.TH "datatypes/datatypes_identify_list.scad" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes/datatypes_identify_list.scad \- List data type identification\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBn_almost_equal\fP (v1, v2, p=6)"
.br
.RI "\fITest if all elements of two lists of numbers are sufficiently equal\&. \fP"
.ti -1c
.RI "function \fBalmost_equal\fP (v1, v2, p=6)"
.br
.RI "\fITest if all numerical elements of two lists of values are sufficiently equal\&. \fP"
.ti -1c
.RI "function \fBcompare\fP (v1, v2, s=true)"
.br
.RI "\fIOrder to lists of arbitrary values\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
List data type identification\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBdatatypes_identify_list\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
