.TH "tv_prim_test_g2_r" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tv_prim_test_g2_r \- Validation Results (group2) 

.PP
.nf
1 ECHO: "OpenSCAD Version [2016, 12, 21]"
2 ECHO: "[ INFO ] run_test(); t01 passed: 'all_equal_T(undef)=false'"
3 ECHO: "[ INFO ] run_test(); t02 passed: 'all_equal_T(1)=false'"
4 ECHO: "[ INFO ] run_test(); t03 passed: 'all_equal_T(true)=true'"
5 ECHO: "[ INFO ] run_test(); t04 passed: 'all_equal_T(false)=false'"
6 ECHO: "[ INFO ] run_test(); t05 passed: 'all_equal_T(a)=false'"
7 ECHO: "[ INFO ] run_test(); t06 passed: 'all_equal_T(This is a longer string)=false'"
8 ECHO: "[ INFO ] run_test(); t07 passed: 'all_equal_T()=true'"
9 ECHO: "[ INFO ] run_test(); t08 passed: 'all_equal_T([])=true'"
10 ECHO: "[ INFO ] run_test(); t09 passed: 'all_equal_T([0 : 1 : 9])=false'"
11 ECHO: "[ INFO ] run_test(); t10 passed: 'all_equal_T([0 : 0\&.5 : 9])=false'"
12 ECHO: "[ INFO ] run_test(); t11 passed: 'all_equal_T([undef])=false'"
13 ECHO: "[ INFO ] run_test(); t12 passed: 'all_equal_T([1])=false'"
14 ECHO: "[ INFO ] run_test(); t13 passed: 'all_equal_T([1, 2, 3])=false'"
15 ECHO: "[ INFO ] run_test(); t14 passed: 'all_equal_T([[1], [2], [3], [4], [5]])=false'"
16 ECHO: "[ INFO ] run_test(); t15 passed: 'all_equal_T([[1, 2], [2, 3]])=false'"
17 ECHO: "[ INFO ] run_test(); t16 passed: 'all_equal_T([[1, 2], [2, 3], [4, 5], "ab"])=false'"
18 ECHO: "[ INFO ] run_test(); t17 passed: 'all_equal_T([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
19 ECHO: "[ INFO ] run_test(); t18 passed: 'all_equal_T([1, 2, 3, undef])=false'"
20 ECHO: "[ INFO ] run_test(); t19 passed: 'all_equal_T([undef, undef, undef, undef])=false'"
21 ECHO: "[ INFO ] run_test(); t20 passed: 'all_equal_T([[undef], [undef], [undef]])=false'"
22 ECHO: "[ INFO ] run_test(); t21 passed: 'all_equal_T([true, true, true, true, false])=false'"
23 ECHO: "[ INFO ] run_test(); t22 passed: 'all_equal_T([true, false, false, false, false])=false'"
24 ECHO: "[ INFO ] run_test(); t23 passed: 'all_equal_T([true, true, true, true])=true'"
25 ECHO: "[ INFO ] run_test(); t01 passed: 'all_equal_F(undef)=false'"
26 ECHO: "[ INFO ] run_test(); t02 passed: 'all_equal_F(1)=false'"
27 ECHO: "[ INFO ] run_test(); t03 passed: 'all_equal_F(true)=false'"
28 ECHO: "[ INFO ] run_test(); t04 passed: 'all_equal_F(false)=true'"
29 ECHO: "[ INFO ] run_test(); t05 passed: 'all_equal_F(a)=false'"
30 ECHO: "[ INFO ] run_test(); t06 passed: 'all_equal_F(This is a longer string)=false'"
31 ECHO: "[ INFO ] run_test(); t07 passed: 'all_equal_F()=true'"
32 ECHO: "[ INFO ] run_test(); t08 passed: 'all_equal_F([])=true'"
33 ECHO: "[ INFO ] run_test(); t09 passed: 'all_equal_F([0 : 1 : 9])=false'"
34 ECHO: "[ INFO ] run_test(); t10 passed: 'all_equal_F([0 : 0\&.5 : 9])=false'"
35 ECHO: "[ INFO ] run_test(); t11 passed: 'all_equal_F([undef])=false'"
36 ECHO: "[ INFO ] run_test(); t12 passed: 'all_equal_F([1])=false'"
37 ECHO: "[ INFO ] run_test(); t13 passed: 'all_equal_F([1, 2, 3])=false'"
38 ECHO: "[ INFO ] run_test(); t14 passed: 'all_equal_F([[1], [2], [3], [4], [5]])=false'"
39 ECHO: "[ INFO ] run_test(); t15 passed: 'all_equal_F([[1, 2], [2, 3]])=false'"
40 ECHO: "[ INFO ] run_test(); t16 passed: 'all_equal_F([[1, 2], [2, 3], [4, 5], "ab"])=false'"
41 ECHO: "[ INFO ] run_test(); t17 passed: 'all_equal_F([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
42 ECHO: "[ INFO ] run_test(); t18 passed: 'all_equal_F([1, 2, 3, undef])=false'"
43 ECHO: "[ INFO ] run_test(); t19 passed: 'all_equal_F([undef, undef, undef, undef])=false'"
44 ECHO: "[ INFO ] run_test(); t20 passed: 'all_equal_F([[undef], [undef], [undef]])=false'"
45 ECHO: "[ INFO ] run_test(); t21 passed: 'all_equal_F([true, true, true, true, false])=false'"
46 ECHO: "[ INFO ] run_test(); t22 passed: 'all_equal_F([true, false, false, false, false])=false'"
47 ECHO: "[ INFO ] run_test(); t23 passed: 'all_equal_F([true, true, true, true])=false'"
48 ECHO: "[ INFO ] run_test(); t01 passed: 'all_equal_U(undef)=true'"
49 ECHO: "[ INFO ] run_test(); t02 passed: 'all_equal_U(1)=false'"
50 ECHO: "[ INFO ] run_test(); t03 passed: 'all_equal_U(true)=false'"
51 ECHO: "[ INFO ] run_test(); t04 passed: 'all_equal_U(false)=false'"
52 ECHO: "[ INFO ] run_test(); t05 passed: 'all_equal_U(a)=false'"
53 ECHO: "[ INFO ] run_test(); t06 passed: 'all_equal_U(This is a longer string)=false'"
54 ECHO: "[ INFO ] run_test(); t07 passed: 'all_equal_U()=true'"
55 ECHO: "[ INFO ] run_test(); t08 passed: 'all_equal_U([])=true'"
56 ECHO: "[ INFO ] run_test(); t09 passed: 'all_equal_U([0 : 1 : 9])=false'"
57 ECHO: "[ INFO ] run_test(); t10 passed: 'all_equal_U([0 : 0\&.5 : 9])=false'"
58 ECHO: "[ INFO ] run_test(); t11 passed: 'all_equal_U([undef])=true'"
59 ECHO: "[ INFO ] run_test(); t12 passed: 'all_equal_U([1])=false'"
60 ECHO: "[ INFO ] run_test(); t13 passed: 'all_equal_U([1, 2, 3])=false'"
61 ECHO: "[ INFO ] run_test(); t14 passed: 'all_equal_U([[1], [2], [3], [4], [5]])=false'"
62 ECHO: "[ INFO ] run_test(); t15 passed: 'all_equal_U([[1, 2], [2, 3]])=false'"
63 ECHO: "[ INFO ] run_test(); t16 passed: 'all_equal_U([[1, 2], [2, 3], [4, 5], "ab"])=false'"
64 ECHO: "[ INFO ] run_test(); t17 passed: 'all_equal_U([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
65 ECHO: "[ INFO ] run_test(); t18 passed: 'all_equal_U([1, 2, 3, undef])=false'"
66 ECHO: "[ INFO ] run_test(); t19 passed: 'all_equal_U([undef, undef, undef, undef])=true'"
67 ECHO: "[ INFO ] run_test(); t20 passed: 'all_equal_U([[undef], [undef], [undef]])=false'"
68 ECHO: "[ INFO ] run_test(); t21 passed: 'all_equal_U([true, true, true, true, false])=false'"
69 ECHO: "[ INFO ] run_test(); t22 passed: 'all_equal_U([true, false, false, false, false])=false'"
70 ECHO: "[ INFO ] run_test(); t23 passed: 'all_equal_U([true, true, true, true])=false'"
71 ECHO: "[ INFO ] run_test(); t01 passed: 'any_equal_T(undef)=false'"
72 ECHO: "[ INFO ] run_test(); t02 passed: 'any_equal_T(1)=false'"
73 ECHO: "[ INFO ] run_test(); t03 passed: 'any_equal_T(true)=true'"
74 ECHO: "[ INFO ] run_test(); t04 passed: 'any_equal_T(false)=false'"
75 ECHO: "[ INFO ] run_test(); t05 passed: 'any_equal_T(a)=false'"
76 ECHO: "[ INFO ] run_test(); t06 passed: 'any_equal_T(This is a longer string)=false'"
77 ECHO: "[ INFO ] run_test(); t07 passed: 'any_equal_T()=false'"
78 ECHO: "[ INFO ] run_test(); t08 passed: 'any_equal_T([])=false'"
79 ECHO: "[ INFO ] run_test(); t09 passed: 'any_equal_T([0 : 1 : 9])=false'"
80 ECHO: "[ INFO ] run_test(); t10 passed: 'any_equal_T([0 : 0\&.5 : 9])=false'"
81 ECHO: "[ INFO ] run_test(); t11 passed: 'any_equal_T([undef])=false'"
82 ECHO: "[ INFO ] run_test(); t12 passed: 'any_equal_T([1])=false'"
83 ECHO: "[ INFO ] run_test(); t13 passed: 'any_equal_T([1, 2, 3])=false'"
84 ECHO: "[ INFO ] run_test(); t14 passed: 'any_equal_T([[1], [2], [3], [4], [5]])=false'"
85 ECHO: "[ INFO ] run_test(); t15 passed: 'any_equal_T([[1, 2], [2, 3]])=false'"
86 ECHO: "[ INFO ] run_test(); t16 passed: 'any_equal_T([[1, 2], [2, 3], [4, 5], "ab"])=false'"
87 ECHO: "[ INFO ] run_test(); t17 passed: 'any_equal_T([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
88 ECHO: "[ INFO ] run_test(); t18 passed: 'any_equal_T([1, 2, 3, undef])=false'"
89 ECHO: "[ INFO ] run_test(); t19 passed: 'any_equal_T([undef, undef, undef, undef])=false'"
90 ECHO: "[ INFO ] run_test(); t20 passed: 'any_equal_T([[undef], [undef], [undef]])=false'"
91 ECHO: "[ INFO ] run_test(); t21 passed: 'any_equal_T([true, true, true, true, false])=true'"
92 ECHO: "[ INFO ] run_test(); t22 passed: 'any_equal_T([true, false, false, false, false])=true'"
93 ECHO: "[ INFO ] run_test(); t23 passed: 'any_equal_T([true, true, true, true])=true'"
94 ECHO: "[ INFO ] run_test(); t01 passed: 'any_equal_F(undef)=false'"
95 ECHO: "[ INFO ] run_test(); t02 passed: 'any_equal_F(1)=false'"
96 ECHO: "[ INFO ] run_test(); t03 passed: 'any_equal_F(true)=false'"
97 ECHO: "[ INFO ] run_test(); t04 passed: 'any_equal_F(false)=true'"
98 ECHO: "[ INFO ] run_test(); t05 passed: 'any_equal_F(a)=false'"
99 ECHO: "[ INFO ] run_test(); t06 passed: 'any_equal_F(This is a longer string)=false'"
100 ECHO: "[ INFO ] run_test(); t07 passed: 'any_equal_F()=false'"
101 ECHO: "[ INFO ] run_test(); t08 passed: 'any_equal_F([])=false'"
102 ECHO: "[ INFO ] run_test(); t09 passed: 'any_equal_F([0 : 1 : 9])=false'"
103 ECHO: "[ INFO ] run_test(); t10 passed: 'any_equal_F([0 : 0\&.5 : 9])=false'"
104 ECHO: "[ INFO ] run_test(); t11 passed: 'any_equal_F([undef])=false'"
105 ECHO: "[ INFO ] run_test(); t12 passed: 'any_equal_F([1])=false'"
106 ECHO: "[ INFO ] run_test(); t13 passed: 'any_equal_F([1, 2, 3])=false'"
107 ECHO: "[ INFO ] run_test(); t14 passed: 'any_equal_F([[1], [2], [3], [4], [5]])=false'"
108 ECHO: "[ INFO ] run_test(); t15 passed: 'any_equal_F([[1, 2], [2, 3]])=false'"
109 ECHO: "[ INFO ] run_test(); t16 passed: 'any_equal_F([[1, 2], [2, 3], [4, 5], "ab"])=false'"
110 ECHO: "[ INFO ] run_test(); t17 passed: 'any_equal_F([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
111 ECHO: "[ INFO ] run_test(); t18 passed: 'any_equal_F([1, 2, 3, undef])=false'"
112 ECHO: "[ INFO ] run_test(); t19 passed: 'any_equal_F([undef, undef, undef, undef])=false'"
113 ECHO: "[ INFO ] run_test(); t20 passed: 'any_equal_F([[undef], [undef], [undef]])=false'"
114 ECHO: "[ INFO ] run_test(); t21 passed: 'any_equal_F([true, true, true, true, false])=true'"
115 ECHO: "[ INFO ] run_test(); t22 passed: 'any_equal_F([true, false, false, false, false])=true'"
116 ECHO: "[ INFO ] run_test(); t23 passed: 'any_equal_F([true, true, true, true])=false'"
117 ECHO: "[ INFO ] run_test(); t01 passed: 'any_equal_U(undef)=true'"
118 ECHO: "[ INFO ] run_test(); t02 passed: 'any_equal_U(1)=false'"
119 ECHO: "[ INFO ] run_test(); t03 passed: 'any_equal_U(true)=false'"
120 ECHO: "[ INFO ] run_test(); t04 passed: 'any_equal_U(false)=false'"
121 ECHO: "[ INFO ] run_test(); t05 passed: 'any_equal_U(a)=false'"
122 ECHO: "[ INFO ] run_test(); t06 passed: 'any_equal_U(This is a longer string)=false'"
123 ECHO: "[ INFO ] run_test(); t07 passed: 'any_equal_U()=false'"
124 ECHO: "[ INFO ] run_test(); t08 passed: 'any_equal_U([])=false'"
125 ECHO: "[ INFO ] run_test(); t09 passed: 'any_equal_U([0 : 1 : 9])=false'"
126 ECHO: "[ INFO ] run_test(); t10 passed: 'any_equal_U([0 : 0\&.5 : 9])=false'"
127 ECHO: "[ INFO ] run_test(); t11 passed: 'any_equal_U([undef])=true'"
128 ECHO: "[ INFO ] run_test(); t12 passed: 'any_equal_U([1])=false'"
129 ECHO: "[ INFO ] run_test(); t13 passed: 'any_equal_U([1, 2, 3])=false'"
130 ECHO: "[ INFO ] run_test(); t14 passed: 'any_equal_U([[1], [2], [3], [4], [5]])=false'"
131 ECHO: "[ INFO ] run_test(); t15 passed: 'any_equal_U([[1, 2], [2, 3]])=false'"
132 ECHO: "[ INFO ] run_test(); t16 passed: 'any_equal_U([[1, 2], [2, 3], [4, 5], "ab"])=false'"
133 ECHO: "[ INFO ] run_test(); t17 passed: 'any_equal_U([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
134 ECHO: "[ INFO ] run_test(); t18 passed: 'any_equal_U([1, 2, 3, undef])=true'"
135 ECHO: "[ INFO ] run_test(); t19 passed: 'any_equal_U([undef, undef, undef, undef])=true'"
136 ECHO: "[ INFO ] run_test(); t20 passed: 'any_equal_U([[undef], [undef], [undef]])=false'"
137 ECHO: "[ INFO ] run_test(); t21 passed: 'any_equal_U([true, true, true, true, false])=false'"
138 ECHO: "[ INFO ] run_test(); t22 passed: 'any_equal_U([true, false, false, false, false])=false'"
139 ECHO: "[ INFO ] run_test(); t23 passed: 'any_equal_U([true, true, true, true])=false'"
140 ECHO: "[ INFO ] run_test(); t01 passed: 'all_defined(undef)=false'"
141 ECHO: "[ INFO ] run_test(); t02 passed: 'all_defined(1)=true'"
142 ECHO: "[ INFO ] run_test(); t03 passed: 'all_defined(true)=true'"
143 ECHO: "[ INFO ] run_test(); t04 passed: 'all_defined(false)=true'"
144 ECHO: "[ INFO ] run_test(); t05 passed: 'all_defined(a)=true'"
145 ECHO: "[ INFO ] run_test(); t06 passed: 'all_defined(This is a longer string)=true'"
146 ECHO: "[ INFO ] run_test(); t07 passed: 'all_defined()=true'"
147 ECHO: "[ INFO ] run_test(); t08 passed: 'all_defined([])=true'"
148 ECHO: "[ INFO ] run_test(); t09 passed: 'all_defined([0 : 1 : 9])=true'"
149 ECHO: "[ INFO ] run_test(); t10 passed: 'all_defined([0 : 0\&.5 : 9])=true'"
150 ECHO: "[ INFO ] run_test(); t11 passed: 'all_defined([undef])=false'"
151 ECHO: "[ INFO ] run_test(); t12 passed: 'all_defined([1])=true'"
152 ECHO: "[ INFO ] run_test(); t13 passed: 'all_defined([1, 2, 3])=true'"
153 ECHO: "[ INFO ] run_test(); t14 passed: 'all_defined([[1], [2], [3], [4], [5]])=true'"
154 ECHO: "[ INFO ] run_test(); t15 passed: 'all_defined([[1, 2], [2, 3]])=true'"
155 ECHO: "[ INFO ] run_test(); t16 passed: 'all_defined([[1, 2], [2, 3], [4, 5], "ab"])=true'"
156 ECHO: "[ INFO ] run_test(); t17 passed: 'all_defined([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=true'"
157 ECHO: "[ INFO ] run_test(); t18 passed: 'all_defined([1, 2, 3, undef])=false'"
158 ECHO: "[ INFO ] run_test(); t19 passed: 'all_defined([undef, undef, undef, undef])=false'"
159 ECHO: "[ INFO ] run_test(); t20 passed: 'all_defined([[undef], [undef], [undef]])=true'"
160 ECHO: "[ INFO ] run_test(); t21 passed: 'all_defined([true, true, true, true, false])=true'"
161 ECHO: "[ INFO ] run_test(); t22 passed: 'all_defined([true, false, false, false, false])=true'"
162 ECHO: "[ INFO ] run_test(); t23 passed: 'all_defined([true, true, true, true])=true'"
163 ECHO: "[ INFO ] run_test(); t01 passed: 'any_undefined(undef)=true'"
164 ECHO: "[ INFO ] run_test(); t02 passed: 'any_undefined(1)=false'"
165 ECHO: "[ INFO ] run_test(); t03 passed: 'any_undefined(true)=false'"
166 ECHO: "[ INFO ] run_test(); t04 passed: 'any_undefined(false)=false'"
167 ECHO: "[ INFO ] run_test(); t05 passed: 'any_undefined(a)=false'"
168 ECHO: "[ INFO ] run_test(); t06 passed: 'any_undefined(This is a longer string)=false'"
169 ECHO: "[ INFO ] run_test(); t07 passed: 'any_undefined()=false'"
170 ECHO: "[ INFO ] run_test(); t08 passed: 'any_undefined([])=false'"
171 ECHO: "[ INFO ] run_test(); t09 passed: 'any_undefined([0 : 1 : 9])=false'"
172 ECHO: "[ INFO ] run_test(); t10 passed: 'any_undefined([0 : 0\&.5 : 9])=false'"
173 ECHO: "[ INFO ] run_test(); t11 passed: 'any_undefined([undef])=true'"
174 ECHO: "[ INFO ] run_test(); t12 passed: 'any_undefined([1])=false'"
175 ECHO: "[ INFO ] run_test(); t13 passed: 'any_undefined([1, 2, 3])=false'"
176 ECHO: "[ INFO ] run_test(); t14 passed: 'any_undefined([[1], [2], [3], [4], [5]])=false'"
177 ECHO: "[ INFO ] run_test(); t15 passed: 'any_undefined([[1, 2], [2, 3]])=false'"
178 ECHO: "[ INFO ] run_test(); t16 passed: 'any_undefined([[1, 2], [2, 3], [4, 5], "ab"])=false'"
179 ECHO: "[ INFO ] run_test(); t17 passed: 'any_undefined([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
180 ECHO: "[ INFO ] run_test(); t18 passed: 'any_undefined([1, 2, 3, undef])=true'"
181 ECHO: "[ INFO ] run_test(); t19 passed: 'any_undefined([undef, undef, undef, undef])=true'"
182 ECHO: "[ INFO ] run_test(); t20 passed: 'any_undefined([[undef], [undef], [undef]])=false'"
183 ECHO: "[ INFO ] run_test(); t21 passed: 'any_undefined([true, true, true, true, false])=false'"
184 ECHO: "[ INFO ] run_test(); t22 passed: 'any_undefined([true, false, false, false, false])=false'"
185 ECHO: "[ INFO ] run_test(); t23 passed: 'any_undefined([true, true, true, true])=false'"
186 ECHO: "[ INFO ] run_test(); t01 passed: 'all_scalars(undef)=undef'"
187 ECHO: "[ INFO ] run_test(); t02 passed: 'all_scalars(1)=true'"
188 ECHO: "[ INFO ] run_test(); t03 passed: 'all_scalars(true)=true'"
189 ECHO: "[ INFO ] run_test(); t04 passed: 'all_scalars(false)=true'"
190 ECHO: "[ INFO ] run_test(); t05 passed: 'all_scalars(a)=false'"
191 ECHO: "[ INFO ] run_test(); t06 passed: 'all_scalars(This is a longer string)=false'"
192 ECHO: "[ INFO ] run_test(); t07 *skip*: 'all_scalars(The empty string)'"
193 ECHO: "[ INFO ] run_test(); t08 *skip*: 'all_scalars(The empty vector)'"
194 ECHO: "[ INFO ] run_test(); t09 *skip*: 'all_scalars(A shorthand range)'"
195 ECHO: "[ INFO ] run_test(); t10 *skip*: 'all_scalars(A range)'"
196 ECHO: "[ INFO ] run_test(); t11 passed: 'all_scalars([undef])=true'"
197 ECHO: "[ INFO ] run_test(); t12 passed: 'all_scalars([1])=true'"
198 ECHO: "[ INFO ] run_test(); t13 passed: 'all_scalars([1, 2, 3])=true'"
199 ECHO: "[ INFO ] run_test(); t14 passed: 'all_scalars([[1], [2], [3], [4], [5]])=false'"
200 ECHO: "[ INFO ] run_test(); t15 passed: 'all_scalars([[1, 2], [2, 3]])=false'"
201 ECHO: "[ INFO ] run_test(); t16 passed: 'all_scalars([[1, 2], [2, 3], [4, 5], "ab"])=false'"
202 ECHO: "[ INFO ] run_test(); t17 passed: 'all_scalars([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
203 ECHO: "[ INFO ] run_test(); t18 passed: 'all_scalars([1, 2, 3, undef])=true'"
204 ECHO: "[ INFO ] run_test(); t19 passed: 'all_scalars([undef, undef, undef, undef])=true'"
205 ECHO: "[ INFO ] run_test(); t20 passed: 'all_scalars([[undef], [undef], [undef]])=false'"
206 ECHO: "[ INFO ] run_test(); t21 passed: 'all_scalars([true, true, true, true, false])=true'"
207 ECHO: "[ INFO ] run_test(); t22 passed: 'all_scalars([true, false, false, false, false])=true'"
208 ECHO: "[ INFO ] run_test(); t23 passed: 'all_scalars([true, true, true, true])=true'"
209 ECHO: "[ INFO ] run_test(); t01 passed: 'all_vectors(undef)=undef'"
210 ECHO: "[ INFO ] run_test(); t02 passed: 'all_vectors(1)=false'"
211 ECHO: "[ INFO ] run_test(); t03 passed: 'all_vectors(true)=false'"
212 ECHO: "[ INFO ] run_test(); t04 passed: 'all_vectors(false)=false'"
213 ECHO: "[ INFO ] run_test(); t05 passed: 'all_vectors(a)=false'"
214 ECHO: "[ INFO ] run_test(); t06 passed: 'all_vectors(This is a longer string)=false'"
215 ECHO: "[ INFO ] run_test(); t07 passed: 'all_vectors()=true'"
216 ECHO: "[ INFO ] run_test(); t08 passed: 'all_vectors([])=true'"
217 ECHO: "[ INFO ] run_test(); t09 passed: 'all_vectors([0 : 1 : 9])=false'"
218 ECHO: "[ INFO ] run_test(); t10 passed: 'all_vectors([0 : 0\&.5 : 9])=false'"
219 ECHO: "[ INFO ] run_test(); t11 passed: 'all_vectors([undef])=false'"
220 ECHO: "[ INFO ] run_test(); t12 passed: 'all_vectors([1])=false'"
221 ECHO: "[ INFO ] run_test(); t13 passed: 'all_vectors([1, 2, 3])=false'"
222 ECHO: "[ INFO ] run_test(); t14 passed: 'all_vectors([[1], [2], [3], [4], [5]])=true'"
223 ECHO: "[ INFO ] run_test(); t15 passed: 'all_vectors([[1, 2], [2, 3]])=true'"
224 ECHO: "[ INFO ] run_test(); t16 passed: 'all_vectors([[1, 2], [2, 3], [4, 5], "ab"])=false'"
225 ECHO: "[ INFO ] run_test(); t17 passed: 'all_vectors([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=true'"
226 ECHO: "[ INFO ] run_test(); t18 passed: 'all_vectors([1, 2, 3, undef])=false'"
227 ECHO: "[ INFO ] run_test(); t19 passed: 'all_vectors([undef, undef, undef, undef])=false'"
228 ECHO: "[ INFO ] run_test(); t20 passed: 'all_vectors([[undef], [undef], [undef]])=true'"
229 ECHO: "[ INFO ] run_test(); t21 passed: 'all_vectors([true, true, true, true, false])=false'"
230 ECHO: "[ INFO ] run_test(); t22 passed: 'all_vectors([true, false, false, false, false])=false'"
231 ECHO: "[ INFO ] run_test(); t23 passed: 'all_vectors([true, true, true, true])=false'"
232 ECHO: "[ INFO ] run_test(); t01 passed: 'all_strings(undef)=undef'"
233 ECHO: "[ INFO ] run_test(); t02 passed: 'all_strings(1)=false'"
234 ECHO: "[ INFO ] run_test(); t03 passed: 'all_strings(true)=false'"
235 ECHO: "[ INFO ] run_test(); t04 passed: 'all_strings(false)=false'"
236 ECHO: "[ INFO ] run_test(); t05 passed: 'all_strings(a)=true'"
237 ECHO: "[ INFO ] run_test(); t06 passed: 'all_strings(This is a longer string)=true'"
238 ECHO: "[ INFO ] run_test(); t07 passed: 'all_strings()=true'"
239 ECHO: "[ INFO ] run_test(); t08 *skip*: 'all_strings(The empty vector)'"
240 ECHO: "[ INFO ] run_test(); t09 passed: 'all_strings([0 : 1 : 9])=false'"
241 ECHO: "[ INFO ] run_test(); t10 passed: 'all_strings([0 : 0\&.5 : 9])=false'"
242 ECHO: "[ INFO ] run_test(); t11 passed: 'all_strings([undef])=false'"
243 ECHO: "[ INFO ] run_test(); t12 passed: 'all_strings([1])=false'"
244 ECHO: "[ INFO ] run_test(); t13 passed: 'all_strings([1, 2, 3])=false'"
245 ECHO: "[ INFO ] run_test(); t14 passed: 'all_strings([[1], [2], [3], [4], [5]])=false'"
246 ECHO: "[ INFO ] run_test(); t15 passed: 'all_strings([[1, 2], [2, 3]])=false'"
247 ECHO: "[ INFO ] run_test(); t16 passed: 'all_strings([[1, 2], [2, 3], [4, 5], "ab"])=false'"
248 ECHO: "[ INFO ] run_test(); t17 passed: 'all_strings([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
249 ECHO: "[ INFO ] run_test(); t18 passed: 'all_strings([1, 2, 3, undef])=false'"
250 ECHO: "[ INFO ] run_test(); t19 passed: 'all_strings([undef, undef, undef, undef])=false'"
251 ECHO: "[ INFO ] run_test(); t20 passed: 'all_strings([[undef], [undef], [undef]])=false'"
252 ECHO: "[ INFO ] run_test(); t21 passed: 'all_strings([true, true, true, true, false])=false'"
253 ECHO: "[ INFO ] run_test(); t22 passed: 'all_strings([true, false, false, false, false])=false'"
254 ECHO: "[ INFO ] run_test(); t23 passed: 'all_strings([true, true, true, true])=false'"
255 ECHO: "[ INFO ] run_test(); t01 passed: 'all_numbers(undef)=undef'"
256 ECHO: "[ INFO ] run_test(); t02 passed: 'all_numbers(1)=true'"
257 ECHO: "[ INFO ] run_test(); t03 passed: 'all_numbers(true)=false'"
258 ECHO: "[ INFO ] run_test(); t04 passed: 'all_numbers(false)=false'"
259 ECHO: "[ INFO ] run_test(); t05 passed: 'all_numbers(a)=false'"
260 ECHO: "[ INFO ] run_test(); t06 passed: 'all_numbers(This is a longer string)=false'"
261 ECHO: "[ INFO ] run_test(); t07 *skip*: 'all_numbers(The empty string)'"
262 ECHO: "[ INFO ] run_test(); t08 *skip*: 'all_numbers(The empty vector)'"
263 ECHO: "[ INFO ] run_test(); t09 passed: 'all_numbers([0 : 1 : 9])=false'"
264 ECHO: "[ INFO ] run_test(); t10 passed: 'all_numbers([0 : 0\&.5 : 9])=false'"
265 ECHO: "[ INFO ] run_test(); t11 passed: 'all_numbers([undef])=false'"
266 ECHO: "[ INFO ] run_test(); t12 passed: 'all_numbers([1])=true'"
267 ECHO: "[ INFO ] run_test(); t13 passed: 'all_numbers([1, 2, 3])=true'"
268 ECHO: "[ INFO ] run_test(); t14 passed: 'all_numbers([[1], [2], [3], [4], [5]])=false'"
269 ECHO: "[ INFO ] run_test(); t15 passed: 'all_numbers([[1, 2], [2, 3]])=false'"
270 ECHO: "[ INFO ] run_test(); t16 passed: 'all_numbers([[1, 2], [2, 3], [4, 5], "ab"])=false'"
271 ECHO: "[ INFO ] run_test(); t17 passed: 'all_numbers([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
272 ECHO: "[ INFO ] run_test(); t18 passed: 'all_numbers([1, 2, 3, undef])=false'"
273 ECHO: "[ INFO ] run_test(); t19 passed: 'all_numbers([undef, undef, undef, undef])=false'"
274 ECHO: "[ INFO ] run_test(); t20 passed: 'all_numbers([[undef], [undef], [undef]])=false'"
275 ECHO: "[ INFO ] run_test(); t21 passed: 'all_numbers([true, true, true, true, false])=false'"
276 ECHO: "[ INFO ] run_test(); t22 passed: 'all_numbers([true, false, false, false, false])=false'"
277 ECHO: "[ INFO ] run_test(); t23 passed: 'all_numbers([true, true, true, true])=false'"
278 ECHO: "[ INFO ] run_test(); t01 passed: 'all_len_1(undef)=undef'"
279 ECHO: "[ INFO ] run_test(); t02 passed: 'all_len_1(1)=false'"
280 ECHO: "[ INFO ] run_test(); t03 passed: 'all_len_1(true)=false'"
281 ECHO: "[ INFO ] run_test(); t04 passed: 'all_len_1(false)=false'"
282 ECHO: "[ INFO ] run_test(); t05 passed: 'all_len_1(a)=true'"
283 ECHO: "[ INFO ] run_test(); t06 passed: 'all_len_1(This is a longer string)=true'"
284 ECHO: "[ INFO ] run_test(); t07 *skip*: 'all_len_1(The empty string)'"
285 ECHO: "[ INFO ] run_test(); t08 *skip*: 'all_len_1(The empty vector)'"
286 ECHO: "[ INFO ] run_test(); t09 passed: 'all_len_1([0 : 1 : 9])=false'"
287 ECHO: "[ INFO ] run_test(); t10 passed: 'all_len_1([0 : 0\&.5 : 9])=false'"
288 ECHO: "[ INFO ] run_test(); t11 passed: 'all_len_1([undef])=false'"
289 ECHO: "[ INFO ] run_test(); t12 passed: 'all_len_1([1])=false'"
290 ECHO: "[ INFO ] run_test(); t13 passed: 'all_len_1([1, 2, 3])=false'"
291 ECHO: "[ INFO ] run_test(); t14 passed: 'all_len_1([[1], [2], [3], [4], [5]])=true'"
292 ECHO: "[ INFO ] run_test(); t15 passed: 'all_len_1([[1, 2], [2, 3]])=false'"
293 ECHO: "[ INFO ] run_test(); t16 passed: 'all_len_1([[1, 2], [2, 3], [4, 5], "ab"])=false'"
294 ECHO: "[ INFO ] run_test(); t17 passed: 'all_len_1([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
295 ECHO: "[ INFO ] run_test(); t18 passed: 'all_len_1([1, 2, 3, undef])=false'"
296 ECHO: "[ INFO ] run_test(); t19 passed: 'all_len_1([undef, undef, undef, undef])=false'"
297 ECHO: "[ INFO ] run_test(); t20 passed: 'all_len_1([[undef], [undef], [undef]])=true'"
298 ECHO: "[ INFO ] run_test(); t21 passed: 'all_len_1([true, true, true, true, false])=false'"
299 ECHO: "[ INFO ] run_test(); t22 passed: 'all_len_1([true, false, false, false, false])=false'"
300 ECHO: "[ INFO ] run_test(); t23 passed: 'all_len_1([true, true, true, true])=false'"
301 ECHO: "[ INFO ] run_test(); t01 passed: 'all_len_2(undef)=undef'"
302 ECHO: "[ INFO ] run_test(); t02 passed: 'all_len_2(1)=false'"
303 ECHO: "[ INFO ] run_test(); t03 passed: 'all_len_2(true)=false'"
304 ECHO: "[ INFO ] run_test(); t04 passed: 'all_len_2(false)=false'"
305 ECHO: "[ INFO ] run_test(); t05 passed: 'all_len_2(a)=false'"
306 ECHO: "[ INFO ] run_test(); t06 passed: 'all_len_2(This is a longer string)=false'"
307 ECHO: "[ INFO ] run_test(); t07 *skip*: 'all_len_2(The empty string)'"
308 ECHO: "[ INFO ] run_test(); t08 *skip*: 'all_len_2(The empty vector)'"
309 ECHO: "[ INFO ] run_test(); t09 passed: 'all_len_2([0 : 1 : 9])=false'"
310 ECHO: "[ INFO ] run_test(); t10 passed: 'all_len_2([0 : 0\&.5 : 9])=false'"
311 ECHO: "[ INFO ] run_test(); t11 passed: 'all_len_2([undef])=false'"
312 ECHO: "[ INFO ] run_test(); t12 passed: 'all_len_2([1])=false'"
313 ECHO: "[ INFO ] run_test(); t13 passed: 'all_len_2([1, 2, 3])=false'"
314 ECHO: "[ INFO ] run_test(); t14 passed: 'all_len_2([[1], [2], [3], [4], [5]])=false'"
315 ECHO: "[ INFO ] run_test(); t15 passed: 'all_len_2([[1, 2], [2, 3]])=true'"
316 ECHO: "[ INFO ] run_test(); t16 passed: 'all_len_2([[1, 2], [2, 3], [4, 5], "ab"])=true'"
317 ECHO: "[ INFO ] run_test(); t17 passed: 'all_len_2([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
318 ECHO: "[ INFO ] run_test(); t18 passed: 'all_len_2([1, 2, 3, undef])=false'"
319 ECHO: "[ INFO ] run_test(); t19 passed: 'all_len_2([undef, undef, undef, undef])=false'"
320 ECHO: "[ INFO ] run_test(); t20 passed: 'all_len_2([[undef], [undef], [undef]])=false'"
321 ECHO: "[ INFO ] run_test(); t21 passed: 'all_len_2([true, true, true, true, false])=false'"
322 ECHO: "[ INFO ] run_test(); t22 passed: 'all_len_2([true, false, false, false, false])=false'"
323 ECHO: "[ INFO ] run_test(); t23 passed: 'all_len_2([true, true, true, true])=false'"
324 ECHO: "[ INFO ] run_test(); t01 passed: 'all_len_3(undef)=undef'"
325 ECHO: "[ INFO ] run_test(); t02 passed: 'all_len_3(1)=false'"
326 ECHO: "[ INFO ] run_test(); t03 passed: 'all_len_3(true)=false'"
327 ECHO: "[ INFO ] run_test(); t04 passed: 'all_len_3(false)=false'"
328 ECHO: "[ INFO ] run_test(); t05 passed: 'all_len_3(a)=false'"
329 ECHO: "[ INFO ] run_test(); t06 passed: 'all_len_3(This is a longer string)=false'"
330 ECHO: "[ INFO ] run_test(); t07 *skip*: 'all_len_3(The empty string)'"
331 ECHO: "[ INFO ] run_test(); t08 *skip*: 'all_len_3(The empty vector)'"
332 ECHO: "[ INFO ] run_test(); t09 passed: 'all_len_3([0 : 1 : 9])=false'"
333 ECHO: "[ INFO ] run_test(); t10 passed: 'all_len_3([0 : 0\&.5 : 9])=false'"
334 ECHO: "[ INFO ] run_test(); t11 passed: 'all_len_3([undef])=false'"
335 ECHO: "[ INFO ] run_test(); t12 passed: 'all_len_3([1])=false'"
336 ECHO: "[ INFO ] run_test(); t13 passed: 'all_len_3([1, 2, 3])=false'"
337 ECHO: "[ INFO ] run_test(); t14 passed: 'all_len_3([[1], [2], [3], [4], [5]])=false'"
338 ECHO: "[ INFO ] run_test(); t15 passed: 'all_len_3([[1, 2], [2, 3]])=false'"
339 ECHO: "[ INFO ] run_test(); t16 passed: 'all_len_3([[1, 2], [2, 3], [4, 5], "ab"])=false'"
340 ECHO: "[ INFO ] run_test(); t17 passed: 'all_len_3([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=true'"
341 ECHO: "[ INFO ] run_test(); t18 passed: 'all_len_3([1, 2, 3, undef])=false'"
342 ECHO: "[ INFO ] run_test(); t19 passed: 'all_len_3([undef, undef, undef, undef])=false'"
343 ECHO: "[ INFO ] run_test(); t20 passed: 'all_len_3([[undef], [undef], [undef]])=false'"
344 ECHO: "[ INFO ] run_test(); t21 passed: 'all_len_3([true, true, true, true, false])=false'"
345 ECHO: "[ INFO ] run_test(); t22 passed: 'all_len_3([true, false, false, false, false])=false'"
346 ECHO: "[ INFO ] run_test(); t23 passed: 'all_len_3([true, true, true, true])=false'"
347 ECHO: "[ INFO ] run_test(); t01 passed: 'almost_equal_AA(undef)=true'"
348 ECHO: "[ INFO ] run_test(); t02 passed: 'almost_equal_AA(1)=true'"
349 ECHO: "[ INFO ] run_test(); t03 passed: 'almost_equal_AA(true)=true'"
350 ECHO: "[ INFO ] run_test(); t04 passed: 'almost_equal_AA(false)=true'"
351 ECHO: "[ INFO ] run_test(); t05 passed: 'almost_equal_AA(a)=true'"
352 ECHO: "[ INFO ] run_test(); t06 passed: 'almost_equal_AA(This is a longer string)=true'"
353 ECHO: "[ INFO ] run_test(); t07 passed: 'almost_equal_AA()=true'"
354 ECHO: "[ INFO ] run_test(); t08 passed: 'almost_equal_AA([])=true'"
355 ECHO: "[ INFO ] run_test(); t09 passed: 'almost_equal_AA([0 : 1 : 9])=true'"
356 ECHO: "[ INFO ] run_test(); t10 passed: 'almost_equal_AA([0 : 0\&.5 : 9])=true'"
357 ECHO: "[ INFO ] run_test(); t11 passed: 'almost_equal_AA([undef])=true'"
358 ECHO: "[ INFO ] run_test(); t12 passed: 'almost_equal_AA([1])=true'"
359 ECHO: "[ INFO ] run_test(); t13 passed: 'almost_equal_AA([1, 2, 3])=true'"
360 ECHO: "[ INFO ] run_test(); t14 passed: 'almost_equal_AA([[1], [2], [3], [4], [5]])=true'"
361 ECHO: "[ INFO ] run_test(); t15 passed: 'almost_equal_AA([[1, 2], [2, 3]])=true'"
362 ECHO: "[ INFO ] run_test(); t16 passed: 'almost_equal_AA([[1, 2], [2, 3], [4, 5], "ab"])=true'"
363 ECHO: "[ INFO ] run_test(); t17 passed: 'almost_equal_AA([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=true'"
364 ECHO: "[ INFO ] run_test(); t18 passed: 'almost_equal_AA([1, 2, 3, undef])=true'"
365 ECHO: "[ INFO ] run_test(); t19 passed: 'almost_equal_AA([undef, undef, undef, undef])=true'"
366 ECHO: "[ INFO ] run_test(); t20 passed: 'almost_equal_AA([[undef], [undef], [undef]])=true'"
367 ECHO: "[ INFO ] run_test(); t21 passed: 'almost_equal_AA([true, true, true, true, false])=true'"
368 ECHO: "[ INFO ] run_test(); t22 passed: 'almost_equal_AA([true, false, false, false, false])=true'"
369 ECHO: "[ INFO ] run_test(); t23 passed: 'almost_equal_AA([true, true, true, true])=true'"
370 ECHO: "[ INFO ] run_test(); t01 passed: 'almost_equal_T(undef)=false'"
371 ECHO: "[ INFO ] run_test(); t02 passed: 'almost_equal_T(1)=false'"
372 ECHO: "[ INFO ] run_test(); t03 passed: 'almost_equal_T(true)=true'"
373 ECHO: "[ INFO ] run_test(); t04 passed: 'almost_equal_T(false)=false'"
374 ECHO: "[ INFO ] run_test(); t05 passed: 'almost_equal_T(a)=false'"
375 ECHO: "[ INFO ] run_test(); t06 passed: 'almost_equal_T(This is a longer string)=false'"
376 ECHO: "[ INFO ] run_test(); t07 passed: 'almost_equal_T()=false'"
377 ECHO: "[ INFO ] run_test(); t08 passed: 'almost_equal_T([])=false'"
378 ECHO: "[ INFO ] run_test(); t09 passed: 'almost_equal_T([0 : 1 : 9])=false'"
379 ECHO: "[ INFO ] run_test(); t10 passed: 'almost_equal_T([0 : 0\&.5 : 9])=false'"
380 ECHO: "[ INFO ] run_test(); t11 passed: 'almost_equal_T([undef])=false'"
381 ECHO: "[ INFO ] run_test(); t12 passed: 'almost_equal_T([1])=false'"
382 ECHO: "[ INFO ] run_test(); t13 passed: 'almost_equal_T([1, 2, 3])=false'"
383 ECHO: "[ INFO ] run_test(); t14 passed: 'almost_equal_T([[1], [2], [3], [4], [5]])=false'"
384 ECHO: "[ INFO ] run_test(); t15 passed: 'almost_equal_T([[1, 2], [2, 3]])=false'"
385 ECHO: "[ INFO ] run_test(); t16 passed: 'almost_equal_T([[1, 2], [2, 3], [4, 5], "ab"])=false'"
386 ECHO: "[ INFO ] run_test(); t17 passed: 'almost_equal_T([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
387 ECHO: "[ INFO ] run_test(); t18 passed: 'almost_equal_T([1, 2, 3, undef])=false'"
388 ECHO: "[ INFO ] run_test(); t19 passed: 'almost_equal_T([undef, undef, undef, undef])=false'"
389 ECHO: "[ INFO ] run_test(); t20 passed: 'almost_equal_T([[undef], [undef], [undef]])=false'"
390 ECHO: "[ INFO ] run_test(); t21 passed: 'almost_equal_T([true, true, true, true, false])=false'"
391 ECHO: "[ INFO ] run_test(); t22 passed: 'almost_equal_T([true, false, false, false, false])=false'"
392 ECHO: "[ INFO ] run_test(); t23 passed: 'almost_equal_T([true, true, true, true])=false'"
393 ECHO: "[ INFO ] run_test(); t01 passed: 'almost_equal_F(undef)=false'"
394 ECHO: "[ INFO ] run_test(); t02 passed: 'almost_equal_F(1)=false'"
395 ECHO: "[ INFO ] run_test(); t03 passed: 'almost_equal_F(true)=false'"
396 ECHO: "[ INFO ] run_test(); t04 passed: 'almost_equal_F(false)=true'"
397 ECHO: "[ INFO ] run_test(); t05 passed: 'almost_equal_F(a)=false'"
398 ECHO: "[ INFO ] run_test(); t06 passed: 'almost_equal_F(This is a longer string)=false'"
399 ECHO: "[ INFO ] run_test(); t07 passed: 'almost_equal_F()=false'"
400 ECHO: "[ INFO ] run_test(); t08 passed: 'almost_equal_F([])=false'"
401 ECHO: "[ INFO ] run_test(); t09 passed: 'almost_equal_F([0 : 1 : 9])=false'"
402 ECHO: "[ INFO ] run_test(); t10 passed: 'almost_equal_F([0 : 0\&.5 : 9])=false'"
403 ECHO: "[ INFO ] run_test(); t11 passed: 'almost_equal_F([undef])=false'"
404 ECHO: "[ INFO ] run_test(); t12 passed: 'almost_equal_F([1])=false'"
405 ECHO: "[ INFO ] run_test(); t13 passed: 'almost_equal_F([1, 2, 3])=false'"
406 ECHO: "[ INFO ] run_test(); t14 passed: 'almost_equal_F([[1], [2], [3], [4], [5]])=false'"
407 ECHO: "[ INFO ] run_test(); t15 passed: 'almost_equal_F([[1, 2], [2, 3]])=false'"
408 ECHO: "[ INFO ] run_test(); t16 passed: 'almost_equal_F([[1, 2], [2, 3], [4, 5], "ab"])=false'"
409 ECHO: "[ INFO ] run_test(); t17 passed: 'almost_equal_F([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
410 ECHO: "[ INFO ] run_test(); t18 passed: 'almost_equal_F([1, 2, 3, undef])=false'"
411 ECHO: "[ INFO ] run_test(); t19 passed: 'almost_equal_F([undef, undef, undef, undef])=false'"
412 ECHO: "[ INFO ] run_test(); t20 passed: 'almost_equal_F([[undef], [undef], [undef]])=false'"
413 ECHO: "[ INFO ] run_test(); t21 passed: 'almost_equal_F([true, true, true, true, false])=false'"
414 ECHO: "[ INFO ] run_test(); t22 passed: 'almost_equal_F([true, false, false, false, false])=false'"
415 ECHO: "[ INFO ] run_test(); t23 passed: 'almost_equal_F([true, true, true, true])=false'"
416 ECHO: "[ INFO ] run_test(); t01 passed: 'almost_equal_U(undef)=true'"
417 ECHO: "[ INFO ] run_test(); t02 passed: 'almost_equal_U(1)=false'"
418 ECHO: "[ INFO ] run_test(); t03 passed: 'almost_equal_U(true)=false'"
419 ECHO: "[ INFO ] run_test(); t04 passed: 'almost_equal_U(false)=false'"
420 ECHO: "[ INFO ] run_test(); t05 passed: 'almost_equal_U(a)=false'"
421 ECHO: "[ INFO ] run_test(); t06 passed: 'almost_equal_U(This is a longer string)=false'"
422 ECHO: "[ INFO ] run_test(); t07 passed: 'almost_equal_U()=false'"
423 ECHO: "[ INFO ] run_test(); t08 passed: 'almost_equal_U([])=false'"
424 ECHO: "[ INFO ] run_test(); t09 passed: 'almost_equal_U([0 : 1 : 9])=false'"
425 ECHO: "[ INFO ] run_test(); t10 passed: 'almost_equal_U([0 : 0\&.5 : 9])=false'"
426 ECHO: "[ INFO ] run_test(); t11 passed: 'almost_equal_U([undef])=false'"
427 ECHO: "[ INFO ] run_test(); t12 passed: 'almost_equal_U([1])=false'"
428 ECHO: "[ INFO ] run_test(); t13 passed: 'almost_equal_U([1, 2, 3])=false'"
429 ECHO: "[ INFO ] run_test(); t14 passed: 'almost_equal_U([[1], [2], [3], [4], [5]])=false'"
430 ECHO: "[ INFO ] run_test(); t15 passed: 'almost_equal_U([[1, 2], [2, 3]])=false'"
431 ECHO: "[ INFO ] run_test(); t16 passed: 'almost_equal_U([[1, 2], [2, 3], [4, 5], "ab"])=false'"
432 ECHO: "[ INFO ] run_test(); t17 passed: 'almost_equal_U([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
433 ECHO: "[ INFO ] run_test(); t18 passed: 'almost_equal_U([1, 2, 3, undef])=false'"
434 ECHO: "[ INFO ] run_test(); t19 passed: 'almost_equal_U([undef, undef, undef, undef])=false'"
435 ECHO: "[ INFO ] run_test(); t20 passed: 'almost_equal_U([[undef], [undef], [undef]])=false'"
436 ECHO: "[ INFO ] run_test(); t21 passed: 'almost_equal_U([true, true, true, true, false])=false'"
437 ECHO: "[ INFO ] run_test(); t22 passed: 'almost_equal_U([true, false, false, false, false])=false'"
438 ECHO: "[ INFO ] run_test(); t23 passed: 'almost_equal_U([true, true, true, true])=false'"
439 ECHO: "[ INFO ] run_test(); t01 passed: 'compare_AA(undef)=true'"
440 ECHO: "[ INFO ] run_test(); t02 passed: 'compare_AA(1)=true'"
441 ECHO: "[ INFO ] run_test(); t03 passed: 'compare_AA(true)=true'"
442 ECHO: "[ INFO ] run_test(); t04 passed: 'compare_AA(false)=true'"
443 ECHO: "[ INFO ] run_test(); t05 passed: 'compare_AA(a)=true'"
444 ECHO: "[ INFO ] run_test(); t06 passed: 'compare_AA(This is a longer string)=true'"
445 ECHO: "[ INFO ] run_test(); t07 passed: 'compare_AA()=true'"
446 ECHO: "[ INFO ] run_test(); t08 passed: 'compare_AA([])=true'"
447 ECHO: "[ INFO ] run_test(); t09 passed: 'compare_AA([0 : 1 : 9])=true'"
448 ECHO: "[ INFO ] run_test(); t10 passed: 'compare_AA([0 : 0\&.5 : 9])=true'"
449 ECHO: "[ INFO ] run_test(); t11 passed: 'compare_AA([undef])=true'"
450 ECHO: "[ INFO ] run_test(); t12 passed: 'compare_AA([1])=true'"
451 ECHO: "[ INFO ] run_test(); t13 passed: 'compare_AA([1, 2, 3])=true'"
452 ECHO: "[ INFO ] run_test(); t14 passed: 'compare_AA([[1], [2], [3], [4], [5]])=true'"
453 ECHO: "[ INFO ] run_test(); t15 passed: 'compare_AA([[1, 2], [2, 3]])=true'"
454 ECHO: "[ INFO ] run_test(); t16 passed: 'compare_AA([[1, 2], [2, 3], [4, 5], "ab"])=true'"
455 ECHO: "[ INFO ] run_test(); t17 passed: 'compare_AA([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=true'"
456 ECHO: "[ INFO ] run_test(); t18 passed: 'compare_AA([1, 2, 3, undef])=true'"
457 ECHO: "[ INFO ] run_test(); t19 passed: 'compare_AA([undef, undef, undef, undef])=true'"
458 ECHO: "[ INFO ] run_test(); t20 passed: 'compare_AA([[undef], [undef], [undef]])=true'"
459 ECHO: "[ INFO ] run_test(); t21 passed: 'compare_AA([true, true, true, true, false])=true'"
460 ECHO: "[ INFO ] run_test(); t22 passed: 'compare_AA([true, false, false, false, false])=true'"
461 ECHO: "[ INFO ] run_test(); t23 passed: 'compare_AA([true, true, true, true])=true'"

.fi
.PP
 
