.TH "datatypes/datatypes_identify_iterable.scad" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes/datatypes_identify_iterable.scad \- Iterable data type identification\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBall_equal\fP (v, cv)"
.br
.RI "\fITest if a list of values equal a comparison value\&. \fP"
.ti -1c
.RI "function \fBany_equal\fP (v, cv)"
.br
.RI "\fITest if any element of a list of values equal a comparison value\&. \fP"
.ti -1c
.RI "function \fBall_defined\fP (v)"
.br
.RI "\fITest if no element of a list of values is undefined\&. \fP"
.ti -1c
.RI "function \fBany_undefined\fP (v)"
.br
.RI "\fITest if any element of a list of values is undefined\&. \fP"
.ti -1c
.RI "function \fBall_scalars\fP (v)"
.br
.RI "\fITest if all elements of a list of values are scalars\&. \fP"
.ti -1c
.RI "function \fBall_lists\fP (v)"
.br
.RI "\fITest if all elements of a list of values are lists\&. \fP"
.ti -1c
.RI "function \fBall_strings\fP (v)"
.br
.RI "\fITest if all elements of a list of values are strings\&. \fP"
.ti -1c
.RI "function \fBall_numbers\fP (v)"
.br
.RI "\fITest if all elements of a list of values are numbers\&. \fP"
.ti -1c
.RI "function \fBall_len\fP (v, l)"
.br
.RI "\fITest if all elements of a list of values are lists of a specified length\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Iterable data type identification\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&.
.PP
\fBNote:\fP
.RS 4
Include this library file using the \fBinclude\fP statement\&. 
.RE
.PP

.PP
Definition in file \fBdatatypes_identify_iterable\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
