.TH "math Directory Reference" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmath-base\&.scad\fP"
.br
.RI "\fIInclude file wrapper of math base primitives\&. \fP"
.ti -1c
.RI "file \fBmath_bitwise\&.scad\fP"
.br
.RI "\fIMathematical base-two bitwise binary functions\&. \fP"
.ti -1c
.RI "file \fBmath_linear_algebra\&.scad\fP"
.br
.RI "\fILinear algebra mathematical functions\&. \fP"
.ti -1c
.RI "file \fBmath_oshapes\&.scad\fP"
.br
.RI "\fIOther shapes mathematical functions\&. \fP"
.ti -1c
.RI "file \fBmath_polytope\&.scad\fP"
.br
.RI "\fIPolygon and polyhedron mathematical functions\&. \fP"
.ti -1c
.RI "file \fBmath_triangle\&.scad\fP"
.br
.RI "\fITriangle solutions mathematical functions\&. \fP"
.ti -1c
.RI "file \fBmath_utility\&.scad\fP"
.br
.RI "\fIMiscellaneous mathematical utilities\&. \fP"
.ti -1c
.RI "file \fBmath_vector_algebra\&.scad\fP"
.br
.RI "\fIVector algebra mathematical functions\&. \fP"
.in -1c
