.TH "tools/tools_align.scad" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools/tools_align.scad \- Shape alignment tools\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <math\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBorient_ll\fP (l=\fBz_axis3d_ul\fP, rl=\fBz_axis3d_ul\fP, r=0)"
.br
.RI "\fIOrient a line or vector to a reference line or vector\&. \fP"
.ti -1c
.RI "module \fBalign_ll\fP (l=\fBz_axis3d_ul\fP, rl=\fBz_axis3d_ul\fP, ap=0, rp=0, r=0, to=\fBorigin3d\fP, ro=\fBzero3d\fP)"
.br
.RI "\fIAlign a line or vector to a reference line or vector\&. \fP"
.ti -1c
.RI "module \fBalign_l\fP (rl=\fBz_axis3d_ul\fP, rp=0, r=0, to=\fBorigin3d\fP, ro=\fBzero3d\fP, d=\fBz_axis_ci\fP)"
.br
.RI "\fIAlign a shapes' x, y, or z Cartesian axis to reference line or vector\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape alignment tools\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBtools_align\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
