.TH "shapes_3d" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shapes_3d \- 3d Shapes
.PP
Three-dimensional geometric shapes\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBshapes3d\&.scad\fP"
.br
.RI "\fIThree-dimensional basic shapes\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBcone\fP (r, h, d, vr, vr1, vr2)"
.br
.RI "\fIA cone\&. \fP"
.ti -1c
.RI "module \fBcuboid\fP (size, vr, vrm=0, center=false)"
.br
.RI "\fIA cuboid with edge, fillet, or chamfer corners\&. \fP"
.ti -1c
.RI "module \fBellipsoid\fP (size)"
.br
.RI "\fIAn ellipsoid\&. \fP"
.ti -1c
.RI "module \fBellipsoid_s\fP (size, a1=0, a2=0)"
.br
.RI "\fIA sector of an ellipsoid\&. \fP"
.ti -1c
.RI "module \fBpyramid_t\fP (size, center=false)"
.br
.RI "\fIA pyramid with trilateral base formed by four equilateral triangles\&. \fP"
.ti -1c
.RI "module \fBpyramid_q\fP (size, center=false)"
.br
.RI "\fIA pyramid with quadrilateral base\&. \fP"
.ti -1c
.RI "module \fBstar3d\fP (size, n=5, half=false)"
.br
.RI "\fIA three-dimensional star\&. \fP"
.ti -1c
.RI "module \fBtorus_rp\fP (size, core, r, l, t, co, cr=0, vr, vr1, vr2, vrm=0, vrm1, vrm2, pa=0, ra=360, m=255, center=false, profile=false)"
.br
.RI "\fIA rectangular cross-sectional profile revolved about the z-axis\&. \fP"
.ti -1c
.RI "module \fBtorus_tp\fP (size, core, r, l, co, cr=0, vr, vr1, vr2, pa=0, ra=360, m=255, centroid=false, incenter=false, profile=false,)"
.br
.RI "\fIA triangular cross-sectional profile revolved about the z-axis\&. \fP"
.ti -1c
.RI "module \fBtorus_ep\fP (size, core, r, l, t, a1=0, a2=0, co, cr=0, pa=0, ra=360, m=255, profile=false)"
.br
.RI "\fIAn elliptical cross-sectional profile revolved about the z-axis\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Three-dimensional geometric shapes\&. 


.SH "Function Documentation"
.PP 
.SS "module cone (r, h, d, vr, vr1, vr2)"

.PP
A cone\&. 
.PP
\fBParameters:\fP
.RS 4
\fIr\fP <decimal> The base radius\&. 
.br
\fIh\fP <decimal> The height\&.
.br
\fId\fP <decimal> The base diameter\&.
.br
\fIvr\fP <decimal> The default corner rounding radius\&. 
.br
\fIvr1\fP <decimal> The base corner rounding radius\&. 
.br
\fIvr2\fP <decimal> The point corner rounding radius\&.
.RE
.PP
\fBExample\fP cone cone 
.PP
.nf
1       cone( h=25, r=10, vr=2 );

.fi
.PP
 
.PP
Definition at line 107 of file shapes3d\&.scad\&.
.SS "module cuboid (size, vr, vrm = \fC0\fP, center = \fCfalse\fP)"

.PP
A cuboid with edge, fillet, or chamfer corners\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal-list-3|decimal> A list [x, y, z] of decimals or a single decimal for (x=y=z)\&.
.br
\fIvr\fP <decimal> The corner rounding radius\&.
.br
\fIvrm\fP <integer> The radius mode\&. A 2-bit encoded integer that indicates edge and vertex finish\&. \fIB0\fP controls edge and \fIB1\fP controls vertex\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBExample\fP cuboid cuboid 
.PP
.nf
1       cuboid( size=[25,40,20], vr=5, center=true );

.fi
.PP
.PP
vrm B1 B0 Description  0 0 0 \fIfillet\fP edges with \fIfillet\fP vertexes 1 0 1 \fIchamfer\fP edges with \fIsphere\fP vertexes 2 1 0 \fIfillet\fP edges with \fIchamfer\fP vertexes 3 1 1 \fIchamfer\fP edges with \fIchamfer\fP vertexes 
.PP
\fBNote:\fP
.RS 4
Using \fIfillet\fP replaces all edges with a quarter circle of radius \fCvr\fP, inset \fC[vr, vr]\fP from the each edge\&. 
.PP
Using \fIchamfer\fP replaces all edges with isosceles right triangles with side lengths equal to the corner rounding radius \fCvr\fP\&. Therefore the chamfer length will be \fCvr*sqrt(2)\fP at 45 degree angles\&. 
.RE
.PP

.PP
Definition at line 172 of file shapes3d\&.scad\&.
.SS "module ellipsoid (size)"

.PP
An ellipsoid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal-list-2|decimal> A list [w, h] of decimals or a single decimal for (w=h)\&.
.RE
.PP
\fBExample\fP ellipsoid ellipsoid 
.PP
.nf
1       ellipsoid( size=[40,25] );

.fi
.PP
 
.PP
Definition at line 257 of file shapes3d\&.scad\&.
.SS "module ellipsoid_s (size, a1 = \fC0\fP, a2 = \fC0\fP)"

.PP
A sector of an ellipsoid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal-list-2|decimal> A list [w, h] of decimals or a single decimal for (w=h)\&.
.br
\fIa1\fP <decimal> The start angle in degrees\&. 
.br
\fIa2\fP <decimal> The stop angle in degrees\&.
.RE
.PP
\fBExample\fP ellipsoid_s ellipsoid_s 
.PP
.nf
1       ellipsoid_s( size=[60,15], a1=0, a2=270 );

.fi
.PP
 
.PP
Definition at line 289 of file shapes3d\&.scad\&.
.SS "module pyramid_q (size, center = \fCfalse\fP)"

.PP
A pyramid with quadrilateral base\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal-list-3|decimal> A list [x, y, z] of decimals or a single decimal for (x=y=z)\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBExample\fP pyramid_q pyramid_q 
.PP
.nf
1       pyramid_q( size=[35,20,5], center=true );

.fi
.PP
.PP
\fBTodo\fP
.RS 4
Support vertex rounding radius\&. 
.RE
.PP

.PP
Definition at line 391 of file shapes3d\&.scad\&.
.SS "module pyramid_t (size, center = \fCfalse\fP)"

.PP
A pyramid with trilateral base formed by four equilateral triangles\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal> The face radius\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBExample\fP pyramid_t pyramid_t 
.PP
.nf
1       pyramid_t( size=20, center=true );

.fi
.PP
.PP
\fBTodo\fP
.RS 4
Support vertex rounding radius\&. 
.RE
.PP

.PP
Definition at line 347 of file shapes3d\&.scad\&.
.SS "module star3d (size, n = \fC5\fP, half = \fCfalse\fP)"

.PP
A three-dimensional star\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal-list-3|decimal> A list [l, w, h] of decimals or a single decimal for (size=l=2*w=4*h)\&.
.br
\fIn\fP <decimal> The number of points\&.
.br
\fIhalf\fP <boolean> Render upper half only\&.
.RE
.PP
\fBExample\fP star3d star3d 
.PP
.nf
1       star3d( size=40, n=5, half=true );

.fi
.PP
 
.PP
Definition at line 437 of file shapes3d\&.scad\&.
.SS "module torus_ep (size, core, r, l, t, a1 = \fC0\fP, a2 = \fC0\fP, co, cr = \fC0\fP, pa = \fC0\fP, ra = \fC360\fP, m = \fC255\fP, profile = \fCfalse\fP)"

.PP
An elliptical cross-sectional profile revolved about the z-axis\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal-list-2|decimal> The profile size\&. A list [x, y] of decimals or a single decimal for (x=y)\&. 
.br
\fIcore\fP <decimal-list-2|decimal> The profile core\&. A list [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIr\fP <decimal> The rotation radius\&. 
.br
\fIl\fP <decimal-list-2|decimal> The elongation length\&. A list [x, y] of decimals or a single decimal for (x=y)
.br
\fIt\fP <decimal-list-2|decimal> The profile thickness\&. A list [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIa1\fP <decimal> The profile start angle in degrees\&. 
.br
\fIa2\fP <decimal> The profile stop angle in degrees\&.
.br
\fIco\fP <decimal-list-2> Core offset\&. A list [x, y] of decimals\&. 
.br
\fIcr\fP <decimal> Core z-rotation\&.
.br
\fIpa\fP <decimal> The profile pitch angle in degrees\&. 
.br
\fIra\fP <decimal> The rotation sweep angle in degrees\&. 
.br
\fIm\fP <integer> The section render mode\&. An 8-bit encoded integer that indicates the revolution sections to render\&.
.br
\fIprofile\fP <boolean> Show profile only (do not extrude)\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBrotate_extrude_tre\fP for description of extrude parameters\&.
.RE
.PP
Thickness \fCt\fP 
.PD 0

.IP "\(bu" 2
\fCcore = size - t\fP; when \fCt\fP and \fCsize\fP are given\&. 
.IP "\(bu" 2
\fCsize = core + t\fP; when \fCt\fP and \fCcore\fP are given\&.
.PP
\fBExample\fP torus_ep torus_ep 
.PP
.nf
1       torus_ep( size=[20,15], t=[2,4], r=50, a1=0, a2=180, pa=90, ra=270, co=[0,2] );

.fi
.PP
 
.PP
Definition at line 659 of file shapes3d\&.scad\&.
.SS "module torus_rp (size, core, r, l, t, co, cr = \fC0\fP, vr, vr1, vr2, vrm = \fC0\fP, vrm1, vrm2, pa = \fC0\fP, ra = \fC360\fP, m = \fC255\fP, center = \fCfalse\fP, profile = \fCfalse\fP)"

.PP
A rectangular cross-sectional profile revolved about the z-axis\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal-list-2|decimal> The profile size\&. A list [x, y] of decimals or a single decimal for (x=y)\&. 
.br
\fIcore\fP <decimal-list-2|decimal> The profile core\&. A list [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIr\fP <decimal> The rotation radius\&. 
.br
\fIl\fP <decimal-list-2|decimal> The elongation length\&. A list [x, y] of decimals or a single decimal for (x=y)
.br
\fIt\fP <decimal-list-2|decimal> The profile thickness\&. A list [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIco\fP <decimal-list-2> Core offset\&. A list [x, y] of decimals\&. 
.br
\fIcr\fP <decimal> Core z-rotation\&.
.br
\fIvr\fP <decimal-list-4|decimal> The profile default corner rounding radius\&. A list [v1r, v2r, v3r, v4r] of decimals or a single decimal for (v1r=v2r=v3r=v4r)\&. Unspecified corners are not rounded\&. 
.br
\fIvr1\fP <decimal-list-4|decimal> The profile outer corner rounding radius\&. 
.br
\fIvr2\fP <decimal-list-4|decimal> The profile core corner rounding radius\&.
.br
\fIvrm\fP <integer> The default corner radius mode\&. A 4-bit encoded integer that indicates each corner finish\&. Use bit value \fB0\fP for \fIfillet\fP and \fB1\fP for \fIchamfer\fP\&. 
.br
\fIvrm1\fP <integer> The outer corner radius mode\&. 
.br
\fIvrm2\fP <integer> The core corner radius mode\&.
.br
\fIpa\fP <decimal> The profile pitch angle in degrees\&. 
.br
\fIra\fP <decimal> The rotation sweep angle in degrees\&. 
.br
\fIm\fP <integer> The section render mode\&. An 8-bit encoded integer that indicates the revolution sections to render\&.
.br
\fIcenter\fP <boolean> Rotate about profile center\&. 
.br
\fIprofile\fP <boolean> Show profile only (do not extrude)\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBrotate_extrude_tre\fP for description of extrude parameters\&.
.RE
.PP
Thickness \fCt\fP 
.PD 0

.IP "\(bu" 2
\fCcore = size - t\fP; when \fCt\fP and \fCsize\fP are given\&. 
.IP "\(bu" 2
\fCsize = core + t\fP; when \fCt\fP and \fCcore\fP are given\&.
.PP
\fBExample\fP torus_rp torus_rp 
.PP
.nf
1       torus_rp( size=[40,20], core=[35,20], r=40, l=[90,60], co=[0,2\&.5], vr=4, vrm=15, center=true );

.fi
.PP
 
.PP
Definition at line 520 of file shapes3d\&.scad\&.
.SS "module torus_tp (size, core, r, l, co, cr = \fC0\fP, vr, vr1, vr2, pa = \fC0\fP, ra = \fC360\fP, m = \fC255\fP, centroid = \fCfalse\fP, incenter = \fCfalse\fP, profile = \fCfalse\fP)"

.PP
A triangular cross-sectional profile revolved about the z-axis\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <decimal-list-3|decimal> The size\&. A list [s1, s2, s3] of decimals or a single decimal for (s1=s2=s3)\&. 
.br
\fIcore\fP <decimal-list-3|decimal> The core\&. A list [s1, s2, s3] of decimals or a single decimal for (s1=s2=s3)\&.
.br
\fIr\fP <decimal> The rotation radius\&. 
.br
\fIl\fP <decimal-list-2|decimal> The elongation length\&. A list [x, y] of decimals or a single decimal for (x=y)
.br
\fIco\fP <decimal-list-2> Core offset\&. A list [x, y] of decimals\&. 
.br
\fIcr\fP <decimal> Core z-rotation\&.
.br
\fIvr\fP <decimal-list-3|decimal> The default vertex rounding radius\&. A list [v1r, v2r, v3r] of decimals or a single decimal for (v1r=v2r=v3r)\&. 
.br
\fIvr1\fP <decimal-list-3|decimal> The outer vertex rounding radius\&. 
.br
\fIvr2\fP <decimal-list-3|decimal> The core vertex rounding radius\&.
.br
\fIpa\fP <decimal> The profile pitch angle in degrees\&. 
.br
\fIra\fP <decimal> The rotation sweep angle in degrees\&. 
.br
\fIm\fP <integer> The section render mode\&. An 8-bit encoded integer that indicates the revolution sections to render\&.
.br
\fIcentroid\fP <boolean> Rotate about profile centroid\&. 
.br
\fIincenter\fP <boolean> Rotate about profile incenter\&. 
.br
\fIprofile\fP <boolean> Show profile only (do not extrude)\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBrotate_extrude_tre\fP for description of extrude parameters\&.
.RE
.PP
\fBExample\fP torus_tp torus_tp 
.PP
.nf
1       torus_tp( size=40, core=30, r=60, co=[0,-4], vr=4, pa=90, ra=270, centroid=true );

.fi
.PP
.PP
\fBNote:\fP
.RS 4
The outer and inner triangles centroids are aligned prior to the core removal\&. 
.RE
.PP

.PP
Definition at line 592 of file shapes3d\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
