.TH "data_console" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data_console \- Console
.PP
Console message logging\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconsole\&.scad\fP"
.br
.RI "\fIMessage logging functions\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBlog_echo\fP (m)"
.br
.RI "\fIOutput message to console\&. \fP"
.ti -1c
.RI "module \fBlog_debug\fP (m)"
.br
.RI "\fIOutput diagnostic message to console\&. \fP"
.ti -1c
.RI "module \fBlog_info\fP (m)"
.br
.RI "\fIOutput information message to console\&. \fP"
.ti -1c
.RI "module \fBlog_warn\fP (m)"
.br
.RI "\fIOutput warning message to console\&. \fP"
.ti -1c
.RI "module \fBlog_error\fP (m)"
.br
.RI "\fIOutput error message to console\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Console message logging\&. 

\fBExample\fP 
.PP
 
.PP
.nf
    use <console\&.scad>;

    $log_debug = true;
    message = "console log message";

    // general
    log_echo( message );

    // debugging
    log_debug( message );
    log_debug( message, $log_debug = false );

    // information
    log_info( message );

    // warning
    log_warn( message );

    // error
    log_error( message );

.fi
.PP
.PP
\fBResult\fP 
.PP
.nf
1 ECHO: "console log message"
2 ECHO: "[ DEBUG ] root(); console log message"
3 ECHO: "[ INFO ] root(); console log message"
4 ECHO: 
5 ECHO: "root()"
6 ECHO: "###################################"
7 ECHO: "# [ WARNING ] console log message #"
8 ECHO: "###################################"
9 ECHO: 
10 ECHO: "root()"
11 ECHO: "###################################"
12 ECHO: "###################################"
13 ECHO: "##                               ##"
14 ECHO: "## [ ERROR ] console log message ##"
15 ECHO: "##                               ##"
16 ECHO: "###################################"
17 ECHO: "###################################"

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "module log_debug (m)"

.PP
Output diagnostic message to console\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP <string> An output message\&.
.RE
.PP
When \fC$log_debug\fP == \fCtrue\fP, message is written to the console\&. When \fCfalse\fP, output is not generated\&. 
.PP
Definition at line 77 of file console\&.scad\&.
.SS "module log_echo (m)"

.PP
Output message to console\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP <string> An output message\&. 
.RE
.PP

.PP
Definition at line 61 of file console\&.scad\&.
.SS "module log_error (m)"

.PP
Output error message to console\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP <string> An output message\&.
.RE
.PP
Output an error message to the console\&. Ideally, rendering should halt and the script should exit\&. However, no suitable abort function exists\&. To alert of the critical error, the error message is also rendered graphically\&. 
.PP
Definition at line 138 of file console\&.scad\&.
.SS "module log_info (m)"

.PP
Output information message to console\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP <string> An output message\&. 
.RE
.PP

.PP
Definition at line 94 of file console\&.scad\&.
.SS "module log_warn (m)"

.PP
Output warning message to console\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP <string> An output message\&. 
.RE
.PP

.PP
Definition at line 109 of file console\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
