.TH "tv_datatypes_identify_list_r" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tv_datatypes_identify_list_r \- Results 

.PP
.nf
1 ECHO: "OpenSCAD Version [2017, 2, 19]"
2 ECHO: "[ INFO ] run_test(); t01 passed: 'n_almost_equal_AA(undef)=false'"
3 ECHO: "[ INFO ] run_test(); t02 passed: 'n_almost_equal_AA(1)=true'"
4 ECHO: "[ INFO ] run_test(); t03 passed: 'n_almost_equal_AA(true)=false'"
5 ECHO: "[ INFO ] run_test(); t04 passed: 'n_almost_equal_AA(false)=false'"
6 ECHO: "[ INFO ] run_test(); t05 passed: 'n_almost_equal_AA(a)=false'"
7 ECHO: "[ INFO ] run_test(); t06 passed: 'n_almost_equal_AA(This is a longer string)=false'"
8 ECHO: "[ INFO ] run_test(); t07 passed: 'n_almost_equal_AA()=false'"
9 ECHO: "[ INFO ] run_test(); t08 passed: 'n_almost_equal_AA([])=false'"
10 ECHO: "[ INFO ] run_test(); t09 passed: 'n_almost_equal_AA([0 : 1 : 9])=false'"
11 ECHO: "[ INFO ] run_test(); t10 passed: 'n_almost_equal_AA([0 : 0\&.5 : 9])=false'"
12 ECHO: "[ INFO ] run_test(); t11 passed: 'n_almost_equal_AA([undef])=false'"
13 ECHO: "[ INFO ] run_test(); t12 passed: 'n_almost_equal_AA([1])=true'"
14 ECHO: "[ INFO ] run_test(); t13 passed: 'n_almost_equal_AA([1, 2, 3])=true'"
15 ECHO: "[ INFO ] run_test(); t14 passed: 'n_almost_equal_AA([[1], [2], [3], [4], [5]])=false'"
16 ECHO: "[ INFO ] run_test(); t15 passed: 'n_almost_equal_AA([[1, 2], [2, 3]])=false'"
17 ECHO: "[ INFO ] run_test(); t16 passed: 'n_almost_equal_AA([[1, 2], [2, 3], [4, 5], "ab"])=false'"
18 ECHO: "[ INFO ] run_test(); t17 passed: 'n_almost_equal_AA([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
19 ECHO: "[ INFO ] run_test(); t18 passed: 'n_almost_equal_AA([1, 2, 3, undef])=false'"
20 ECHO: "[ INFO ] run_test(); t19 passed: 'n_almost_equal_AA([undef, undef, undef, undef])=false'"
21 ECHO: "[ INFO ] run_test(); t20 passed: 'n_almost_equal_AA([[undef], [undef], [undef]])=false'"
22 ECHO: "[ INFO ] run_test(); t21 passed: 'n_almost_equal_AA([true, true, true, true, false])=false'"
23 ECHO: "[ INFO ] run_test(); t22 passed: 'n_almost_equal_AA([true, false, false, false, false])=false'"
24 ECHO: "[ INFO ] run_test(); t23 passed: 'n_almost_equal_AA([true, true, true, true])=false'"
25 ECHO: "[ INFO ] run_test(); t01 passed: 'almost_equal_AA(undef)=true'"
26 ECHO: "[ INFO ] run_test(); t02 passed: 'almost_equal_AA(1)=true'"
27 ECHO: "[ INFO ] run_test(); t03 passed: 'almost_equal_AA(true)=true'"
28 ECHO: "[ INFO ] run_test(); t04 passed: 'almost_equal_AA(false)=true'"
29 ECHO: "[ INFO ] run_test(); t05 passed: 'almost_equal_AA(a)=true'"
30 ECHO: "[ INFO ] run_test(); t06 passed: 'almost_equal_AA(This is a longer string)=true'"
31 ECHO: "[ INFO ] run_test(); t07 passed: 'almost_equal_AA()=true'"
32 ECHO: "[ INFO ] run_test(); t08 passed: 'almost_equal_AA([])=true'"
33 ECHO: "[ INFO ] run_test(); t09 passed: 'almost_equal_AA([0 : 1 : 9])=true'"
34 ECHO: "[ INFO ] run_test(); t10 passed: 'almost_equal_AA([0 : 0\&.5 : 9])=true'"
35 ECHO: "[ INFO ] run_test(); t11 passed: 'almost_equal_AA([undef])=true'"
36 ECHO: "[ INFO ] run_test(); t12 passed: 'almost_equal_AA([1])=true'"
37 ECHO: "[ INFO ] run_test(); t13 passed: 'almost_equal_AA([1, 2, 3])=true'"
38 ECHO: "[ INFO ] run_test(); t14 passed: 'almost_equal_AA([[1], [2], [3], [4], [5]])=true'"
39 ECHO: "[ INFO ] run_test(); t15 passed: 'almost_equal_AA([[1, 2], [2, 3]])=true'"
40 ECHO: "[ INFO ] run_test(); t16 passed: 'almost_equal_AA([[1, 2], [2, 3], [4, 5], "ab"])=true'"
41 ECHO: "[ INFO ] run_test(); t17 passed: 'almost_equal_AA([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=true'"
42 ECHO: "[ INFO ] run_test(); t18 passed: 'almost_equal_AA([1, 2, 3, undef])=true'"
43 ECHO: "[ INFO ] run_test(); t19 passed: 'almost_equal_AA([undef, undef, undef, undef])=true'"
44 ECHO: "[ INFO ] run_test(); t20 passed: 'almost_equal_AA([[undef], [undef], [undef]])=true'"
45 ECHO: "[ INFO ] run_test(); t21 passed: 'almost_equal_AA([true, true, true, true, false])=true'"
46 ECHO: "[ INFO ] run_test(); t22 passed: 'almost_equal_AA([true, false, false, false, false])=true'"
47 ECHO: "[ INFO ] run_test(); t23 passed: 'almost_equal_AA([true, true, true, true])=true'"
48 ECHO: "[ INFO ] run_test(); t01 passed: 'almost_equal_T(undef)=false'"
49 ECHO: "[ INFO ] run_test(); t02 passed: 'almost_equal_T(1)=false'"
50 ECHO: "[ INFO ] run_test(); t03 passed: 'almost_equal_T(true)=true'"
51 ECHO: "[ INFO ] run_test(); t04 passed: 'almost_equal_T(false)=false'"
52 ECHO: "[ INFO ] run_test(); t05 passed: 'almost_equal_T(a)=false'"
53 ECHO: "[ INFO ] run_test(); t06 passed: 'almost_equal_T(This is a longer string)=false'"
54 ECHO: "[ INFO ] run_test(); t07 passed: 'almost_equal_T()=false'"
55 ECHO: "[ INFO ] run_test(); t08 passed: 'almost_equal_T([])=false'"
56 ECHO: "[ INFO ] run_test(); t09 passed: 'almost_equal_T([0 : 1 : 9])=false'"
57 ECHO: "[ INFO ] run_test(); t10 passed: 'almost_equal_T([0 : 0\&.5 : 9])=false'"
58 ECHO: "[ INFO ] run_test(); t11 passed: 'almost_equal_T([undef])=false'"
59 ECHO: "[ INFO ] run_test(); t12 passed: 'almost_equal_T([1])=false'"
60 ECHO: "[ INFO ] run_test(); t13 passed: 'almost_equal_T([1, 2, 3])=false'"
61 ECHO: "[ INFO ] run_test(); t14 passed: 'almost_equal_T([[1], [2], [3], [4], [5]])=false'"
62 ECHO: "[ INFO ] run_test(); t15 passed: 'almost_equal_T([[1, 2], [2, 3]])=false'"
63 ECHO: "[ INFO ] run_test(); t16 passed: 'almost_equal_T([[1, 2], [2, 3], [4, 5], "ab"])=false'"
64 ECHO: "[ INFO ] run_test(); t17 passed: 'almost_equal_T([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
65 ECHO: "[ INFO ] run_test(); t18 passed: 'almost_equal_T([1, 2, 3, undef])=false'"
66 ECHO: "[ INFO ] run_test(); t19 passed: 'almost_equal_T([undef, undef, undef, undef])=false'"
67 ECHO: "[ INFO ] run_test(); t20 passed: 'almost_equal_T([[undef], [undef], [undef]])=false'"
68 ECHO: "[ INFO ] run_test(); t21 passed: 'almost_equal_T([true, true, true, true, false])=false'"
69 ECHO: "[ INFO ] run_test(); t22 passed: 'almost_equal_T([true, false, false, false, false])=false'"
70 ECHO: "[ INFO ] run_test(); t23 passed: 'almost_equal_T([true, true, true, true])=false'"
71 ECHO: "[ INFO ] run_test(); t01 passed: 'almost_equal_F(undef)=false'"
72 ECHO: "[ INFO ] run_test(); t02 passed: 'almost_equal_F(1)=false'"
73 ECHO: "[ INFO ] run_test(); t03 passed: 'almost_equal_F(true)=false'"
74 ECHO: "[ INFO ] run_test(); t04 passed: 'almost_equal_F(false)=true'"
75 ECHO: "[ INFO ] run_test(); t05 passed: 'almost_equal_F(a)=false'"
76 ECHO: "[ INFO ] run_test(); t06 passed: 'almost_equal_F(This is a longer string)=false'"
77 ECHO: "[ INFO ] run_test(); t07 passed: 'almost_equal_F()=false'"
78 ECHO: "[ INFO ] run_test(); t08 passed: 'almost_equal_F([])=false'"
79 ECHO: "[ INFO ] run_test(); t09 passed: 'almost_equal_F([0 : 1 : 9])=false'"
80 ECHO: "[ INFO ] run_test(); t10 passed: 'almost_equal_F([0 : 0\&.5 : 9])=false'"
81 ECHO: "[ INFO ] run_test(); t11 passed: 'almost_equal_F([undef])=false'"
82 ECHO: "[ INFO ] run_test(); t12 passed: 'almost_equal_F([1])=false'"
83 ECHO: "[ INFO ] run_test(); t13 passed: 'almost_equal_F([1, 2, 3])=false'"
84 ECHO: "[ INFO ] run_test(); t14 passed: 'almost_equal_F([[1], [2], [3], [4], [5]])=false'"
85 ECHO: "[ INFO ] run_test(); t15 passed: 'almost_equal_F([[1, 2], [2, 3]])=false'"
86 ECHO: "[ INFO ] run_test(); t16 passed: 'almost_equal_F([[1, 2], [2, 3], [4, 5], "ab"])=false'"
87 ECHO: "[ INFO ] run_test(); t17 passed: 'almost_equal_F([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
88 ECHO: "[ INFO ] run_test(); t18 passed: 'almost_equal_F([1, 2, 3, undef])=false'"
89 ECHO: "[ INFO ] run_test(); t19 passed: 'almost_equal_F([undef, undef, undef, undef])=false'"
90 ECHO: "[ INFO ] run_test(); t20 passed: 'almost_equal_F([[undef], [undef], [undef]])=false'"
91 ECHO: "[ INFO ] run_test(); t21 passed: 'almost_equal_F([true, true, true, true, false])=false'"
92 ECHO: "[ INFO ] run_test(); t22 passed: 'almost_equal_F([true, false, false, false, false])=false'"
93 ECHO: "[ INFO ] run_test(); t23 passed: 'almost_equal_F([true, true, true, true])=false'"
94 ECHO: "[ INFO ] run_test(); t01 passed: 'almost_equal_U(undef)=true'"
95 ECHO: "[ INFO ] run_test(); t02 passed: 'almost_equal_U(1)=false'"
96 ECHO: "[ INFO ] run_test(); t03 passed: 'almost_equal_U(true)=false'"
97 ECHO: "[ INFO ] run_test(); t04 passed: 'almost_equal_U(false)=false'"
98 ECHO: "[ INFO ] run_test(); t05 passed: 'almost_equal_U(a)=false'"
99 ECHO: "[ INFO ] run_test(); t06 passed: 'almost_equal_U(This is a longer string)=false'"
100 ECHO: "[ INFO ] run_test(); t07 passed: 'almost_equal_U()=false'"
101 ECHO: "[ INFO ] run_test(); t08 passed: 'almost_equal_U([])=false'"
102 ECHO: "[ INFO ] run_test(); t09 passed: 'almost_equal_U([0 : 1 : 9])=false'"
103 ECHO: "[ INFO ] run_test(); t10 passed: 'almost_equal_U([0 : 0\&.5 : 9])=false'"
104 ECHO: "[ INFO ] run_test(); t11 passed: 'almost_equal_U([undef])=false'"
105 ECHO: "[ INFO ] run_test(); t12 passed: 'almost_equal_U([1])=false'"
106 ECHO: "[ INFO ] run_test(); t13 passed: 'almost_equal_U([1, 2, 3])=false'"
107 ECHO: "[ INFO ] run_test(); t14 passed: 'almost_equal_U([[1], [2], [3], [4], [5]])=false'"
108 ECHO: "[ INFO ] run_test(); t15 passed: 'almost_equal_U([[1, 2], [2, 3]])=false'"
109 ECHO: "[ INFO ] run_test(); t16 passed: 'almost_equal_U([[1, 2], [2, 3], [4, 5], "ab"])=false'"
110 ECHO: "[ INFO ] run_test(); t17 passed: 'almost_equal_U([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=false'"
111 ECHO: "[ INFO ] run_test(); t18 passed: 'almost_equal_U([1, 2, 3, undef])=false'"
112 ECHO: "[ INFO ] run_test(); t19 passed: 'almost_equal_U([undef, undef, undef, undef])=false'"
113 ECHO: "[ INFO ] run_test(); t20 passed: 'almost_equal_U([[undef], [undef], [undef]])=false'"
114 ECHO: "[ INFO ] run_test(); t21 passed: 'almost_equal_U([true, true, true, true, false])=false'"
115 ECHO: "[ INFO ] run_test(); t22 passed: 'almost_equal_U([true, false, false, false, false])=false'"
116 ECHO: "[ INFO ] run_test(); t23 passed: 'almost_equal_U([true, true, true, true])=false'"
117 ECHO: "[ INFO ] run_test(); t01 passed: 'compare_AA(undef)=true'"
118 ECHO: "[ INFO ] run_test(); t02 passed: 'compare_AA(1)=true'"
119 ECHO: "[ INFO ] run_test(); t03 passed: 'compare_AA(true)=true'"
120 ECHO: "[ INFO ] run_test(); t04 passed: 'compare_AA(false)=true'"
121 ECHO: "[ INFO ] run_test(); t05 passed: 'compare_AA(a)=true'"
122 ECHO: "[ INFO ] run_test(); t06 passed: 'compare_AA(This is a longer string)=true'"
123 ECHO: "[ INFO ] run_test(); t07 passed: 'compare_AA()=true'"
124 ECHO: "[ INFO ] run_test(); t08 passed: 'compare_AA([])=true'"
125 ECHO: "[ INFO ] run_test(); t09 passed: 'compare_AA([0 : 1 : 9])=true'"
126 ECHO: "[ INFO ] run_test(); t10 passed: 'compare_AA([0 : 0\&.5 : 9])=true'"
127 ECHO: "[ INFO ] run_test(); t11 passed: 'compare_AA([undef])=true'"
128 ECHO: "[ INFO ] run_test(); t12 passed: 'compare_AA([1])=true'"
129 ECHO: "[ INFO ] run_test(); t13 passed: 'compare_AA([1, 2, 3])=true'"
130 ECHO: "[ INFO ] run_test(); t14 passed: 'compare_AA([[1], [2], [3], [4], [5]])=true'"
131 ECHO: "[ INFO ] run_test(); t15 passed: 'compare_AA([[1, 2], [2, 3]])=true'"
132 ECHO: "[ INFO ] run_test(); t16 passed: 'compare_AA([[1, 2], [2, 3], [4, 5], "ab"])=true'"
133 ECHO: "[ INFO ] run_test(); t17 passed: 'compare_AA([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=true'"
134 ECHO: "[ INFO ] run_test(); t18 passed: 'compare_AA([1, 2, 3, undef])=true'"
135 ECHO: "[ INFO ] run_test(); t19 passed: 'compare_AA([undef, undef, undef, undef])=true'"
136 ECHO: "[ INFO ] run_test(); t20 passed: 'compare_AA([[undef], [undef], [undef]])=true'"
137 ECHO: "[ INFO ] run_test(); t21 passed: 'compare_AA([true, true, true, true, false])=true'"
138 ECHO: "[ INFO ] run_test(); t22 passed: 'compare_AA([true, false, false, false, false])=true'"
139 ECHO: "[ INFO ] run_test(); t23 passed: 'compare_AA([true, true, true, true])=true'"

.fi
.PP
 
