.TH "data" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
data \- Data
.PP
Data values and reference\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBConsole\fP"
.br
.RI "\fIConsole message logging\&. \fP"
.ti -1c
.RI "\fBDatatable\fP"
.br
.RI "\fIData table encoding and lookup\&. \fP"
.ti -1c
.RI "\fBMap\fP"
.br
.RI "\fIMapped data access via key-value pairs\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconsole\&.scad\fP"
.br
.RI "\fIMessage logging functions\&. \fP"
.ti -1c
.RI "file \fBmap\&.scad\fP"
.br
.RI "\fIMapped key-value pair data access\&. \fP"
.ti -1c
.RI "file \fBtable\&.scad\fP"
.br
.RI "\fIData table encoding and lookup\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data values and reference\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
