.TH "tool_edge.scad" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tool_edge.scad \- Shape edge finishing tools\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <shapes2d\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBedge_profile_r\fP (r, p=0, f=1, a=90,)"
.br
.RI "\fIA 2D edge-finish profile specified by intersection radius\&. \fP"
.ti -1c
.RI "module \fBedge_add_r\fP (r, l=1, p=0, f=1, m=3, ba=45, a1=0, a2=90, center=false)"
.br
.RI "\fIA 3D edge-finish additive shape specified by intersection radius\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape edge finishing tools\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBtool_edge\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
