.TH "datatypes/datatypes_operate_iterable.scad" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes/datatypes_operate_iterable.scad \- Iterable data type operations\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBedefined_or\fP (v, i, d)"
.br
.RI "\fIReturn an iterable element when it exists or a default value when it does not\&. \fP"
.ti -1c
.RI "function \fBfind\fP (mv, v, c=1, i, i1=0, i2)"
.br
.RI "\fIFind the occurrences of a match value in an iterable value\&. \fP"
.ti -1c
.RI "function \fBcount\fP (mv, v, s=true, i)"
.br
.RI "\fICount all occurrences of a match value in an iterable value\&. \fP"
.ti -1c
.RI "function \fBexists\fP (mv, v, s=true, i)"
.br
.RI "\fICheck for the existence of a match value in an iterable value\&. \fP"
.ti -1c
.RI "function \fBfirst\fP (v)"
.br
.RI "\fIReturn the first element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBsecond\fP (v)"
.br
.RI "\fIReturn the second element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBthird\fP (v)"
.br
.RI "\fIReturn the third element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBlast\fP (v)"
.br
.RI "\fIReturn the last element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBnfirst\fP (v, n=1)"
.br
.RI "\fIReturn a list containing the first n elements of an iterable value\&. \fP"
.ti -1c
.RI "function \fBnlast\fP (v, n=1)"
.br
.RI "\fIReturn a list containing the last n elements of an iterable value\&. \fP"
.ti -1c
.RI "function \fBnhead\fP (v, n=1)"
.br
.RI "\fIReturn a list containing all but the last n elements of an iterable value\&. \fP"
.ti -1c
.RI "function \fBntail\fP (v, n=1)"
.br
.RI "\fIReturn a list containing all but the first n elements of an iterable value\&. \fP"
.ti -1c
.RI "function \fBreverse\fP (v)"
.br
.RI "\fIReverse the elements of an iterable value\&. \fP"
.ti -1c
.RI "function \fBrselect\fP (v, i)"
.br
.RI "\fISelect a range of elements from an iterable value\&. \fP"
.ti -1c
.RI "function \fBnssequence\fP (v, n=1, s=1, w=false)"
.br
.RI "\fIReturn a list of all n-element sequential-subsets of an iterable value\&. \fP"
.ti -1c
.RI "function \fBeappend\fP (nv, v, r=true, j=true, l=true)"
.br
.RI "\fIAppend a value to each element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBinsert\fP (nv, v, i=0, mv, mi=0, s=true, si)"
.br
.RI "\fIInsert a new value into an iterable value\&. \fP"
.ti -1c
.RI "function \fBdelete\fP (v, i, mv, mc=1, s=true, si)"
.br
.RI "\fIDelete elements from an iterable value\&. \fP"
.ti -1c
.RI "function \fBstrip\fP (v, mv=\fBempty_lst\fP)"
.br
.RI "\fIStrip all matching values from an iterable value\&. \fP"
.ti -1c
.RI "function \fBunique\fP (v)"
.br
.RI "\fIReturn the unique elements of an iterable value\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Iterable data type operations\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&.
.PP
\fBNote:\fP
.RS 4
Include this library file using the \fBinclude\fP statement\&. 
.RE
.PP

.PP
Definition in file \fBdatatypes_operate_iterable\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
