.TH "units/units_resolution.scad" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units/units_resolution.scad \- An abstraction for arc rendering resolution control\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <console\&.scad>\fP
.br
\fC#include <constants\&.scad>\fP
.br
\fC#include <units/units_length\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBresolution_fn\fP (r)"
.br
.RI "\fIReturn facets number for the given arc radius\&. \fP"
.ti -1c
.RI "function \fBresolution_fs\fP ()"
.br
.RI "\fIReturn minimum facets size\&. \fP"
.ti -1c
.RI "function \fBresolution_fa\fP (r)"
.br
.RI "\fIReturn the minimum facets angle\&. \fP"
.ti -1c
.RI "function \fBresolution_reduced\fP ()"
.br
.RI "\fIReturn the radius at which arc resolution will begin to degrade\&. \fP"
.ti -1c
.RI "module \fBresolution_info\fP (r)"
.br
.RI "\fIOutput resolution information to the console for given radius\&. \fP"
.ti -1c
.RI "function \fBresolution_facets\fP (r)"
.br
.RI "\fIReturn facet count used to render a radius\&. \fP"
.ti -1c
.RI "function \fBresolution_facetsv\fP (r)"
.br
.RI "\fIReturn facet count information list used to render a radius\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$resolution_mode\fP = 'fast'"
.br
.RI "\fI<string> Global special variable that configures the arc resolution mode\&. \fP"
.ti -1c
.RI "\fB$resolution_value\fP = 0"
.br
.RI "\fI<number> Global special variable for modes that use custom resolutions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
An abstraction for arc rendering resolution control\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&.
.PP
\fBNote:\fP
.RS 4
Include this library file using the \fBinclude\fP statement\&.
.RE
.PP
\fBTest\fP
.RS 4
Review model for accuracy\&.
.RE
.PP

.PP
Definition in file \fBunits_resolution\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
