.TH "tools_repeat" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools_repeat \- Repeat
.PP
Shape repetition and distribution tools\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtools_utility\&.scad\fP"
.br
.RI "\fIShape transformation utility tools\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBradial_repeat\fP (n, r=1, angle=true, move=false)"
.br
.RI "\fIDistribute copies of a 2d or 3d shape equally about a z-axis radius\&. \fP"
.ti -1c
.RI "module \fBgrid_repeat\fP (g, i, c=1, center=false)"
.br
.RI "\fIDistribute copies of 2d or 3d shapes about Cartesian grid\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape repetition and distribution tools\&. 


.SH "Function Documentation"
.PP 
.SS "module grid_repeat (g, i, c = \fC1\fP, center = \fCfalse\fP)"

.PP
Distribute copies of 2d or 3d shapes about Cartesian grid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIg\fP <integer-list-3|integer> The grid division count\&. A list [x, y, z] of integers or a single integer for (x=y=z)\&. 
.br
\fIi\fP <decimal-list-3|decimal> The grid increment size\&. A list [x, y, z] of decimals or a single decimal for (x=y=z)\&. 
.br
\fIc\fP <integer> The number of copies\&. Number of times to iterate over children\&. 
.br
\fIcenter\fP <boolean> Center distribution about origin\&.
.RE
.PP
\fBExample\fP grid_repeat grid_repeat 
.PP
.nf
1       grid_repeat( g=[5,5,4], i=10, c=50, center=true ) {cube(10, center=true); sphere(10);}

.fi
.PP
 
.PP
Definition at line 357 of file tools_utility\&.scad\&.
.SS "module radial_repeat (n, r = \fC1\fP, angle = \fCtrue\fP, move = \fCfalse\fP)"

.PP
Distribute copies of a 2d or 3d shape equally about a z-axis radius\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP <integer> The number of equally spaced radii\&. 
.br
\fIr\fP <decimal> The shape move radius\&. 
.br
\fIangle\fP <boolean> Rotate each copy about z-axis\&. 
.br
\fImove\fP <boolean> Move each shape copy to radii coordinate\&.
.RE
.PP
\fBExample\fP radial_repeat radial_repeat 
.PP
.nf
1       radial_repeat( n=7, r=6, move=true ) square( [20,1], center=true );

.fi
.PP
 
.PP
Definition at line 326 of file tools_utility\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
