.TH "prim_vector" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
prim_vector \- Vector Operations
.PP
Vector operation primitives\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBprimitives\&.scad\fP"
.br
.RI "\fIMathematical primitive functions\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBconsts\fP (l, v)"
.br
.RI "\fICreate a vector of constant elements\&. \fP"
.ti -1c
.RI "function \fBvstr\fP (v)"
.br
.RI "\fIConvert all vector elements to strings and concatenate\&. \fP"
.ti -1c
.RI "function \fBsum\fP (v, i1, i2)"
.br
.RI "\fICompute the sum of a vector of numbers\&. \fP"
.ti -1c
.RI "function \fBdefined_or\fP (v, d)"
.br
.RI "\fIReturn a defined or default value\&. \fP"
.ti -1c
.RI "function \fBedefined_or\fP (v, i, d)"
.br
.RI "\fIReturn a defined vector element or default value\&. \fP"
.ti -1c
.RI "function \fBfirst\fP (v)"
.br
.RI "\fIReturn the first element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBsecond\fP (v)"
.br
.RI "\fIReturn the second element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBlast\fP (v)"
.br
.RI "\fIReturn the last element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBhead\fP (v)"
.br
.RI "\fIReturn a vector containing the first element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBtail\fP (v)"
.br
.RI "\fIReturn a vector containing all but the first element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBrselect\fP (v, i)"
.br
.RI "\fISelect a range of elements from an iterable value\&. \fP"
.ti -1c
.RI "function \fBeselect\fP (v, f=true, l=false, i)"
.br
.RI "\fISelect an element from each iterable value\&. \fP"
.ti -1c
.RI "function \fBciselect\fP (v, i)"
.br
.RI "\fICase-like select a value from a vector of ordered options by index\&. \fP"
.ti -1c
.RI "function \fBcmvselect\fP (v, mv)"
.br
.RI "\fICase-like select a value from a vector of identified options by match-value\&. \fP"
.ti -1c
.RI "function \fBsmerge\fP (v, r=false)"
.br
.RI "\fISerial-merge vectors of iterable values\&. \fP"
.ti -1c
.RI "function \fBpmerge\fP (v, j=true)"
.br
.RI "\fIParallel-merge vectors of iterable values\&. \fP"
.ti -1c
.RI "function \fBreverse\fP (v)"
.br
.RI "\fIReverse the elements of an iterable value\&. \fP"
.ti -1c
.RI "function \fBqsort\fP (v, r=false)"
.br
.RI "\fISort the numeric or string elements of a vector using quick sort\&. \fP"
.ti -1c
.RI "function \fBqsort2\fP (v, d=0, r=false, s=true)"
.br
.RI "\fIHierarchically sort all elements of a vector using quick sort\&. \fP"
.ti -1c
.RI "function \fBstrip\fP (v, mv=\fBempty_v\fP)"
.br
.RI "\fIStrip all matching values from an iterable value\&. \fP"
.ti -1c
.RI "function \fBappend\fP (nv, v, r=true, j=true, l=true)"
.br
.RI "\fIAppend a value to each element of an iterable value\&. \fP"
.ti -1c
.RI "function \fBinsert\fP (nv, v, i=0, mv, mi=0)"
.br
.RI "\fIInsert a new value into an iterable value\&. \fP"
.ti -1c
.RI "function \fBdelete\fP (v, i, mv, mc=0)"
.br
.RI "\fIDelete elements from an iterable value\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Vector operation primitives\&. 

See validation \fBresults\fP\&. 
.SH "Function Documentation"
.PP 
.SS "function append (nv, v, r = \fCtrue\fP, j = \fCtrue\fP, l = \fCtrue\fP)"

.PP
Append a value to each element of an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fInv\fP <value> A new value to append\&. 
.br
\fIv\fP <vector> A vector of values\&. 
.br
\fIr\fP <boolean> Reduce vector element value before appending\&. 
.br
\fIj\fP <boolean> Join each appendage as a vector\&. 
.br
\fIl\fP <boolean> Append to last element\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> With \fCnv\fP appended to each element of \fCv\fP\&. Returns \fBundef\fP when \fCv\fP is not defined or is not iterable\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
v1=[["a"], ["b"], ["c"], ["d"]];
v2=[1, 2, 3];

echo( append( v2, v1 ) );
echo( append( v2, v1, r=false ) );
echo( append( v2, v1, j=false, l=false ) );

.fi
.PP
.PP
\fBResult\fP 
.PP
.nf
ECHO: [["a", 1, 2, 3], ["b", 1, 2, 3], ["c", 1, 2, 3], ["d", 1, 2, 3]]
ECHO: [[["a"], 1, 2, 3], [["b"], 1, 2, 3], [["c"], 1, 2, 3], [["d"], 1, 2, 3]]
ECHO: ["a", 1, 2, 3, "b", 1, 2, 3, "c", 1, 2, 3, "d"]

.fi
.PP
.PP
\fBNote:\fP
.RS 4
Appending with reduction causes \fCnv\fP to be appended to the \fIelements\fP of each value of \fCv\fP that is a vector\&. Otherwise, \fCnv\fP is appended to the \fIvector\fP itself of each value of \fCv\fP that is a vector\&. 
.RE
.PP

.SS "function ciselect (v, i)"

.PP
Case-like select a value from a vector of ordered options by index\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector of values\&. 
.br
\fIi\fP <integer> Element selection index\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<value> The value of the vector element at the specified index\&. Returns the default value when \fCi\fP does not map to an element of \fCv\fP or when \fCi\fP is undefined\&.
.RE
.PP
Behaves like a case statement for selecting values from a list of \fIordered options\fP\&. The default value is: \fC\fBlast(v)\fP\fC\&.\fP\fP
.PP
\fC\fC \fBExample\fP 
.PP
.nf
ov = [ "value1", "value2", "default" ];

ciselect( ov );     // "default"
ciselect( ov, 4 );  // "default"
ciselect( ov, 0 );  // "value1"

.fi
.PP
 \fP\fP
.SS "function cmvselect (v, mv)"

.PP
Case-like select a value from a vector of identified options by match-value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A two dimensional vector of one or more identified values [[identifier, value], \&.\&.\&.]\&. 
.br
\fImv\fP <value> Element selection match value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<value> The value from the vector of identified elements with an identifier matching \fCmv\fP\&. Returns the default value when \fCmv\fP does not match any of the element identifiers of \fCv\fP or when \fCmv\fP is undefined\&.
.RE
.PP
Behaves like a case statement for selecting values from a list of \fIidentified options\fP\&. The default value is: \fCsecond(last(v))\fC\&.\fP\fP
.PP
\fC\fC \fBExample\fP 
.PP
.nf
ov = [ [0,"value0"], ["a","value1"], ["b","value2"], ["c","default"] ];

cmvselect( ov );      // "default"
cmvselect( ov, "x" ); // "default"
cmvselect( ov, 0 );   // "value0"
cmvselect( ov, "b" ); // "value2"

.fi
.PP
 \fP\fP
.SS "function consts (l, v)"

.PP
Create a vector of constant elements\&. 
.PP
\fBParameters:\fP
.RS 4
\fIl\fP <integer> The vector length\&. 
.br
\fIv\fP <value> The element value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> With \fCl\fP copies of the element value \fCv\fP\&. Returns \fBempty_v\fP when \fCl\fP is not a number or if \fC(l < 1)\fP\&.
.RE
.PP
\fBNote:\fP
.RS 4
When \fCv\fP is not specified, each element is assigned the value of its index position\&. 
.RE
.PP

.SS "function defined_or (v, d)"

.PP
Return a defined or default value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> A value\&. 
.br
\fId\fP <value> A default value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<value> \fCv\fP when it is defined or \fCd\fP otherwise\&. 
.RE
.PP

.SS "function delete (v, i, mv, mc = \fC0\fP)"

.PP
Delete elements from an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> An iterable value\&. 
.br
\fIi\fP <range|vector|integer> Deletion Indexes\&. 
.br
\fImv\fP <vector|string|value> Match value candidates (a vector of values, a string of characters, or a single value)\&. 
.br
\fImc\fP <integer> A match count\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> \fCv\fP with all specified element removed\&. Returns \fBundef\fP when \fCi\fP does not map to an element of \fCv\fP\&. Returns \fBundef\fP when \fCv\fP is not defined or is not iterable\&.
.RE
.PP
\fBNote:\fP
.RS 4
The elements to delete can be specified by an index position, a vector of index positions, an index range, an element match value, or a vector of element match values\&. 
.PP
When \fCmv\fP is a vector of match values, all matching values from \fCmv\fP that exists in \fCv\fP are candidates for deletion\&. For each matching candidate, \fCmc\fP indicates the quantity to remove\&. If \fC(mc == 0)\fP all candidates are removed\&. 
.PP
When more than one deletion criteria is specified, the order of precedence is: \fCmv\fP, \fCi\fP\&. 
.RE
.PP

.SS "function edefined_or (v, i, d)"

.PP
Return a defined vector element or default value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector\&. 
.br
\fIi\fP <integer> An element index\&. 
.br
\fId\fP <value> A default value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<value> \fCv[i]\fP when it is defined or \fCd\fP otherwise\&. 
.RE
.PP

.SS "function eselect (v, f = \fCtrue\fP, l = \fCfalse\fP, i)"

.PP
Select an element from each iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector of iterable values\&. 
.br
\fIf\fP <boolean> Select the first element\&. 
.br
\fIl\fP <boolean> Select the last element\&. 
.br
\fIi\fP <integer> Select a numeric element index position\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> Containing the selected element of each iterable value of \fCv\fP\&. Returns \fBempty_v\fP when \fCv\fP is empty\&. Returns \fBundef\fP when \fCv\fP is not defined or is not iterable\&.
.RE
.PP
\fBNote:\fP
.RS 4
When more than one selection criteria is specified, the order of precedence is: \fCi\fP, \fCl\fP, \fCf\fP\&. 
.RE
.PP

.SS "function first (v)"

.PP
Return the first element of an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> An iterable value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<value> The first element of \fCv\fP\&. Returns \fBundef\fP when \fCv\fP is not defined, is not iterable, or is empty\&. 
.RE
.PP

.SS "function head (v)"

.PP
Return a vector containing the first element of an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> An iterable value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> Containing the first element of \fCv\fP\&. Returns \fBundef\fP when \fCv\fP is not defined, is not iterable, or is empty\&. 
.RE
.PP

.SS "function insert (nv, v, i = \fC0\fP, mv, mi = \fC0\fP)"

.PP
Insert a new value into an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fInv\fP <value> A new value to insert\&. 
.br
\fIv\fP <value> An iterable value\&. 
.br
\fIi\fP <integer> An index insert position\&. 
.br
\fImv\fP <vector|string|value> Match value candidates (a vector of values, a string of characters, or a single value)\&. 
.br
\fImi\fP <integer> A match index\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> With \fCnv\fP inserted into \fCv\fP at the specified position\&. Returns \fBundef\fP when no value of \fCmv\fP exists in \fCv\fP\&. Returns \fBundef\fP when \fC(mi + 1)\fP exceeds the match count of the first matching element of \fCmv\fP\&. Returns \fBundef\fP when \fCi\fP does not map to an element of \fCv\fP\&. Returns \fBundef\fP when \fCv\fP is not defined or is not iterable\&.
.RE
.PP
\fBNote:\fP
.RS 4
The insert position can be specified by an index, an element match value, or vector of potential match values\&. 
.PP
When \fCmv\fP is a vector of potential match values, the first matching value from \fCmv\fP that exists in \fCv\fP is selected\&. 
.PP
When the selected matching value repeats in \fCv\fP, \fCmi\fP indicates which match is use as the insert position\&. 
.PP
When more than one insert position criteria is specified, the order of precedence is: \fCmv\fP, \fCi\fP\&. 
.RE
.PP

.SS "function last (v)"

.PP
Return the last element of an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> An iterable value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<value> The last element of \fCv\fP\&. Returns \fBundef\fP when \fCv\fP is not defined, is not iterable, or is empty\&. 
.RE
.PP

.SS "function pmerge (v, j = \fCtrue\fP)"

.PP
Parallel-merge vectors of iterable values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector of iterable values\&. 
.br
\fIj\fP <boolean> Join each merge as a vector\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> Containing the parallel-wise element concatenation of each iterable value in \fCv\fP\&. Returns \fBempty_v\fP when any element value in \fCv\fP is empty\&. Returns \fBundef\fP when \fCv\fP is not defined or when any element value in \fCv\fP is not iterable\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
v1=["a", "b", "c", "d"];
v2=[1, 2, 3];

echo( pmerge( [v1, v2], true ) );
echo( pmerge( [v1, v2], false ) );

.fi
.PP
.PP
\fBResult\fP 
.PP
.nf
ECHO: [["a", 1], ["b", 2], ["c", 3]]
ECHO: ["a", 1, "b", 2, "c", 3]

.fi
.PP
.PP
\fBNote:\fP
.RS 4
The resulting vector length will be limited by the iterable value with the shortest length\&. 
.PP
A string, although iterable, is treated as a merged unit\&. 
.RE
.PP

.SS "function qsort (v, r = \fCfalse\fP)"

.PP
Sort the numeric or string elements of a vector using quick sort\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector of values\&. 
.br
\fIr\fP <boolean> Reverse sort order\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> With elements sorted in ascending order\&. Returns \fBundef\fP when \fCv\fP is not all strings or all numbers\&. Returns \fBundef\fP when \fCv\fP is not defined or is not a vector\&.
.RE
.PP
\fBWarning:\fP
.RS 4
This implementation relies on the comparison operators '<' and '>' which expect the operands to be either two scalar numbers or two strings\&. Therefore, this function returns \fBundef\fP for vectors containing anything other than all scalar numbers or all strings\&.
.RE
.PP
See \fCWikipedia\fP for more information\&. 
.SS "function qsort2 (v, d = \fC0\fP, r = \fCfalse\fP, s = \fCtrue\fP)"

.PP
Hierarchically sort all elements of a vector using quick sort\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector of values\&. 
.br
\fId\fP <integer> Recursive sort depth\&. 
.br
\fIr\fP <boolean> Reverse sort order\&. 
.br
\fIs\fP <boolean> Order ranges by their numerical sum\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> With all elements sorted in ascending order\&. Returns \fBundef\fP when \fCv\fP is not defined or is not a vector\&.
.RE
.PP
Elements are sorted using the \fBcompare\fP function\&. See its documentation for a description of the parameter \fCs\fP\&. To recursively sort all elements, set \fCd\fP greater than, or equal to, the maximum level of hierarchy in \fCv\fP\&.
.PP
See \fCWikipedia\fP for more information\&. 
.SS "function reverse (v)"

.PP
Reverse the elements of an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> An iterable value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> Containing the elements of \fCv\fP in reversed order\&. Returns \fBempty_v\fP when \fCv\fP is empty\&. Returns \fBundef\fP when \fCv\fP is not defined or is not iterable\&. 
.RE
.PP

.SS "function rselect (v, i)"

.PP
Select a range of elements from an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> An iterable value\&. 
.br
\fIi\fP <range|vector|integer> Index selection\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> Containing the vector element indexes selected in \fCi\fP\&. Returns \fBundef\fP when \fCi\fP does not map to an element of \fCv\fP\&. Returns \fBempty_v\fP when \fCv\fP is empty\&. Returns \fBundef\fP when \fCv\fP is not defined or is not iterable\&. 
.RE
.PP

.SS "function second (v)"

.PP
Return the second element of an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> An iterable value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<value> The second element of \fCv\fP\&. Returns \fBundef\fP when \fCv\fP is not defined, is not iterable, or is empty\&. 
.RE
.PP

.SS "function smerge (v, r = \fCfalse\fP)"

.PP
Serial-merge vectors of iterable values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector of iterable values\&. 
.br
\fIr\fP <boolean> Recursively merge iterable elements\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> Containing the serial-wise element concatenation of each element in \fCv\fP\&. Returns \fBempty_v\fP when \fCv\fP is empty\&. Returns \fBundef\fP when \fCv\fP is not defined\&.
.RE
.PP
\fBNote:\fP
.RS 4
A string, although iterable, is treated as a merged unit\&. 
.RE
.PP

.SS "function strip (v, mv = \fC\fBempty_v\fP\fP)"

.PP
Strip all matching values from an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector of values\&. 
.br
\fImv\fP <value> A match value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> \fCv\fP with all elements equal to \fCmv\fP removed\&. Returns \fBundef\fP when \fCv\fP is not defined or is not iterable\&. 
.RE
.PP

.SS "function sum (v, i1, i2)"

.PP
Compute the sum of a vector of numbers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <range|vector> A vector of numerical values\&. 
.br
\fIi1\fP <integer> The element index at which to begin summation (first when not specified)\&. 
.br
\fIi2\fP <integer> The element index at which to end summation (last when not specified)\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<decimal> The summation of elements over the index range\&. Returns \fBv\fP when it is a scalar number\&. Returns 0 when \fCv\fP is empty\&. Returns \fBundef\fP when \fCv\fP is not defined or is not iterable and not a number\&. 
.RE
.PP

.SS "function tail (v)"

.PP
Return a vector containing all but the first element of an iterable value\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> An iterable value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> Containing all but the first element of \fCv\fP\&. Returns \fBempty_v\fP when \fCv\fP contains a single element\&. Returns \fBundef\fP when \fCv\fP is not defined, is not iterable, or is empty\&. 
.RE
.PP

.SS "function vstr (v)"

.PP
Convert all vector elements to strings and concatenate\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector of values\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<string> Constructed by converting each element of the vector to a string and concatenating together\&. Returns \fBundef\fP when \fCv\fP is not defined\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
v1=["a", "b", "c", "d"];
v2=[1, 2, 3];

echo( vstr(concat(v1, v2)) );

.fi
.PP
.PP
\fBResult\fP 
.PP
.nf
ECHO: "abcd123"

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
