.TH "tools" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools \- Tools
.PP
Design tools and techniques\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAlignment\fP"
.br
.RI "\fIShape alignment tools\&. \fP"
.ti -1c
.RI "\fBEdge\fP"
.br
.RI "\fIShape edge finishing tools\&. \fP"
.ti -1c
.RI "\fBExtrude\fP"
.br
.RI "\fIShape extrusion tools\&. \fP"
.ti -1c
.RI "\fBPolytope\fP"
.br
.RI "\fIPolygon and polyhedron tools\&. \fP"
.ti -1c
.RI "\fBRepeat\fP"
.br
.RI "\fIShape repetition and distribution tools\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtools_align\&.scad\fP"
.br
.RI "\fIShape alignment tools\&. \fP"
.ti -1c
.RI "file \fBtools_edge\&.scad\fP"
.br
.RI "\fIShape edge finishing tools\&. \fP"
.ti -1c
.RI "file \fBtools_polytope\&.scad\fP"
.br
.RI "\fIPolygon and polyhedron tools\&. \fP"
.ti -1c
.RI "file \fBtools_utility\&.scad\fP"
.br
.RI "\fIShape transformation utility tools\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Design tools and techniques\&. 

 
.PP
  
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
