.TH "tv_prim_test" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tv_prim_test \- Variable Tests 

.PD 0

.IP "\(bu" 2
\fBValidation Script (group1)\fP 
.IP "\(bu" 2
\fBValidation Results (group1)\fP 
.IP "\(bu" 2
\fBValidation Script (group2)\fP 
.IP "\(bu" 2
\fBValidation Results (group2)\fP 
.PP

