.TH "tv_math_bitwise_r" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tv_math_bitwise_r \- Validation Results 

.PP
.nf
1 ECHO: "OpenSCAD Version [2016, 12, 21]"
2 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_is_equal_0(undef, undef)=false'"
3 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_is_equal_0([], [])=false'"
4 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_is_equal_0(254, 0)=true'"
5 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_is_equal_0(254, 1)=false'"
6 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_is_equal_0(255, 0)=false'"
7 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_is_equal_0(0, 255)=true'"
8 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_is_equal_0(126, 63)=true'"
9 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_is_equal_0(25, 10)=true'"
10 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_is_equal_0(1024, 512)=true'"
11 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_is_equal_0(4253, 315)=true'"
12 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_is_equal_0(835, 769)=true'"
13 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_is_equal_0(856, 625)=true'"
14 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_is_equal_1(undef, undef)=false'"
15 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_is_equal_1([], [])=false'"
16 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_is_equal_1(254, 0)=false'"
17 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_is_equal_1(254, 1)=true'"
18 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_is_equal_1(255, 0)=true'"
19 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_is_equal_1(0, 255)=false'"
20 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_is_equal_1(126, 63)=false'"
21 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_is_equal_1(25, 10)=false'"
22 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_is_equal_1(1024, 512)=false'"
23 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_is_equal_1(4253, 315)=false'"
24 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_is_equal_1(835, 769)=false'"
25 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_is_equal_1(856, 625)=false'"
26 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_i2v(undef)=undef'"
27 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_i2v([])=undef'"
28 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_i2v(254)=[1, 1, 1, 1, 1, 1, 1, 0]'"
29 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_i2v(254)=[1, 1, 1, 1, 1, 1, 1, 0]'"
30 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_i2v(255)=[1, 1, 1, 1, 1, 1, 1, 1]'"
31 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_i2v(0)=[0]'"
32 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_i2v(126)=[1, 1, 1, 1, 1, 1, 0]'"
33 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_i2v(25)=[1, 1, 0, 0, 1]'"
34 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_i2v(1024)=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]'"
35 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_i2v(4253)=[1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1]'"
36 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_i2v(835)=[1, 1, 0, 1, 0, 0, 0, 0, 1, 1]'"
37 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_i2v(856)=[1, 1, 0, 1, 0, 1, 1, 0, 0, 0]'"
38 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_i2v_v2i(undef)=undef'"
39 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_i2v_v2i([])=undef'"
40 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_i2v_v2i(254)=254'"
41 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_i2v_v2i(254)=254'"
42 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_i2v_v2i(255)=255'"
43 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_i2v_v2i(0)=0'"
44 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_i2v_v2i(126)=126'"
45 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_i2v_v2i(25)=25'"
46 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_i2v_v2i(1024)=1024'"
47 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_i2v_v2i(4253)=4253'"
48 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_i2v_v2i(835)=835'"
49 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_i2v_v2i(856)=856'"
50 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_i2s(undef)=undef'"
51 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_i2s([])=undef'"
52 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_i2s(254)=11111110'"
53 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_i2s(254)=11111110'"
54 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_i2s(255)=11111111'"
55 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_i2s(0)=0'"
56 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_i2s(126)=1111110'"
57 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_i2s(25)=11001'"
58 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_i2s(1024)=10000000000'"
59 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_i2s(4253)=1000010011101'"
60 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_i2s(835)=1101000011'"
61 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_i2s(856)=1101011000'"
62 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_i2s_s2i(undef)=undef'"
63 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_i2s_s2i([])=undef'"
64 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_i2s_s2i(254)=254'"
65 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_i2s_s2i(254)=254'"
66 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_i2s_s2i(255)=255'"
67 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_i2s_s2i(0)=0'"
68 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_i2s_s2i(126)=126'"
69 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_i2s_s2i(25)=25'"
70 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_i2s_s2i(1024)=1024'"
71 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_i2s_s2i(4253)=4253'"
72 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_i2s_s2i(835)=835'"
73 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_i2s_s2i(856)=856'"
74 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_and(undef, undef)=undef'"
75 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_and([], [])=undef'"
76 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_and(254, 0)=0'"
77 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_and(254, 1)=0'"
78 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_and(255, 0)=0'"
79 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_and(0, 255)=0'"
80 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_and(126, 63)=62'"
81 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_and(25, 10)=8'"
82 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_and(1024, 512)=0'"
83 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_and(4253, 315)=25'"
84 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_and(835, 769)=769'"
85 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_and(856, 625)=592'"
86 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_or(undef, undef)=undef'"
87 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_or([], [])=undef'"
88 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_or(254, 0)=254'"
89 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_or(254, 1)=255'"
90 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_or(255, 0)=255'"
91 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_or(0, 255)=255'"
92 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_or(126, 63)=127'"
93 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_or(25, 10)=27'"
94 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_or(1024, 512)=1536'"
95 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_or(4253, 315)=4543'"
96 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_or(835, 769)=835'"
97 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_or(856, 625)=889'"
98 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_xor(undef, undef)=undef'"
99 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_xor([], [])=undef'"
100 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_xor(254, 0)=254'"
101 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_xor(254, 1)=255'"
102 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_xor(255, 0)=255'"
103 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_xor(0, 255)=255'"
104 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_xor(126, 63)=65'"
105 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_xor(25, 10)=19'"
106 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_xor(1024, 512)=1536'"
107 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_xor(4253, 315)=4518'"
108 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_xor(835, 769)=66'"
109 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_xor(856, 625)=297'"
110 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_not(undef)=undef'"
111 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_not([])=undef'"
112 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_not(254)=1'"
113 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_not(254)=1'"
114 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_not(255)=0'"
115 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_not(0)=1'"
116 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_not(126)=1'"
117 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_not(25)=6'"
118 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_not(1024)=1023'"
119 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_not(4253)=3938'"
120 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_not(835)=188'"
121 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_not(856)=167'"
122 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_lsh(undef)=undef'"
123 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_lsh([])=undef'"
124 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_lsh(254)=508'"
125 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_lsh(254)=508'"
126 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_lsh(255)=510'"
127 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_lsh(0)=0'"
128 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_lsh(126)=252'"
129 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_lsh(25)=50'"
130 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_lsh(1024)=2048'"
131 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_lsh(4253)=8506'"
132 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_lsh(835)=1670'"
133 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_lsh(856)=1712'"
134 ECHO: "[ INFO ] run(): test(); t01 passed: 'bitwise_rsh(undef)=undef'"
135 ECHO: "[ INFO ] run(): test(); t02 passed: 'bitwise_rsh([])=undef'"
136 ECHO: "[ INFO ] run(): test(); t03 passed: 'bitwise_rsh(254)=127'"
137 ECHO: "[ INFO ] run(): test(); t04 passed: 'bitwise_rsh(254)=127'"
138 ECHO: "[ INFO ] run(): test(); t05 passed: 'bitwise_rsh(255)=127'"
139 ECHO: "[ INFO ] run(): test(); t06 passed: 'bitwise_rsh(0)=0'"
140 ECHO: "[ INFO ] run(): test(); t07 passed: 'bitwise_rsh(126)=63'"
141 ECHO: "[ INFO ] run(): test(); t08 passed: 'bitwise_rsh(25)=12'"
142 ECHO: "[ INFO ] run(): test(); t09 passed: 'bitwise_rsh(1024)=512'"
143 ECHO: "[ INFO ] run(): test(); t10 passed: 'bitwise_rsh(4253)=2126'"
144 ECHO: "[ INFO ] run(): test(); t11 passed: 'bitwise_rsh(835)=417'"
145 ECHO: "[ INFO ] run(): test(); t12 passed: 'bitwise_rsh(856)=428'"

.fi
.PP
 
