.TH "todo" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBglobalScope> Global \fBpyramid_q\fP (x, y, z, center=false)\fP" 1c
Support vertex rounding radius\&.  
.IP "\fBFile \fBresolution\&.scad\fP \fP" 1c
Review model for accuracy\&. 
.IP "\fBFile \fBshapes3d\&.scad\fP \fP" 1c
Complete rounded cylinder\&. 
.IP "\fBglobalScope> Global \fBtetrahedron\fP (r, center=false)\fP" 1c
Support vertex rounding radius\&. 
.PP
Identify cause of missing face\&. Using hull() as a workaround\&.  
.IP "\fBglobalScope> Global \fBtriangle_ppp\fP (v1, v2, v3, vr, v1r, v2r, v3r, centroid=false, incenter=false)\fP" 1c
Replace the hull() operation with calculated tangential intersection of the rounded vertexes\&. 
.PP
Remove the all or nothing requirement for vertex rounding\&. 
.PP

