.TH "tv_datatypes_operate_iterable_r" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tv_datatypes_operate_iterable_r \- Results 

.PP
.nf
1 ECHO: "OpenSCAD Version [2017, 2, 19]"
2 ECHO: "[ INFO ] run_test(); t01 passed: 'edefined_or_DE3(undef)=default'"
3 ECHO: "[ INFO ] run_test(); t02 passed: 'edefined_or_DE3([])=default'"
4 ECHO: "[ INFO ] run_test(); t03 passed: 'edefined_or_DE3([0 : 0\&.5 : 9])=default'"
5 ECHO: "[ INFO ] run_test(); t04 passed: 'edefined_or_DE3(A string)=t'"
6 ECHO: "[ INFO ] run_test(); t05 passed: 'edefined_or_DE3(["orange", "apple", "grape", "banana"])=banana'"
7 ECHO: "[ INFO ] run_test(); t06 passed: 'edefined_or_DE3(["b", "a", "n", "a", "n", "a", "s"])=a'"
8 ECHO: "[ INFO ] run_test(); t07 passed: 'edefined_or_DE3([undef])=default'"
9 ECHO: "[ INFO ] run_test(); t08 passed: 'edefined_or_DE3([[1, 2], [2, 3]])=default'"
10 ECHO: "[ INFO ] run_test(); t09 passed: 'edefined_or_DE3(["ab", [1, 2], [2, 3], [4, 5]])=[4, 5]'"
11 ECHO: "[ INFO ] run_test(); t10 passed: 'edefined_or_DE3([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=["a", "b", "c"]'"
12 ECHO: "[ INFO ] run_test(); t11 passed: 'edefined_or_DE3([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=3'"
13 ECHO: "[ INFO ] run_test(); t01 passed: 'find_12(undef)=[]'"
14 ECHO: "[ INFO ] run_test(); t02 passed: 'find_12([])=[]'"
15 ECHO: "[ INFO ] run_test(); t03 passed: 'find_12([0 : 0\&.5 : 9])=[]'"
16 ECHO: "[ INFO ] run_test(); t04 passed: 'find_12(A string)=[]'"
17 ECHO: "[ INFO ] run_test(); t05 passed: 'find_12(["orange", "apple", "grape", "banana"])=[]'"
18 ECHO: "[ INFO ] run_test(); t06 passed: 'find_12(["b", "a", "n", "a", "n", "a", "s"])=[]'"
19 ECHO: "[ INFO ] run_test(); t07 passed: 'find_12([undef])=[]'"
20 ECHO: "[ INFO ] run_test(); t08 passed: 'find_12([[1, 2], [2, 3]])=[0]'"
21 ECHO: "[ INFO ] run_test(); t09 passed: 'find_12(["ab", [1, 2], [2, 3], [4, 5]])=[1]'"
22 ECHO: "[ INFO ] run_test(); t10 passed: 'find_12([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[]'"
23 ECHO: "[ INFO ] run_test(); t11 passed: 'find_12([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[]'"
24 ECHO: "[ INFO ] run_test(); t01 passed: 'count_S1(undef)=0'"
25 ECHO: "[ INFO ] run_test(); t02 passed: 'count_S1([])=0'"
26 ECHO: "[ INFO ] run_test(); t03 passed: 'count_S1([0 : 0\&.5 : 9])=0'"
27 ECHO: "[ INFO ] run_test(); t04 passed: 'count_S1(A string)=0'"
28 ECHO: "[ INFO ] run_test(); t05 passed: 'count_S1(["orange", "apple", "grape", "banana"])=0'"
29 ECHO: "[ INFO ] run_test(); t06 passed: 'count_S1(["b", "a", "n", "a", "n", "a", "s"])=0'"
30 ECHO: "[ INFO ] run_test(); t07 passed: 'count_S1([undef])=0'"
31 ECHO: "[ INFO ] run_test(); t08 passed: 'count_S1([[1, 2], [2, 3]])=1'"
32 ECHO: "[ INFO ] run_test(); t09 passed: 'count_S1(["ab", [1, 2], [2, 3], [4, 5]])=1'"
33 ECHO: "[ INFO ] run_test(); t10 passed: 'count_S1([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=1'"
34 ECHO: "[ INFO ] run_test(); t11 passed: 'count_S1([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=1'"
35 ECHO: "[ INFO ] run_test(); t01 passed: 'exists_S1(undef)=false'"
36 ECHO: "[ INFO ] run_test(); t02 passed: 'exists_S1([])=false'"
37 ECHO: "[ INFO ] run_test(); t03 passed: 'exists_S1([0 : 0\&.5 : 9])=false'"
38 ECHO: "[ INFO ] run_test(); t04 passed: 'exists_S1(A string)=false'"
39 ECHO: "[ INFO ] run_test(); t05 passed: 'exists_S1(["orange", "apple", "grape", "banana"])=false'"
40 ECHO: "[ INFO ] run_test(); t06 passed: 'exists_S1(["b", "a", "n", "a", "n", "a", "s"])=false'"
41 ECHO: "[ INFO ] run_test(); t07 passed: 'exists_S1([undef])=false'"
42 ECHO: "[ INFO ] run_test(); t08 passed: 'exists_S1([[1, 2], [2, 3]])=true'"
43 ECHO: "[ INFO ] run_test(); t09 passed: 'exists_S1(["ab", [1, 2], [2, 3], [4, 5]])=true'"
44 ECHO: "[ INFO ] run_test(); t10 passed: 'exists_S1([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=true'"
45 ECHO: "[ INFO ] run_test(); t11 passed: 'exists_S1([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=true'"
46 ECHO: "[ INFO ] run_test(); t01 passed: 'first(undef)=undef'"
47 ECHO: "[ INFO ] run_test(); t02 passed: 'first([])=undef'"
48 ECHO: "[ INFO ] run_test(); t03 passed: 'first([0 : 0\&.5 : 9])=0'"
49 ECHO: "[ INFO ] run_test(); t04 passed: 'first(A string)=A'"
50 ECHO: "[ INFO ] run_test(); t05 passed: 'first(["orange", "apple", "grape", "banana"])=orange'"
51 ECHO: "[ INFO ] run_test(); t06 passed: 'first(["b", "a", "n", "a", "n", "a", "s"])=b'"
52 ECHO: "[ INFO ] run_test(); t07 passed: 'first([undef])=undef'"
53 ECHO: "[ INFO ] run_test(); t08 passed: 'first([[1, 2], [2, 3]])=[1, 2]'"
54 ECHO: "[ INFO ] run_test(); t09 passed: 'first(["ab", [1, 2], [2, 3], [4, 5]])=ab'"
55 ECHO: "[ INFO ] run_test(); t10 passed: 'first([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[1, 2, 3]'"
56 ECHO: "[ INFO ] run_test(); t11 passed: 'first([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=0'"
57 ECHO: "[ INFO ] run_test(); t01 passed: 'second(undef)=undef'"
58 ECHO: "[ INFO ] run_test(); t02 passed: 'second([])=undef'"
59 ECHO: "[ INFO ] run_test(); t03 passed: 'second([0 : 0\&.5 : 9])=0\&.5'"
60 ECHO: "[ INFO ] run_test(); t04 passed: 'second(A string)= '"
61 ECHO: "[ INFO ] run_test(); t05 passed: 'second(["orange", "apple", "grape", "banana"])=apple'"
62 ECHO: "[ INFO ] run_test(); t06 passed: 'second(["b", "a", "n", "a", "n", "a", "s"])=a'"
63 ECHO: "[ INFO ] run_test(); t07 passed: 'second([undef])=undef'"
64 ECHO: "[ INFO ] run_test(); t08 passed: 'second([[1, 2], [2, 3]])=[2, 3]'"
65 ECHO: "[ INFO ] run_test(); t09 passed: 'second(["ab", [1, 2], [2, 3], [4, 5]])=[1, 2]'"
66 ECHO: "[ INFO ] run_test(); t10 passed: 'second([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[4, 5, 6]'"
67 ECHO: "[ INFO ] run_test(); t11 passed: 'second([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=1'"
68 ECHO: "[ INFO ] run_test(); t01 passed: 'third(undef)=undef'"
69 ECHO: "[ INFO ] run_test(); t02 passed: 'third([])=undef'"
70 ECHO: "[ INFO ] run_test(); t03 passed: 'third([0 : 0\&.5 : 9])=9'"
71 ECHO: "[ INFO ] run_test(); t04 passed: 'third(A string)=s'"
72 ECHO: "[ INFO ] run_test(); t05 passed: 'third(["orange", "apple", "grape", "banana"])=grape'"
73 ECHO: "[ INFO ] run_test(); t06 passed: 'third(["b", "a", "n", "a", "n", "a", "s"])=n'"
74 ECHO: "[ INFO ] run_test(); t07 passed: 'third([undef])=undef'"
75 ECHO: "[ INFO ] run_test(); t08 passed: 'third([[1, 2], [2, 3]])=undef'"
76 ECHO: "[ INFO ] run_test(); t09 passed: 'third(["ab", [1, 2], [2, 3], [4, 5]])=[2, 3]'"
77 ECHO: "[ INFO ] run_test(); t10 passed: 'third([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[7, 8, 9]'"
78 ECHO: "[ INFO ] run_test(); t11 passed: 'third([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=2'"
79 ECHO: "[ INFO ] run_test(); t01 passed: 'last(undef)=undef'"
80 ECHO: "[ INFO ] run_test(); t02 passed: 'last([])=undef'"
81 ECHO: "[ INFO ] run_test(); t03 passed: 'last([0 : 0\&.5 : 9])=undef'"
82 ECHO: "[ INFO ] run_test(); t04 passed: 'last(A string)=g'"
83 ECHO: "[ INFO ] run_test(); t05 passed: 'last(["orange", "apple", "grape", "banana"])=banana'"
84 ECHO: "[ INFO ] run_test(); t06 passed: 'last(["b", "a", "n", "a", "n", "a", "s"])=s'"
85 ECHO: "[ INFO ] run_test(); t07 passed: 'last([undef])=undef'"
86 ECHO: "[ INFO ] run_test(); t08 passed: 'last([[1, 2], [2, 3]])=[2, 3]'"
87 ECHO: "[ INFO ] run_test(); t09 passed: 'last(["ab", [1, 2], [2, 3], [4, 5]])=[4, 5]'"
88 ECHO: "[ INFO ] run_test(); t10 passed: 'last([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=["a", "b", "c"]'"
89 ECHO: "[ INFO ] run_test(); t11 passed: 'last([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=15'"
90 ECHO: "[ INFO ] run_test(); t01 passed: 'nfirst_1(undef)=undef'"
91 ECHO: "[ INFO ] run_test(); t02 passed: 'nfirst_1([])=undef'"
92 ECHO: "[ INFO ] run_test(); t03 passed: 'nfirst_1([0 : 0\&.5 : 9])=undef'"
93 ECHO: "[ INFO ] run_test(); t04 passed: 'nfirst_1(A string)=["A"]'"
94 ECHO: "[ INFO ] run_test(); t05 passed: 'nfirst_1(["orange", "apple", "grape", "banana"])=["orange"]'"
95 ECHO: "[ INFO ] run_test(); t06 passed: 'nfirst_1(["b", "a", "n", "a", "n", "a", "s"])=["b"]'"
96 ECHO: "[ INFO ] run_test(); t07 passed: 'nfirst_1([undef])=[undef]'"
97 ECHO: "[ INFO ] run_test(); t08 passed: 'nfirst_1([[1, 2], [2, 3]])=[[1, 2]]'"
98 ECHO: "[ INFO ] run_test(); t09 passed: 'nfirst_1(["ab", [1, 2], [2, 3], [4, 5]])=["ab"]'"
99 ECHO: "[ INFO ] run_test(); t10 passed: 'nfirst_1([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[1, 2, 3]]'"
100 ECHO: "[ INFO ] run_test(); t11 passed: 'nfirst_1([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[0]'"
101 ECHO: "[ INFO ] run_test(); t01 passed: 'nlast_1(undef)=undef'"
102 ECHO: "[ INFO ] run_test(); t02 passed: 'nlast_1([])=undef'"
103 ECHO: "[ INFO ] run_test(); t03 passed: 'nlast_1([0 : 0\&.5 : 9])=undef'"
104 ECHO: "[ INFO ] run_test(); t04 passed: 'nlast_1(A string)=["g"]'"
105 ECHO: "[ INFO ] run_test(); t05 passed: 'nlast_1(["orange", "apple", "grape", "banana"])=["banana"]'"
106 ECHO: "[ INFO ] run_test(); t06 passed: 'nlast_1(["b", "a", "n", "a", "n", "a", "s"])=["s"]'"
107 ECHO: "[ INFO ] run_test(); t07 passed: 'nlast_1([undef])=[undef]'"
108 ECHO: "[ INFO ] run_test(); t08 passed: 'nlast_1([[1, 2], [2, 3]])=[[2, 3]]'"
109 ECHO: "[ INFO ] run_test(); t09 passed: 'nlast_1(["ab", [1, 2], [2, 3], [4, 5]])=[[4, 5]]'"
110 ECHO: "[ INFO ] run_test(); t10 passed: 'nlast_1([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[["a", "b", "c"]]'"
111 ECHO: "[ INFO ] run_test(); t11 passed: 'nlast_1([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[15]'"
112 ECHO: "[ INFO ] run_test(); t01 passed: 'nhead_1(undef)=undef'"
113 ECHO: "[ INFO ] run_test(); t02 passed: 'nhead_1([])=undef'"
114 ECHO: "[ INFO ] run_test(); t03 passed: 'nhead_1([0 : 0\&.5 : 9])=undef'"
115 ECHO: "[ INFO ] run_test(); t04 passed: 'nhead_1(A string)=["A", " ", "s", "t", "r", "i", "n"]'"
116 ECHO: "[ INFO ] run_test(); t05 passed: 'nhead_1(["orange", "apple", "grape", "banana"])=["orange", "apple", "grape"]'"
117 ECHO: "[ INFO ] run_test(); t06 passed: 'nhead_1(["b", "a", "n", "a", "n", "a", "s"])=["b", "a", "n", "a", "n", "a"]'"
118 ECHO: "[ INFO ] run_test(); t07 passed: 'nhead_1([undef])=[]'"
119 ECHO: "[ INFO ] run_test(); t08 passed: 'nhead_1([[1, 2], [2, 3]])=[[1, 2]]'"
120 ECHO: "[ INFO ] run_test(); t09 passed: 'nhead_1(["ab", [1, 2], [2, 3], [4, 5]])=["ab", [1, 2], [2, 3]]'"
121 ECHO: "[ INFO ] run_test(); t10 passed: 'nhead_1([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]'"
122 ECHO: "[ INFO ] run_test(); t11 passed: 'nhead_1([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]'"
123 ECHO: "[ INFO ] run_test(); t01 passed: 'ntail_1(undef)=undef'"
124 ECHO: "[ INFO ] run_test(); t02 passed: 'ntail_1([])=undef'"
125 ECHO: "[ INFO ] run_test(); t03 passed: 'ntail_1([0 : 0\&.5 : 9])=undef'"
126 ECHO: "[ INFO ] run_test(); t04 passed: 'ntail_1(A string)=[" ", "s", "t", "r", "i", "n", "g"]'"
127 ECHO: "[ INFO ] run_test(); t05 passed: 'ntail_1(["orange", "apple", "grape", "banana"])=["apple", "grape", "banana"]'"
128 ECHO: "[ INFO ] run_test(); t06 passed: 'ntail_1(["b", "a", "n", "a", "n", "a", "s"])=["a", "n", "a", "n", "a", "s"]'"
129 ECHO: "[ INFO ] run_test(); t07 passed: 'ntail_1([undef])=[]'"
130 ECHO: "[ INFO ] run_test(); t08 passed: 'ntail_1([[1, 2], [2, 3]])=[[2, 3]]'"
131 ECHO: "[ INFO ] run_test(); t09 passed: 'ntail_1(["ab", [1, 2], [2, 3], [4, 5]])=[[1, 2], [2, 3], [4, 5]]'"
132 ECHO: "[ INFO ] run_test(); t10 passed: 'ntail_1([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[4, 5, 6], [7, 8, 9], ["a", "b", "c"]]'"
133 ECHO: "[ INFO ] run_test(); t11 passed: 'ntail_1([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]'"
134 ECHO: "[ INFO ] run_test(); t01 passed: 'reverse(undef)=undef'"
135 ECHO: "[ INFO ] run_test(); t02 passed: 'reverse([])=[]'"
136 ECHO: "[ INFO ] run_test(); t03 passed: 'reverse([0 : 0\&.5 : 9])=undef'"
137 ECHO: "[ INFO ] run_test(); t04 passed: 'reverse(A string)=["g", "n", "i", "r", "t", "s", " ", "A"]'"
138 ECHO: "[ INFO ] run_test(); t05 passed: 'reverse(["orange", "apple", "grape", "banana"])=["banana", "grape", "apple", "orange"]'"
139 ECHO: "[ INFO ] run_test(); t06 passed: 'reverse(["b", "a", "n", "a", "n", "a", "s"])=["s", "a", "n", "a", "n", "a", "b"]'"
140 ECHO: "[ INFO ] run_test(); t07 passed: 'reverse([undef])=[undef]'"
141 ECHO: "[ INFO ] run_test(); t08 passed: 'reverse([[1, 2], [2, 3]])=[[2, 3], [1, 2]]'"
142 ECHO: "[ INFO ] run_test(); t09 passed: 'reverse(["ab", [1, 2], [2, 3], [4, 5]])=[[4, 5], [2, 3], [1, 2], "ab"]'"
143 ECHO: "[ INFO ] run_test(); t10 passed: 'reverse([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[["a", "b", "c"], [7, 8, 9], [4, 5, 6], [1, 2, 3]]'"
144 ECHO: "[ INFO ] run_test(); t11 passed: 'reverse([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]'"
145 ECHO: "[ INFO ] run_test(); t01 passed: 'rselect_02(undef)=undef'"
146 ECHO: "[ INFO ] run_test(); t02 passed: 'rselect_02([])=[]'"
147 ECHO: "[ INFO ] run_test(); t03 passed: 'rselect_02([0 : 0\&.5 : 9])=undef'"
148 ECHO: "[ INFO ] run_test(); t04 passed: 'rselect_02(A string)=["A", " ", "s"]'"
149 ECHO: "[ INFO ] run_test(); t05 passed: 'rselect_02(["orange", "apple", "grape", "banana"])=["orange", "apple", "grape"]'"
150 ECHO: "[ INFO ] run_test(); t06 passed: 'rselect_02(["b", "a", "n", "a", "n", "a", "s"])=["b", "a", "n"]'"
151 ECHO: "[ INFO ] run_test(); t07 passed: 'rselect_02([undef])=undef'"
152 ECHO: "[ INFO ] run_test(); t08 passed: 'rselect_02([[1, 2], [2, 3]])=undef'"
153 ECHO: "[ INFO ] run_test(); t09 passed: 'rselect_02(["ab", [1, 2], [2, 3], [4, 5]])=["ab", [1, 2], [2, 3]]'"
154 ECHO: "[ INFO ] run_test(); t10 passed: 'rselect_02([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]'"
155 ECHO: "[ INFO ] run_test(); t11 passed: 'rselect_02([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[0, 1, 2]'"
156 ECHO: "[ INFO ] run_test(); t01 passed: 'nssequence_31(undef)=[]'"
157 ECHO: "[ INFO ] run_test(); t02 passed: 'nssequence_31([])=[]'"
158 ECHO: "[ INFO ] run_test(); t03 passed: 'nssequence_31([0 : 0\&.5 : 9])=[]'"
159 ECHO: "[ INFO ] run_test(); t04 passed: 'nssequence_31(A string)=[["A", " ", "s"], [" ", "s", "t"], ["s", "t", "r"], ["t", "r", "i"], ["r", "i", "n"], ["i", "n", "g"]]'"
160 ECHO: "[ INFO ] run_test(); t05 passed: 'nssequence_31(["orange", "apple", "grape", "banana"])=[["orange", "apple", "grape"], ["apple", "grape", "banana"]]'"
161 ECHO: "[ INFO ] run_test(); t06 passed: 'nssequence_31(["b", "a", "n", "a", "n", "a", "s"])=[["b", "a", "n"], ["a", "n", "a"], ["n", "a", "n"], ["a", "n", "a"], ["n", "a", "s"]]'"
162 ECHO: "[ INFO ] run_test(); t07 passed: 'nssequence_31([undef])=[]'"
163 ECHO: "[ INFO ] run_test(); t08 passed: 'nssequence_31([[1, 2], [2, 3]])=[]'"
164 ECHO: "[ INFO ] run_test(); t09 passed: 'nssequence_31(["ab", [1, 2], [2, 3], [4, 5]])=[["ab", [1, 2], [2, 3]], [[1, 2], [2, 3], [4, 5]]]'"
165 ECHO: "[ INFO ] run_test(); t10 passed: 'nssequence_31([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[4, 5, 6], [7, 8, 9], ["a", "b", "c"]]]'"
166 ECHO: "[ INFO ] run_test(); t11 passed: 'nssequence_31([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9], [8, 9, 10], [9, 10, 11], [10, 11, 12], [11, 12, 13], [12, 13, 14], [13, 14, 15]]'"
167 ECHO: "[ INFO ] run_test(); t01 passed: 'eappend_T0(undef)=undef'"
168 ECHO: "[ INFO ] run_test(); t02 passed: 'eappend_T0([])=[[0]]'"
169 ECHO: "[ INFO ] run_test(); t03 passed: 'eappend_T0([0 : 0\&.5 : 9])=undef'"
170 ECHO: "[ INFO ] run_test(); t04 passed: 'eappend_T0(A string)=[["A", 0], [" ", 0], ["s", 0], ["t", 0], ["r", 0], ["i", 0], ["n", 0], ["g", 0]]'"
171 ECHO: "[ INFO ] run_test(); t05 passed: 'eappend_T0(["orange", "apple", "grape", "banana"])=[["orange", 0], ["apple", 0], ["grape", 0], ["banana", 0]]'"
172 ECHO: "[ INFO ] run_test(); t06 passed: 'eappend_T0(["b", "a", "n", "a", "n", "a", "s"])=[["b", 0], ["a", 0], ["n", 0], ["a", 0], ["n", 0], ["a", 0], ["s", 0]]'"
173 ECHO: "[ INFO ] run_test(); t07 passed: 'eappend_T0([undef])=[[undef, 0]]'"
174 ECHO: "[ INFO ] run_test(); t08 passed: 'eappend_T0([[1, 2], [2, 3]])=[[1, 2, 0], [2, 3, 0]]'"
175 ECHO: "[ INFO ] run_test(); t09 passed: 'eappend_T0(["ab", [1, 2], [2, 3], [4, 5]])=[["ab", 0], [1, 2, 0], [2, 3, 0], [4, 5, 0]]'"
176 ECHO: "[ INFO ] run_test(); t10 passed: 'eappend_T0([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[1, 2, 3, 0], [4, 5, 6, 0], [7, 8, 9, 0], ["a", "b", "c", 0]]'"
177 ECHO: "[ INFO ] run_test(); t11 passed: 'eappend_T0([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[[0, 0], [1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [6, 0], [7, 0], [8, 0], [9, 0], [10, 0], [11, 0], [12, 0], [13, 0], [14, 0], [15, 0]]'"
178 ECHO: "[ INFO ] run_test(); t01 passed: 'insert_T0(undef)=undef'"
179 ECHO: "[ INFO ] run_test(); t02 passed: 'insert_T0([])=undef'"
180 ECHO: "[ INFO ] run_test(); t03 passed: 'insert_T0([0 : 0\&.5 : 9])=undef'"
181 ECHO: "[ INFO ] run_test(); t04 passed: 'insert_T0(A string)=undef'"
182 ECHO: "[ INFO ] run_test(); t05 passed: 'insert_T0(["orange", "apple", "grape", "banana"])=["orange", 0, "apple", "grape", "banana"]'"
183 ECHO: "[ INFO ] run_test(); t06 passed: 'insert_T0(["b", "a", "n", "a", "n", "a", "s"])=["b", "a", "n", "a", "n", "a", 0, "s"]'"
184 ECHO: "[ INFO ] run_test(); t07 passed: 'insert_T0([undef])=undef'"
185 ECHO: "[ INFO ] run_test(); t08 passed: 'insert_T0([[1, 2], [2, 3]])=[[1, 2], 0, [2, 3]]'"
186 ECHO: "[ INFO ] run_test(); t09 passed: 'insert_T0(["ab", [1, 2], [2, 3], [4, 5]])=["ab", [1, 2], 0, [2, 3], [4, 5]]'"
187 ECHO: "[ INFO ] run_test(); t10 passed: 'insert_T0([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=undef'"
188 ECHO: "[ INFO ] run_test(); t11 passed: 'insert_T0([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[0, 1, 2, 3, 4, 0, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]'"
189 ECHO: "[ INFO ] run_test(); t01 passed: 'delete_T0(undef)=undef'"
190 ECHO: "[ INFO ] run_test(); t02 passed: 'delete_T0([])=[]'"
191 ECHO: "[ INFO ] run_test(); t03 passed: 'delete_T0([0 : 0\&.5 : 9])=undef'"
192 ECHO: "[ INFO ] run_test(); t04 passed: 'delete_T0(A string)=["A", " ", "s", "t", "r", "i", "n", "g"]'"
193 ECHO: "[ INFO ] run_test(); t05 passed: 'delete_T0(["orange", "apple", "grape", "banana"])=["orange", "grape", "banana"]'"
194 ECHO: "[ INFO ] run_test(); t06 passed: 'delete_T0(["b", "a", "n", "a", "n", "a", "s"])=["b", "a", "n", "a", "n", "a"]'"
195 ECHO: "[ INFO ] run_test(); t07 passed: 'delete_T0([undef])=[undef]'"
196 ECHO: "[ INFO ] run_test(); t08 passed: 'delete_T0([[1, 2], [2, 3]])=[[1, 2]]'"
197 ECHO: "[ INFO ] run_test(); t09 passed: 'delete_T0(["ab", [1, 2], [2, 3], [4, 5]])=["ab", [1, 2], [4, 5]]'"
198 ECHO: "[ INFO ] run_test(); t10 passed: 'delete_T0([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]]'"
199 ECHO: "[ INFO ] run_test(); t11 passed: 'delete_T0([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]'"
200 ECHO: "[ INFO ] run_test(); t01 passed: 'strip(undef)=undef'"
201 ECHO: "[ INFO ] run_test(); t02 passed: 'strip([])=[]'"
202 ECHO: "[ INFO ] run_test(); t03 passed: 'strip([0 : 0\&.5 : 9])=undef'"
203 ECHO: "[ INFO ] run_test(); t04 passed: 'strip(A string)=["A", " ", "s", "t", "r", "i", "n", "g"]'"
204 ECHO: "[ INFO ] run_test(); t05 passed: 'strip(["orange", "apple", "grape", "banana"])=["orange", "apple", "grape", "banana"]'"
205 ECHO: "[ INFO ] run_test(); t06 passed: 'strip(["b", "a", "n", "a", "n", "a", "s"])=["b", "a", "n", "a", "n", "a", "s"]'"
206 ECHO: "[ INFO ] run_test(); t07 passed: 'strip([undef])=[undef]'"
207 ECHO: "[ INFO ] run_test(); t08 passed: 'strip([[1, 2], [2, 3]])=[[1, 2], [2, 3]]'"
208 ECHO: "[ INFO ] run_test(); t09 passed: 'strip(["ab", [1, 2], [2, 3], [4, 5]])=["ab", [1, 2], [2, 3], [4, 5]]'"
209 ECHO: "[ INFO ] run_test(); t10 passed: 'strip([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]]'"
210 ECHO: "[ INFO ] run_test(); t11 passed: 'strip([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]'"
211 ECHO: "[ INFO ] run_test(); t01 passed: 'unique(undef)=undef'"
212 ECHO: "[ INFO ] run_test(); t02 passed: 'unique([])=[]'"
213 ECHO: "[ INFO ] run_test(); t03 passed: 'unique([0 : 0\&.5 : 9])=undef'"
214 ECHO: "[ INFO ] run_test(); t04 passed: 'unique(A string)=["A", " ", "s", "t", "r", "i", "n", "g"]'"
215 ECHO: "[ INFO ] run_test(); t05 passed: 'unique(["orange", "apple", "grape", "banana"])=["orange", "apple", "grape", "banana"]'"
216 ECHO: "[ INFO ] run_test(); t06 passed: 'unique(["b", "a", "n", "a", "n", "a", "s"])=["b", "a", "n", "s"]'"
217 ECHO: "[ INFO ] run_test(); t07 passed: 'unique([undef])=[undef]'"
218 ECHO: "[ INFO ] run_test(); t08 passed: 'unique([[1, 2], [2, 3]])=[[1, 2], [2, 3]]'"
219 ECHO: "[ INFO ] run_test(); t09 passed: 'unique(["ab", [1, 2], [2, 3], [4, 5]])=["ab", [1, 2], [2, 3], [4, 5]]'"
220 ECHO: "[ INFO ] run_test(); t10 passed: 'unique([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]]'"
221 ECHO: "[ INFO ] run_test(); t11 passed: 'unique([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]'"

.fi
.PP
 
