.TH "units" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units \- Units
.PP
Units and unit conversions\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBAngle\fP"
.br
.RI "\fIAngle units and conversions\&. \fP"
.ti -1c
.RI "\fBLength\fP"
.br
.RI "\fILength units and conversions\&. \fP"
.ti -1c
.RI "\fBResolution\fP"
.br
.RI "\fIArch rendering resolution management\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBunits_angle\&.scad\fP"
.br
.RI "\fIAngle units and conversions\&. \fP"
.ti -1c
.RI "file \fBunits_length\&.scad\fP"
.br
.RI "\fILength units and conversions\&. \fP"
.ti -1c
.RI "file \fBresolution\&.scad\fP"
.br
.RI "\fIArc rendering resolution abstraction\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Units and unit conversions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
