.TH "transforms_replicate" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transforms_replicate \- Replications
.PP
Shape Replications and distribution\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtransform\&.scad\fP"
.br
.RI "\fIShape transformation functions\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBst_radial_copy\fP (n, r=1, angle=true, move=false)"
.br
.RI "\fIDistribute copies of a 2D or 3D shape equally about a z-axis radius\&. \fP"
.ti -1c
.RI "module \fBst_cartesian_copy\fP (grid, incr, copy=1, center=false)"
.br
.RI "\fIDistribute copies of 2D or 3D shapes about Cartesian grid\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape Replications and distribution\&. 


.SH "Function Documentation"
.PP 
.SS "module st_cartesian_copy (grid, incr, copy = \fC1\fP, center = \fCfalse\fP)"

.PP
Distribute copies of 2D or 3D shapes about Cartesian grid\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgrid\fP <vector|decimal> A vector [x, y, z] of decimals or a single decimal for (x=y=z)\&. 
.br
\fIincr\fP <vector|decimal> A vector [x, y, z] of decimals or a single decimal for (x=y=z)\&. 
.br
\fIcopy\fP <decimal> Number of times to iterate over children\&. 
.br
\fIcenter\fP <boolean> Center distribution about origin\&.
.RE
.PP
\fBExample\fP st_cartesian_copy st_cartesian_copy 
.PP
.nf
1       st_cartesian_copy( grid=[5,5,4], incr=10, copy=50, center=true ) {cube(10, center=true); sphere(10);}

.fi
.PP
 
.PP
Definition at line 352 of file transform\&.scad\&.
.SS "module st_radial_copy (n, r = \fC1\fP, angle = \fCtrue\fP, move = \fCfalse\fP)"

.PP
Distribute copies of a 2D or 3D shape equally about a z-axis radius\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP <decimal> The number of equally spaced radii\&. 
.br
\fIr\fP <decimal> The shape move radius\&. 
.br
\fIangle\fP <boolean> Rotate each copy about z-axis\&. 
.br
\fImove\fP <boolean> Move each shape copy to radii coordinate\&.
.RE
.PP
\fBExample\fP st_radial_copy st_radial_copy 
.PP
.nf
1       st_radial_copy( n=7, r=6, move=true ) square( [20,1], center=true );

.fi
.PP
 
.PP
Definition at line 322 of file transform\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
