.TH "shapes" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shapes \- Shapes
.PP
2d and 3d shapes\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fB2d Extrusions\fP"
.br
.RI "\fIExtruded two-dimensional geometric shapes\&. \fP"
.ti -1c
.RI "\fB2d Shapes\fP"
.br
.RI "\fITwo-dimensional geometric shapes\&. \fP"
.ti -1c
.RI "\fB3d Shapes\fP"
.br
.RI "\fIThree-dimensional geometric shapes\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBshapes2d\&.scad\fP"
.br
.RI "\fITwo-dimensional basic shapes\&. \fP"
.ti -1c
.RI "file \fBshapes2de\&.scad\fP"
.br
.RI "\fILinearly extruded two-dimensional basic shapes\&. \fP"
.ti -1c
.RI "file \fBshapes3d\&.scad\fP"
.br
.RI "\fIThree-dimensional basic shapes\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
2d and 3d shapes\&. 

 
.PP
 
.PP
  
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
