.TH "database" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database \- Database
.PP
Design specification data\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBComponent\fP"
.br
.RI "\fIComponent specifications\&. \fP"
.ti -1c
.RI "\fBElectrical\fP"
.br
.RI "\fIElectrical specifications\&. \fP"
.ti -1c
.RI "\fBGeometry\fP"
.br
.RI "\fIPredefined geometry\&. \fP"
.ti -1c
.RI "\fBMaterial\fP"
.br
.RI "\fIMaterial specifications\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Design specification data\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
