.TH "tv_prim_test_g1_r" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tv_prim_test_g1_r \- Validation Results (group1) 

.PP
.nf
1 ECHO: "OpenSCAD Version [2016, 12, 21]"
2 ECHO: "[ INFO ] run_test(); t01 passed: 'is_defined(undef)=false'"
3 ECHO: "[ INFO ] run_test(); t02 passed: 'is_defined(1)=true'"
4 ECHO: "[ INFO ] run_test(); t03 passed: 'is_defined(10)=true'"
5 ECHO: "[ INFO ] run_test(); t04 passed: 'is_defined(1e+08)=true'"
6 ECHO: "[ INFO ] run_test(); t05 passed: 'is_defined(0\&.01)=true'"
7 ECHO: "[ INFO ] run_test(); t06 passed: 'is_defined(1e+308)=true'"
8 ECHO: "[ INFO ] run_test(); t07 passed: 'is_defined(-1e+308)=true'"
9 ECHO: "[ INFO ] run_test(); t08 passed: 'is_defined(inf)=true'"
10 ECHO: "[ INFO ] run_test(); t09 passed: 'is_defined(nan)=true'"
11 ECHO: "[ INFO ] run_test(); t10 passed: 'is_defined(true)=true'"
12 ECHO: "[ INFO ] run_test(); t11 passed: 'is_defined(false)=true'"
13 ECHO: "[ INFO ] run_test(); t12 passed: 'is_defined(a)=true'"
14 ECHO: "[ INFO ] run_test(); t13 passed: 'is_defined(This is a longer string)=true'"
15 ECHO: "[ INFO ] run_test(); t14 passed: 'is_defined()=true'"
16 ECHO: "[ INFO ] run_test(); t15 passed: 'is_defined([])=true'"
17 ECHO: "[ INFO ] run_test(); t16 passed: 'is_defined([undef])=true'"
18 ECHO: "[ INFO ] run_test(); t17 passed: 'is_defined([10])=true'"
19 ECHO: "[ INFO ] run_test(); t18 passed: 'is_defined([1, 2, 3])=true'"
20 ECHO: "[ INFO ] run_test(); t19 passed: 'is_defined([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=true'"
21 ECHO: "[ INFO ] run_test(); t20 passed: 'is_defined([0 : 1 : 9])=true'"
22 ECHO: "[ INFO ] run_test(); t21 passed: 'is_defined([0 : 0\&.5 : 9])=true'"
23 ECHO: "[ INFO ] run_test(); t01 passed: 'not_defined(undef)=true'"
24 ECHO: "[ INFO ] run_test(); t02 passed: 'not_defined(1)=false'"
25 ECHO: "[ INFO ] run_test(); t03 passed: 'not_defined(10)=false'"
26 ECHO: "[ INFO ] run_test(); t04 passed: 'not_defined(1e+08)=false'"
27 ECHO: "[ INFO ] run_test(); t05 passed: 'not_defined(0\&.01)=false'"
28 ECHO: "[ INFO ] run_test(); t06 passed: 'not_defined(1e+308)=false'"
29 ECHO: "[ INFO ] run_test(); t07 passed: 'not_defined(-1e+308)=false'"
30 ECHO: "[ INFO ] run_test(); t08 passed: 'not_defined(inf)=false'"
31 ECHO: "[ INFO ] run_test(); t09 passed: 'not_defined(nan)=false'"
32 ECHO: "[ INFO ] run_test(); t10 passed: 'not_defined(true)=false'"
33 ECHO: "[ INFO ] run_test(); t11 passed: 'not_defined(false)=false'"
34 ECHO: "[ INFO ] run_test(); t12 passed: 'not_defined(a)=false'"
35 ECHO: "[ INFO ] run_test(); t13 passed: 'not_defined(This is a longer string)=false'"
36 ECHO: "[ INFO ] run_test(); t14 passed: 'not_defined()=false'"
37 ECHO: "[ INFO ] run_test(); t15 passed: 'not_defined([])=false'"
38 ECHO: "[ INFO ] run_test(); t16 passed: 'not_defined([undef])=false'"
39 ECHO: "[ INFO ] run_test(); t17 passed: 'not_defined([10])=false'"
40 ECHO: "[ INFO ] run_test(); t18 passed: 'not_defined([1, 2, 3])=false'"
41 ECHO: "[ INFO ] run_test(); t19 passed: 'not_defined([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
42 ECHO: "[ INFO ] run_test(); t20 passed: 'not_defined([0 : 1 : 9])=false'"
43 ECHO: "[ INFO ] run_test(); t21 passed: 'not_defined([0 : 0\&.5 : 9])=false'"
44 ECHO: "[ INFO ] run_test(); t01 passed: 'is_empty(undef)=false'"
45 ECHO: "[ INFO ] run_test(); t02 passed: 'is_empty(1)=false'"
46 ECHO: "[ INFO ] run_test(); t03 passed: 'is_empty(10)=false'"
47 ECHO: "[ INFO ] run_test(); t04 passed: 'is_empty(1e+08)=false'"
48 ECHO: "[ INFO ] run_test(); t05 passed: 'is_empty(0\&.01)=false'"
49 ECHO: "[ INFO ] run_test(); t06 passed: 'is_empty(1e+308)=false'"
50 ECHO: "[ INFO ] run_test(); t07 passed: 'is_empty(-1e+308)=false'"
51 ECHO: "[ INFO ] run_test(); t08 passed: 'is_empty(inf)=false'"
52 ECHO: "[ INFO ] run_test(); t09 passed: 'is_empty(nan)=false'"
53 ECHO: "[ INFO ] run_test(); t10 passed: 'is_empty(true)=false'"
54 ECHO: "[ INFO ] run_test(); t11 passed: 'is_empty(false)=false'"
55 ECHO: "[ INFO ] run_test(); t12 passed: 'is_empty(a)=false'"
56 ECHO: "[ INFO ] run_test(); t13 passed: 'is_empty(This is a longer string)=false'"
57 ECHO: "[ INFO ] run_test(); t14 passed: 'is_empty()=true'"
58 ECHO: "[ INFO ] run_test(); t15 passed: 'is_empty([])=true'"
59 ECHO: "[ INFO ] run_test(); t16 passed: 'is_empty([undef])=false'"
60 ECHO: "[ INFO ] run_test(); t17 passed: 'is_empty([10])=false'"
61 ECHO: "[ INFO ] run_test(); t18 passed: 'is_empty([1, 2, 3])=false'"
62 ECHO: "[ INFO ] run_test(); t19 passed: 'is_empty([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
63 ECHO: "[ INFO ] run_test(); t20 passed: 'is_empty([0 : 1 : 9])=false'"
64 ECHO: "[ INFO ] run_test(); t21 passed: 'is_empty([0 : 0\&.5 : 9])=false'"
65 ECHO: "[ INFO ] run_test(); t01 passed: 'is_scalar(undef)=true'"
66 ECHO: "[ INFO ] run_test(); t02 passed: 'is_scalar(1)=true'"
67 ECHO: "[ INFO ] run_test(); t03 passed: 'is_scalar(10)=true'"
68 ECHO: "[ INFO ] run_test(); t04 passed: 'is_scalar(1e+08)=true'"
69 ECHO: "[ INFO ] run_test(); t05 passed: 'is_scalar(0\&.01)=true'"
70 ECHO: "[ INFO ] run_test(); t06 passed: 'is_scalar(1e+308)=true'"
71 ECHO: "[ INFO ] run_test(); t07 passed: 'is_scalar(-1e+308)=true'"
72 ECHO: "[ INFO ] run_test(); t08 passed: 'is_scalar(inf)=true'"
73 ECHO: "[ INFO ] run_test(); t09 passed: 'is_scalar(nan)=true'"
74 ECHO: "[ INFO ] run_test(); t10 passed: 'is_scalar(true)=true'"
75 ECHO: "[ INFO ] run_test(); t11 passed: 'is_scalar(false)=true'"
76 ECHO: "[ INFO ] run_test(); t12 passed: 'is_scalar(a)=false'"
77 ECHO: "[ INFO ] run_test(); t13 passed: 'is_scalar(This is a longer string)=false'"
78 ECHO: "[ INFO ] run_test(); t14 passed: 'is_scalar()=false'"
79 ECHO: "[ INFO ] run_test(); t15 passed: 'is_scalar([])=false'"
80 ECHO: "[ INFO ] run_test(); t16 passed: 'is_scalar([undef])=false'"
81 ECHO: "[ INFO ] run_test(); t17 passed: 'is_scalar([10])=false'"
82 ECHO: "[ INFO ] run_test(); t18 passed: 'is_scalar([1, 2, 3])=false'"
83 ECHO: "[ INFO ] run_test(); t19 passed: 'is_scalar([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
84 ECHO: "[ INFO ] run_test(); t20 *skip*: 'is_scalar(A shorthand range)'"
85 ECHO: "[ INFO ] run_test(); t21 *skip*: 'is_scalar(A range)'"
86 ECHO: "[ INFO ] run_test(); t01 passed: 'is_iterable(undef)=false'"
87 ECHO: "[ INFO ] run_test(); t02 passed: 'is_iterable(1)=false'"
88 ECHO: "[ INFO ] run_test(); t03 passed: 'is_iterable(10)=false'"
89 ECHO: "[ INFO ] run_test(); t04 passed: 'is_iterable(1e+08)=false'"
90 ECHO: "[ INFO ] run_test(); t05 passed: 'is_iterable(0\&.01)=false'"
91 ECHO: "[ INFO ] run_test(); t06 passed: 'is_iterable(1e+308)=false'"
92 ECHO: "[ INFO ] run_test(); t07 passed: 'is_iterable(-1e+308)=false'"
93 ECHO: "[ INFO ] run_test(); t08 passed: 'is_iterable(inf)=false'"
94 ECHO: "[ INFO ] run_test(); t09 passed: 'is_iterable(nan)=false'"
95 ECHO: "[ INFO ] run_test(); t10 passed: 'is_iterable(true)=false'"
96 ECHO: "[ INFO ] run_test(); t11 passed: 'is_iterable(false)=false'"
97 ECHO: "[ INFO ] run_test(); t12 passed: 'is_iterable(a)=true'"
98 ECHO: "[ INFO ] run_test(); t13 passed: 'is_iterable(This is a longer string)=true'"
99 ECHO: "[ INFO ] run_test(); t14 passed: 'is_iterable()=true'"
100 ECHO: "[ INFO ] run_test(); t15 passed: 'is_iterable([])=true'"
101 ECHO: "[ INFO ] run_test(); t16 passed: 'is_iterable([undef])=true'"
102 ECHO: "[ INFO ] run_test(); t17 passed: 'is_iterable([10])=true'"
103 ECHO: "[ INFO ] run_test(); t18 passed: 'is_iterable([1, 2, 3])=true'"
104 ECHO: "[ INFO ] run_test(); t19 passed: 'is_iterable([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=true'"
105 ECHO: "[ INFO ] run_test(); t20 *skip*: 'is_iterable(A shorthand range)'"
106 ECHO: "[ INFO ] run_test(); t21 *skip*: 'is_iterable(A range)'"
107 ECHO: "[ INFO ] run_test(); t01 passed: 'is_string(undef)=false'"
108 ECHO: "[ INFO ] run_test(); t02 passed: 'is_string(1)=false'"
109 ECHO: "[ INFO ] run_test(); t03 passed: 'is_string(10)=false'"
110 ECHO: "[ INFO ] run_test(); t04 passed: 'is_string(1e+08)=false'"
111 ECHO: "[ INFO ] run_test(); t05 passed: 'is_string(0\&.01)=false'"
112 ECHO: "[ INFO ] run_test(); t06 passed: 'is_string(1e+308)=false'"
113 ECHO: "[ INFO ] run_test(); t07 passed: 'is_string(-1e+308)=false'"
114 ECHO: "[ INFO ] run_test(); t08 passed: 'is_string(inf)=false'"
115 ECHO: "[ INFO ] run_test(); t09 passed: 'is_string(nan)=false'"
116 ECHO: "[ INFO ] run_test(); t10 passed: 'is_string(true)=false'"
117 ECHO: "[ INFO ] run_test(); t11 passed: 'is_string(false)=false'"
118 ECHO: "[ INFO ] run_test(); t12 passed: 'is_string(a)=true'"
119 ECHO: "[ INFO ] run_test(); t13 passed: 'is_string(This is a longer string)=true'"
120 ECHO: "[ INFO ] run_test(); t14 passed: 'is_string()=true'"
121 ECHO: "[ INFO ] run_test(); t15 passed: 'is_string([])=false'"
122 ECHO: "[ INFO ] run_test(); t16 passed: 'is_string([undef])=false'"
123 ECHO: "[ INFO ] run_test(); t17 passed: 'is_string([10])=false'"
124 ECHO: "[ INFO ] run_test(); t18 passed: 'is_string([1, 2, 3])=false'"
125 ECHO: "[ INFO ] run_test(); t19 passed: 'is_string([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
126 ECHO: "[ INFO ] run_test(); t20 passed: 'is_string([0 : 1 : 9])=false'"
127 ECHO: "[ INFO ] run_test(); t21 passed: 'is_string([0 : 0\&.5 : 9])=false'"
128 ECHO: "[ INFO ] run_test(); t01 passed: 'is_vector(undef)=false'"
129 ECHO: "[ INFO ] run_test(); t02 passed: 'is_vector(1)=false'"
130 ECHO: "[ INFO ] run_test(); t03 passed: 'is_vector(10)=false'"
131 ECHO: "[ INFO ] run_test(); t04 passed: 'is_vector(1e+08)=false'"
132 ECHO: "[ INFO ] run_test(); t05 passed: 'is_vector(0\&.01)=false'"
133 ECHO: "[ INFO ] run_test(); t06 passed: 'is_vector(1e+308)=false'"
134 ECHO: "[ INFO ] run_test(); t07 passed: 'is_vector(-1e+308)=false'"
135 ECHO: "[ INFO ] run_test(); t08 passed: 'is_vector(inf)=false'"
136 ECHO: "[ INFO ] run_test(); t09 passed: 'is_vector(nan)=false'"
137 ECHO: "[ INFO ] run_test(); t10 passed: 'is_vector(true)=false'"
138 ECHO: "[ INFO ] run_test(); t11 passed: 'is_vector(false)=false'"
139 ECHO: "[ INFO ] run_test(); t12 passed: 'is_vector(a)=false'"
140 ECHO: "[ INFO ] run_test(); t13 passed: 'is_vector(This is a longer string)=false'"
141 ECHO: "[ INFO ] run_test(); t14 passed: 'is_vector()=false'"
142 ECHO: "[ INFO ] run_test(); t15 passed: 'is_vector([])=true'"
143 ECHO: "[ INFO ] run_test(); t16 passed: 'is_vector([undef])=true'"
144 ECHO: "[ INFO ] run_test(); t17 passed: 'is_vector([10])=true'"
145 ECHO: "[ INFO ] run_test(); t18 passed: 'is_vector([1, 2, 3])=true'"
146 ECHO: "[ INFO ] run_test(); t19 passed: 'is_vector([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=true'"
147 ECHO: "[ INFO ] run_test(); t20 *skip*: 'is_vector(A shorthand range)'"
148 ECHO: "[ INFO ] run_test(); t21 *skip*: 'is_vector(A range)'"
149 ECHO: "[ INFO ] run_test(); t01 passed: 'is_boolean(undef)=false'"
150 ECHO: "[ INFO ] run_test(); t02 passed: 'is_boolean(1)=false'"
151 ECHO: "[ INFO ] run_test(); t03 passed: 'is_boolean(10)=false'"
152 ECHO: "[ INFO ] run_test(); t04 passed: 'is_boolean(1e+08)=false'"
153 ECHO: "[ INFO ] run_test(); t05 passed: 'is_boolean(0\&.01)=false'"
154 ECHO: "[ INFO ] run_test(); t06 passed: 'is_boolean(1e+308)=false'"
155 ECHO: "[ INFO ] run_test(); t07 passed: 'is_boolean(-1e+308)=false'"
156 ECHO: "[ INFO ] run_test(); t08 passed: 'is_boolean(inf)=false'"
157 ECHO: "[ INFO ] run_test(); t09 passed: 'is_boolean(nan)=false'"
158 ECHO: "[ INFO ] run_test(); t10 passed: 'is_boolean(true)=true'"
159 ECHO: "[ INFO ] run_test(); t11 passed: 'is_boolean(false)=true'"
160 ECHO: "[ INFO ] run_test(); t12 passed: 'is_boolean(a)=false'"
161 ECHO: "[ INFO ] run_test(); t13 passed: 'is_boolean(This is a longer string)=false'"
162 ECHO: "[ INFO ] run_test(); t14 passed: 'is_boolean()=false'"
163 ECHO: "[ INFO ] run_test(); t15 passed: 'is_boolean([])=false'"
164 ECHO: "[ INFO ] run_test(); t16 passed: 'is_boolean([undef])=false'"
165 ECHO: "[ INFO ] run_test(); t17 passed: 'is_boolean([10])=false'"
166 ECHO: "[ INFO ] run_test(); t18 passed: 'is_boolean([1, 2, 3])=false'"
167 ECHO: "[ INFO ] run_test(); t19 passed: 'is_boolean([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
168 ECHO: "[ INFO ] run_test(); t20 passed: 'is_boolean([0 : 1 : 9])=false'"
169 ECHO: "[ INFO ] run_test(); t21 passed: 'is_boolean([0 : 0\&.5 : 9])=false'"
170 ECHO: "[ INFO ] run_test(); t01 passed: 'is_integer(undef)=false'"
171 ECHO: "[ INFO ] run_test(); t02 passed: 'is_integer(1)=true'"
172 ECHO: "[ INFO ] run_test(); t03 passed: 'is_integer(10)=true'"
173 ECHO: "[ INFO ] run_test(); t04 passed: 'is_integer(1e+08)=true'"
174 ECHO: "[ INFO ] run_test(); t05 passed: 'is_integer(0\&.01)=false'"
175 ECHO: "[ INFO ] run_test(); t06 passed: 'is_integer(1e+308)=true'"
176 ECHO: "[ INFO ] run_test(); t07 passed: 'is_integer(-1e+308)=true'"
177 ECHO: "[ INFO ] run_test(); t08 passed: 'is_integer(inf)=false'"
178 ECHO: "[ INFO ] run_test(); t09 passed: 'is_integer(nan)=false'"
179 ECHO: "[ INFO ] run_test(); t10 passed: 'is_integer(true)=false'"
180 ECHO: "[ INFO ] run_test(); t11 passed: 'is_integer(false)=false'"
181 ECHO: "[ INFO ] run_test(); t12 passed: 'is_integer(a)=false'"
182 ECHO: "[ INFO ] run_test(); t13 passed: 'is_integer(This is a longer string)=false'"
183 ECHO: "[ INFO ] run_test(); t14 passed: 'is_integer()=false'"
184 ECHO: "[ INFO ] run_test(); t15 passed: 'is_integer([])=false'"
185 ECHO: "[ INFO ] run_test(); t16 passed: 'is_integer([undef])=false'"
186 ECHO: "[ INFO ] run_test(); t17 passed: 'is_integer([10])=false'"
187 ECHO: "[ INFO ] run_test(); t18 passed: 'is_integer([1, 2, 3])=false'"
188 ECHO: "[ INFO ] run_test(); t19 passed: 'is_integer([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
189 ECHO: "[ INFO ] run_test(); t20 passed: 'is_integer([0 : 1 : 9])=false'"
190 ECHO: "[ INFO ] run_test(); t21 passed: 'is_integer([0 : 0\&.5 : 9])=false'"
191 ECHO: "[ INFO ] run_test(); t01 passed: 'is_decimal(undef)=false'"
192 ECHO: "[ INFO ] run_test(); t02 passed: 'is_decimal(1)=false'"
193 ECHO: "[ INFO ] run_test(); t03 passed: 'is_decimal(10)=false'"
194 ECHO: "[ INFO ] run_test(); t04 passed: 'is_decimal(1e+08)=false'"
195 ECHO: "[ INFO ] run_test(); t05 passed: 'is_decimal(0\&.01)=true'"
196 ECHO: "[ INFO ] run_test(); t06 passed: 'is_decimal(1e+308)=false'"
197 ECHO: "[ INFO ] run_test(); t07 passed: 'is_decimal(-1e+308)=false'"
198 ECHO: "[ INFO ] run_test(); t08 passed: 'is_decimal(inf)=false'"
199 ECHO: "[ INFO ] run_test(); t09 passed: 'is_decimal(nan)=false'"
200 ECHO: "[ INFO ] run_test(); t10 passed: 'is_decimal(true)=false'"
201 ECHO: "[ INFO ] run_test(); t11 passed: 'is_decimal(false)=false'"
202 ECHO: "[ INFO ] run_test(); t12 passed: 'is_decimal(a)=false'"
203 ECHO: "[ INFO ] run_test(); t13 passed: 'is_decimal(This is a longer string)=false'"
204 ECHO: "[ INFO ] run_test(); t14 passed: 'is_decimal()=false'"
205 ECHO: "[ INFO ] run_test(); t15 passed: 'is_decimal([])=false'"
206 ECHO: "[ INFO ] run_test(); t16 passed: 'is_decimal([undef])=false'"
207 ECHO: "[ INFO ] run_test(); t17 passed: 'is_decimal([10])=false'"
208 ECHO: "[ INFO ] run_test(); t18 passed: 'is_decimal([1, 2, 3])=false'"
209 ECHO: "[ INFO ] run_test(); t19 passed: 'is_decimal([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
210 ECHO: "[ INFO ] run_test(); t20 passed: 'is_decimal([0 : 1 : 9])=false'"
211 ECHO: "[ INFO ] run_test(); t21 passed: 'is_decimal([0 : 0\&.5 : 9])=false'"
212 ECHO: "[ INFO ] run_test(); t01 passed: 'is_number(undef)=false'"
213 ECHO: "[ INFO ] run_test(); t02 passed: 'is_number(1)=true'"
214 ECHO: "[ INFO ] run_test(); t03 passed: 'is_number(10)=true'"
215 ECHO: "[ INFO ] run_test(); t04 passed: 'is_number(1e+08)=true'"
216 ECHO: "[ INFO ] run_test(); t05 passed: 'is_number(0\&.01)=true'"
217 ECHO: "[ INFO ] run_test(); t06 passed: 'is_number(1e+308)=true'"
218 ECHO: "[ INFO ] run_test(); t07 passed: 'is_number(-1e+308)=true'"
219 ECHO: "[ INFO ] run_test(); t08 passed: 'is_number(inf)=true'"
220 ECHO: "[ INFO ] run_test(); t09 passed: 'is_number(nan)=true'"
221 ECHO: "[ INFO ] run_test(); t10 passed: 'is_number(true)=false'"
222 ECHO: "[ INFO ] run_test(); t11 passed: 'is_number(false)=false'"
223 ECHO: "[ INFO ] run_test(); t12 passed: 'is_number(a)=false'"
224 ECHO: "[ INFO ] run_test(); t13 passed: 'is_number(This is a longer string)=false'"
225 ECHO: "[ INFO ] run_test(); t14 passed: 'is_number()=false'"
226 ECHO: "[ INFO ] run_test(); t15 passed: 'is_number([])=false'"
227 ECHO: "[ INFO ] run_test(); t16 passed: 'is_number([undef])=false'"
228 ECHO: "[ INFO ] run_test(); t17 passed: 'is_number([10])=false'"
229 ECHO: "[ INFO ] run_test(); t18 passed: 'is_number([1, 2, 3])=false'"
230 ECHO: "[ INFO ] run_test(); t19 passed: 'is_number([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
231 ECHO: "[ INFO ] run_test(); t20 passed: 'is_number([0 : 1 : 9])=false'"
232 ECHO: "[ INFO ] run_test(); t21 passed: 'is_number([0 : 0\&.5 : 9])=false'"
233 ECHO: "[ INFO ] run_test(); t01 passed: 'is_range(undef)=false'"
234 ECHO: "[ INFO ] run_test(); t02 passed: 'is_range(1)=false'"
235 ECHO: "[ INFO ] run_test(); t03 passed: 'is_range(10)=false'"
236 ECHO: "[ INFO ] run_test(); t04 passed: 'is_range(1e+08)=false'"
237 ECHO: "[ INFO ] run_test(); t05 passed: 'is_range(0\&.01)=false'"
238 ECHO: "[ INFO ] run_test(); t06 passed: 'is_range(1e+308)=false'"
239 ECHO: "[ INFO ] run_test(); t07 passed: 'is_range(-1e+308)=false'"
240 ECHO: "[ INFO ] run_test(); t08 passed: 'is_range(inf)=false'"
241 ECHO: "[ INFO ] run_test(); t09 passed: 'is_range(nan)=false'"
242 ECHO: "[ INFO ] run_test(); t10 passed: 'is_range(true)=false'"
243 ECHO: "[ INFO ] run_test(); t11 passed: 'is_range(false)=false'"
244 ECHO: "[ INFO ] run_test(); t12 passed: 'is_range(a)=false'"
245 ECHO: "[ INFO ] run_test(); t13 passed: 'is_range(This is a longer string)=false'"
246 ECHO: "[ INFO ] run_test(); t14 passed: 'is_range()=false'"
247 ECHO: "[ INFO ] run_test(); t15 passed: 'is_range([])=false'"
248 ECHO: "[ INFO ] run_test(); t16 passed: 'is_range([undef])=false'"
249 ECHO: "[ INFO ] run_test(); t17 passed: 'is_range([10])=false'"
250 ECHO: "[ INFO ] run_test(); t18 passed: 'is_range([1, 2, 3])=false'"
251 ECHO: "[ INFO ] run_test(); t19 passed: 'is_range([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
252 ECHO: "[ INFO ] run_test(); t20 passed: 'is_range([0 : 1 : 9])=true'"
253 ECHO: "[ INFO ] run_test(); t21 passed: 'is_range([0 : 0\&.5 : 9])=true'"
254 ECHO: "[ INFO ] run_test(); t01 passed: 'is_nan(undef)=false'"
255 ECHO: "[ INFO ] run_test(); t02 passed: 'is_nan(1)=false'"
256 ECHO: "[ INFO ] run_test(); t03 passed: 'is_nan(10)=false'"
257 ECHO: "[ INFO ] run_test(); t04 passed: 'is_nan(1e+08)=false'"
258 ECHO: "[ INFO ] run_test(); t05 passed: 'is_nan(0\&.01)=false'"
259 ECHO: "[ INFO ] run_test(); t06 passed: 'is_nan(1e+308)=false'"
260 ECHO: "[ INFO ] run_test(); t07 passed: 'is_nan(-1e+308)=false'"
261 ECHO: "[ INFO ] run_test(); t08 passed: 'is_nan(inf)=false'"
262 ECHO: "[ INFO ] run_test(); t09 passed: 'is_nan(nan)=true'"
263 ECHO: "[ INFO ] run_test(); t10 passed: 'is_nan(true)=false'"
264 ECHO: "[ INFO ] run_test(); t11 passed: 'is_nan(false)=false'"
265 ECHO: "[ INFO ] run_test(); t12 passed: 'is_nan(a)=false'"
266 ECHO: "[ INFO ] run_test(); t13 passed: 'is_nan(This is a longer string)=false'"
267 ECHO: "[ INFO ] run_test(); t14 passed: 'is_nan()=false'"
268 ECHO: "[ INFO ] run_test(); t15 passed: 'is_nan([])=false'"
269 ECHO: "[ INFO ] run_test(); t16 passed: 'is_nan([undef])=false'"
270 ECHO: "[ INFO ] run_test(); t17 passed: 'is_nan([10])=false'"
271 ECHO: "[ INFO ] run_test(); t18 passed: 'is_nan([1, 2, 3])=false'"
272 ECHO: "[ INFO ] run_test(); t19 passed: 'is_nan([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
273 ECHO: "[ INFO ] run_test(); t20 passed: 'is_nan([0 : 1 : 9])=false'"
274 ECHO: "[ INFO ] run_test(); t21 passed: 'is_nan([0 : 0\&.5 : 9])=false'"
275 ECHO: "[ INFO ] run_test(); t01 passed: 'is_inf(undef)=false'"
276 ECHO: "[ INFO ] run_test(); t02 passed: 'is_inf(1)=false'"
277 ECHO: "[ INFO ] run_test(); t03 passed: 'is_inf(10)=false'"
278 ECHO: "[ INFO ] run_test(); t04 passed: 'is_inf(1e+08)=false'"
279 ECHO: "[ INFO ] run_test(); t05 passed: 'is_inf(0\&.01)=false'"
280 ECHO: "[ INFO ] run_test(); t06 passed: 'is_inf(1e+308)=false'"
281 ECHO: "[ INFO ] run_test(); t07 passed: 'is_inf(-1e+308)=false'"
282 ECHO: "[ INFO ] run_test(); t08 passed: 'is_inf(inf)=true'"
283 ECHO: "[ INFO ] run_test(); t09 passed: 'is_inf(nan)=false'"
284 ECHO: "[ INFO ] run_test(); t10 passed: 'is_inf(true)=false'"
285 ECHO: "[ INFO ] run_test(); t11 passed: 'is_inf(false)=false'"
286 ECHO: "[ INFO ] run_test(); t12 passed: 'is_inf(a)=false'"
287 ECHO: "[ INFO ] run_test(); t13 passed: 'is_inf(This is a longer string)=false'"
288 ECHO: "[ INFO ] run_test(); t14 passed: 'is_inf()=false'"
289 ECHO: "[ INFO ] run_test(); t15 passed: 'is_inf([])=false'"
290 ECHO: "[ INFO ] run_test(); t16 passed: 'is_inf([undef])=false'"
291 ECHO: "[ INFO ] run_test(); t17 passed: 'is_inf([10])=false'"
292 ECHO: "[ INFO ] run_test(); t18 passed: 'is_inf([1, 2, 3])=false'"
293 ECHO: "[ INFO ] run_test(); t19 passed: 'is_inf([[1, 2, 3], [4, 5, 6], [7, 8, 9]])=false'"
294 ECHO: "[ INFO ] run_test(); t20 passed: 'is_inf([0 : 1 : 9])=false'"
295 ECHO: "[ INFO ] run_test(); t21 passed: 'is_inf([0 : 0\&.5 : 9])=false'"
296 ECHO: "[ INFO ] run_test(); t01 *skip*: 'is_even(The undefined value)'"
297 ECHO: "[ INFO ] run_test(); t02 passed: 'is_even(1)=false'"
298 ECHO: "[ INFO ] run_test(); t03 passed: 'is_even(10)=true'"
299 ECHO: "[ INFO ] run_test(); t04 passed: 'is_even(1e+08)=true'"
300 ECHO: "[ INFO ] run_test(); t05 passed: 'is_even(0\&.01)=false'"
301 ECHO: "[ INFO ] run_test(); t06 passed: 'is_even(1e+308)=true'"
302 ECHO: "[ INFO ] run_test(); t07 passed: 'is_even(-1e+308)=true'"
303 ECHO: "[ INFO ] run_test(); t08 *skip*: 'is_even(The max number^2)'"
304 ECHO: "[ INFO ] run_test(); t09 *skip*: 'is_even(The invalid number nan)'"
305 ECHO: "[ INFO ] run_test(); t10 *skip*: 'is_even(The boolean true)'"
306 ECHO: "[ INFO ] run_test(); t11 *skip*: 'is_even(The boolean false)'"
307 ECHO: "[ INFO ] run_test(); t12 *skip*: 'is_even(A character string)'"
308 ECHO: "[ INFO ] run_test(); t13 *skip*: 'is_even(A string)'"
309 ECHO: "[ INFO ] run_test(); t14 *skip*: 'is_even(The empty string)'"
310 ECHO: "[ INFO ] run_test(); t15 *skip*: 'is_even(The empty vector)'"
311 ECHO: "[ INFO ] run_test(); t16 *skip*: 'is_even(A 1-tuple vector of undef)'"
312 ECHO: "[ INFO ] run_test(); t17 *skip*: 'is_even(A 1-tuple vector)'"
313 ECHO: "[ INFO ] run_test(); t18 *skip*: 'is_even(A 3-tuple vector)'"
314 ECHO: "[ INFO ] run_test(); t19 *skip*: 'is_even(A vector of vectors)'"
315 ECHO: "[ INFO ] run_test(); t20 *skip*: 'is_even(A shorthand range)'"
316 ECHO: "[ INFO ] run_test(); t21 *skip*: 'is_even(A range)'"
317 ECHO: "[ INFO ] run_test(); t01 *skip*: 'is_odd(The undefined value)'"
318 ECHO: "[ INFO ] run_test(); t02 passed: 'is_odd(1)=true'"
319 ECHO: "[ INFO ] run_test(); t03 passed: 'is_odd(10)=false'"
320 ECHO: "[ INFO ] run_test(); t04 passed: 'is_odd(1e+08)=false'"
321 ECHO: "[ INFO ] run_test(); t05 passed: 'is_odd(0\&.01)=false'"
322 ECHO: "[ INFO ] run_test(); t06 passed: 'is_odd(1e+308)=false'"
323 ECHO: "[ INFO ] run_test(); t07 passed: 'is_odd(-1e+308)=false'"
324 ECHO: "[ INFO ] run_test(); t08 *skip*: 'is_odd(The max number^2)'"
325 ECHO: "[ INFO ] run_test(); t09 *skip*: 'is_odd(The invalid number nan)'"
326 ECHO: "[ INFO ] run_test(); t10 *skip*: 'is_odd(The boolean true)'"
327 ECHO: "[ INFO ] run_test(); t11 *skip*: 'is_odd(The boolean false)'"
328 ECHO: "[ INFO ] run_test(); t12 *skip*: 'is_odd(A character string)'"
329 ECHO: "[ INFO ] run_test(); t13 *skip*: 'is_odd(A string)'"
330 ECHO: "[ INFO ] run_test(); t14 *skip*: 'is_odd(The empty string)'"
331 ECHO: "[ INFO ] run_test(); t15 *skip*: 'is_odd(The empty vector)'"
332 ECHO: "[ INFO ] run_test(); t16 *skip*: 'is_odd(A 1-tuple vector of undef)'"
333 ECHO: "[ INFO ] run_test(); t17 *skip*: 'is_odd(A 1-tuple vector)'"
334 ECHO: "[ INFO ] run_test(); t18 *skip*: 'is_odd(A 3-tuple vector)'"
335 ECHO: "[ INFO ] run_test(); t19 *skip*: 'is_odd(A vector of vectors)'"
336 ECHO: "[ INFO ] run_test(); t20 *skip*: 'is_odd(A shorthand range)'"
337 ECHO: "[ INFO ] run_test(); t21 *skip*: 'is_odd(A range)'"

.fi
.PP
 
