.TH "math" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math \- Math
.PP
Mathematical functions\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBBitwise\fP"
.br
.RI "\fIBase-two bitwise binary operations\&. \fP"
.ti -1c
.RI "\fBLinear Algebra\fP"
.br
.RI "\fILinear algebra transformations on Euclidean coordinates\&. \fP"
.ti -1c
.RI "\fBOther Shapes\fP"
.br
.RI "\fIMathematical functions for other shapes\&. \fP"
.ti -1c
.RI "\fBPolytopes\fP"
.br
.RI "\fIPolygon and polyhedron mathematical functions\&. \fP"
.ti -1c
.RI "\fBTriangles\fP"
.br
.RI "\fITriangle mathematical functions\&. \fP"
.ti -1c
.RI "\fBUtilities\fP"
.br
.RI "\fIMiscellaneous mathematical utilities\&. \fP"
.ti -1c
.RI "\fBVector Algebra\fP"
.br
.RI "\fIAlgebraic operations on Euclidean vectors\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmath\&.scad\fP"
.br
.RI "\fIMathematical function primitives\&. \fP"
.ti -1c
.RI "file \fBmath_bitwise\&.scad\fP"
.br
.RI "\fIMathematical base-two bitwise binary functions\&. \fP"
.ti -1c
.RI "file \fBmath_linalg\&.scad\fP"
.br
.RI "\fILinear algebra mathematical functions\&. \fP"
.ti -1c
.RI "file \fBmath_oshapes\&.scad\fP"
.br
.RI "\fIOther shapes mathematical functions\&. \fP"
.ti -1c
.RI "file \fBmath_polytope\&.scad\fP"
.br
.RI "\fIPolygon and polyhedron mathematical functions\&. \fP"
.ti -1c
.RI "file \fBmath_triangle\&.scad\fP"
.br
.RI "\fITriangle solutions mathematical functions\&. \fP"
.ti -1c
.RI "file \fBmath_utility\&.scad\fP"
.br
.RI "\fIMiscellaneous mathematical utilities\&. \fP"
.ti -1c
.RI "file \fBmath_vecalg\&.scad\fP"
.br
.RI "\fIVector algebra mathematical functions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mathematical functions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
