.TH "constants_system" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants_system \- System
.PP
System/Program limits\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.scad\fP"
.br
.RI "\fIMechanical design constants\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBnumber_max\fP = 1e308"
.br
.RI "\fIThe largest representable number in OpenSCAD scripts\&. \fP"
.ti -1c
.RI "\fBnumber_min\fP = -1e308"
.br
.RI "\fIThe smallest representable number in OpenSCAD scripts\&. \fP"
.ti -1c
.RI "\fBempty_str\fP = ''"
.br
.RI "\fIA string with no content (the empty string)\&. \fP"
.ti -1c
.RI "\fBempty_v\fP = []"
.br
.RI "\fIA vector with no content (the empty vector)\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
System/Program limits\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
