.TH "datatypes Directory Reference" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatatypes-base\&.scad\fP"
.br
.RI "\fIInclude file wrapper of data types base primitives\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_iterable\&.scad\fP"
.br
.RI "\fIIterable data type identification\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_list\&.scad\fP"
.br
.RI "\fIList data type identification\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_scalar\&.scad\fP"
.br
.RI "\fIScalar data type identification\&. \fP"
.ti -1c
.RI "file \fBdatatypes_map\&.scad\fP"
.br
.RI "\fIMap data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_operate_iterable\&.scad\fP"
.br
.RI "\fIIterable data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_operate_list\&.scad\fP"
.br
.RI "\fIList data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_operate_scalar\&.scad\fP"
.br
.RI "\fIScalar data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_table\&.scad\fP"
.br
.RI "\fITable data type operations\&. \fP"
.in -1c
