.TH "transforms_extrude" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transforms_extrude \- Extrusions
.PP
Shape Extrusions\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtransform\&.scad\fP"
.br
.RI "\fIShape transformation functions\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBst_rotate_extrude\fP (r, pa=0, ra=360, profile=false)"
.br
.RI "\fIRevolve the 2D shape about the z-axis\&. \fP"
.ti -1c
.RI "module \fBst_rotate_extrude_elongate\fP (r, l, pa=0, ra=360, m=255, profile=false)"
.br
.RI "\fIRevolve the 2D shape about the z-axis with linear elongation\&. \fP"
.ti -1c
.RI "module \fBst_linear_extrude_scale\fP (h, center=false)"
.br
.RI "\fILinearly extrude 2D shape with extrusion upper and lower scaling\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape Extrusions\&. 


.SH "Function Documentation"
.PP 
.SS "module st_linear_extrude_scale (h, center = \fCfalse\fP)"

.PP
Linearly extrude 2D shape with extrusion upper and lower scaling\&. 
.PP
\fBParameters:\fP
.RS 4
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&. 
.br
\fIcenter\fP <boolean> Center extrusion about origin\&.
.RE
.PP
When \fCh\fP is a decimal, the shape is extruded linearly as normal\&. To scale the upper and lower slices of the extrusion, \fCh\fP must be assigned a vector with a minimum of three decimal values as described in the following table\&.
.PP
sym h[n] default description  h 0 total extrusion height n1 1 (+z) number of scaled extrusion slices h1 2 (+z) extrusion scale percentage x1 3 -h1 (+z) x-dimension scale percentage y1 4 x1 (+z) y-dimension scale percentage n2 5 n1 (-z) number of scaled extrusion slices h2 6 h1 (-z) extrusion scale percentage x2 7 x1 (-z) x-dimension scale percentage y2 8 y1 (-z) y-dimension scale percentage 
.PP
\fBExample\fP st_linear_extrude_scale st_linear_extrude_scale 
.PP
.nf
1       st_linear_extrude_scale( [5,10,15,-5], center=true ) square( [20,15], center=true );

.fi
.PP
.PP
\fBNote:\fP
.RS 4
When symmetrical scaling is desired, shape must be centered about origin\&. 
.RE
.PP

.PP
Definition at line 230 of file transform\&.scad\&.
.SS "module st_rotate_extrude (r, pa = \fC0\fP, ra = \fC360\fP, profile = \fCfalse\fP)"

.PP
Revolve the 2D shape about the z-axis\&. 
.PP
\fBParameters:\fP
.RS 4
\fIr\fP <decimal> The rotation radius\&. 
.br
\fIpa\fP <decimal> The profile pitch angle in degrees\&. 
.br
\fIra\fP <decimal> The rotation sweep angle in degrees\&. 
.br
\fIprofile\fP <boolean> Show profile only (do not extrude)\&.
.RE
.PP
\fBExample\fP st_rotate_extrude st_rotate_extrude 
.PP
.nf
1       st_rotate_extrude( r=50, pa=45, ra=270 ) square( [10,5], center=true );

.fi
.PP
 
.PP
Definition at line 103 of file transform\&.scad\&.
.SS "module st_rotate_extrude_elongate (r, l, pa = \fC0\fP, ra = \fC360\fP, m = \fC255\fP, profile = \fCfalse\fP)"

.PP
Revolve the 2D shape about the z-axis with linear elongation\&. 
.PP
\fBParameters:\fP
.RS 4
\fIr\fP <decimal> The rotation radius\&. 
.br
\fIl\fP <vector|decimal> The elongation length\&. A vector [x, y] of decimals or a single decimal for (x=y) 
.br
\fIpa\fP <decimal> The profile pitch angle in degrees\&. 
.br
\fIra\fP <decimal> The rotation sweep angle in degrees\&. 
.br
\fIm\fP <integer> The section render mode\&. An 8-bit encoded integer that indicates the revolution sections to render\&. Bit values \fB1\fP enables the corresponding section and bit values \fB0\fP are disabled\&. Sections are assigned to the bit position in counter-clockwise order\&. 
.br
\fIprofile\fP <boolean> Show profile only (do not extrude)\&.
.RE
.PP
\fBExample\fP st_rotate_extrude_elongate st_rotate_extrude_elongate 
.PP
.nf
1       st_rotate_extrude_elongate( r=25, l=[5, 50], pa=45, m=31 ) square( [10,5], center=true );

.fi
.PP
.PP
\fBNote:\fP
.RS 4
When elongating \fC(l > 0)\fP, \fCra\fP is ignored\&. However, \fCm\fP may be used to control which complete revolution section to render\&. 
.RE
.PP

.PP
Definition at line 139 of file transform\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
