.TH "datatypes" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes \- Datatypes
.PP
Data type definitions and operators\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBIdentification\fP"
.br
.RI "\fICompile-time data type identification and tests\&. \fP"
.ti -1c
.RI "\fBMaps\fP"
.br
.RI "\fIMap data type operations\&. \fP"
.ti -1c
.RI "\fBOperations\fP"
.br
.RI "\fIData type operation\&. \fP"
.ti -1c
.RI "\fBTables\fP"
.br
.RI "\fITable data type operations\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatatypes-base\&.scad\fP"
.br
.RI "\fIInclude file wrapper of data types base primitives\&. \fP"
.ti -1c
.RI "file \fBdatatypes_map\&.scad\fP"
.br
.RI "\fIMap data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_table\&.scad\fP"
.br
.RI "\fITable data type operations\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data type definitions and operators\&. 

See \fBData types\fP for nomenclature, assumptions, and conventions used to specify values and data types throughout the library\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
