.TH "constants_system" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants_system \- System
.PP
System and program limits\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.scad\fP"
.br
.RI "\fIDesign constant definitions\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBnumber_max\fP = 1e308"
.br
.RI "\fI<decimal> The largest representable number in OpenSCAD scripts\&. \fP"
.ti -1c
.RI "\fBnumber_min\fP = -1e308"
.br
.RI "\fI<decimal> The smallest representable number in OpenSCAD scripts\&. \fP"
.ti -1c
.RI "\fBempty_str\fP = ''"
.br
.RI "\fI<string> A string with no characters (the empty string)\&. \fP"
.ti -1c
.RI "\fBempty_lst\fP = []"
.br
.RI "\fI<list> A list with no values (the empty list)\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
System and program limits\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
