.TH "constants_euclidean" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants_euclidean \- Euclidean
.PP
Euclidean 2D/3D space mapping\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.scad\fP"
.br
.RI "\fIMechanical design constants\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBx_axis_vi\fP = 0"
.br
.RI "\fIThe vector index for the x-coordinate of a vector\&. \fP"
.ti -1c
.RI "\fBy_axis_vi\fP = 1"
.br
.RI "\fIThe vector index for the y-coordinate of a vector\&. \fP"
.ti -1c
.RI "\fBz_axis_vi\fP = 2"
.br
.RI "\fIThe vector index for the z-coordinate of a vector\&. \fP"
.ti -1c
.RI "\fBorigin2d\fP = [0, 0]"
.br
.RI "\fIThe origin coordinates in 2-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis2d_uv\fP = [1, 0]"
.br
.RI "\fIThe unit vector of the positive x-axis in 2-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis2d_uv\fP = [0, 1]"
.br
.RI "\fIThe unit vector of the positive y-axis in 2-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBorigin3d\fP = [0, 0, 0]"
.br
.RI "\fIThe origin coordinates in 3-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis3d_uv\fP = [1, 0, 0]"
.br
.RI "\fIThe unit vector of the positive x-axis in 3-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis3d_uv\fP = [0, 1, 0]"
.br
.RI "\fIThe unit vector of the positive y-axis in 3-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBz_axis3d_uv\fP = [0, 0, 1]"
.br
.RI "\fIThe unit vector of the positive z-axis in 3-dimensional Euclidean space\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Euclidean 2D/3D space mapping\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
