.TH "shapes/shapes2d.scad" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shapes/shapes2d.scad \- Two-dimensional basic shapes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <\&.\&./math/math_triangle\&.scad>\fP
.br
\fC#include <\&.\&./tools/tools_utility\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBrectangle\fP (size, vr, vrm=0, center=false)"
.br
.RI "\fIA rectangle with edge, fillet, and/or chamfer corners\&. \fP"
.ti -1c
.RI "module \fBrectangle_c\fP (size, core, t, co, cr=0, vr, vr1, vr2, vrm=0, vrm1, vrm2, center=false)"
.br
.RI "\fIA rectangle with a removed rectangular core\&. \fP"
.ti -1c
.RI "module \fBrhombus\fP (size, vr, center=false)"
.br
.RI "\fIA rhombus\&. \fP"
.ti -1c
.RI "module \fBtriangle_ppp\fP (v1, v2, v3, vr, v1r, v2r, v3r, centroid=false, incenter=false)"
.br
.RI "\fIA general triangle specified by three vertices\&. \fP"
.ti -1c
.RI "module \fBtriangle_lp\fP (v, vr, centroid=false, incenter=false)"
.br
.RI "\fIA general triangle specified by a list of its three vertices\&. \fP"
.ti -1c
.RI "module \fBtriangle_sss\fP (s1, s2, s3, vr, v1r, v2r, v3r, centroid=false, incenter=false)"
.br
.RI "\fIA general triangle specified by its three side lengths\&. \fP"
.ti -1c
.RI "module \fBtriangle_ls\fP (v, vr, centroid=false, incenter=false)"
.br
.RI "\fIA general triangle specified by a list of its three side lengths\&. \fP"
.ti -1c
.RI "module \fBtriangle_ls_c\fP (vs, vc, co, cr=0, vr, vr1, vr2, centroid=false, incenter=false)"
.br
.RI "\fIA general triangle specified by its sides with a removed triangular core\&. \fP"
.ti -1c
.RI "module \fBtriangle_sas\fP (s1, a, s2, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false)"
.br
.RI "\fIA general triangle specified by two sides and the included angle\&. \fP"
.ti -1c
.RI "module \fBtriangle_asa\fP (a1, s, a2, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false)"
.br
.RI "\fIA general triangle specified by a side and two adjacent angles\&. \fP"
.ti -1c
.RI "module \fBtriangle_aas\fP (a1, a2, s, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false)"
.br
.RI "\fIA general triangle specified by a side, one adjacent angle and the opposite angle\&. \fP"
.ti -1c
.RI "module \fBtriangle_ss\fP (x, y, vr, v1r, v2r, v3r, centroid=false, incenter=false)"
.br
.RI "\fIA right-angled triangle specified by its opposite and adjacent side lengths\&. \fP"
.ti -1c
.RI "module \fBtriangle_sa\fP (x, y, aa, oa, vr, v1r, v2r, v3r, centroid=false, incenter=false)"
.br
.RI "\fIA right-angled triangle specified by a side length and an angle\&. \fP"
.ti -1c
.RI "module \fBngon\fP (n, r, vr)"
.br
.RI "\fIAn n-sided equiangular/equilateral regular polygon\&. \fP"
.ti -1c
.RI "module \fBellipse\fP (size)"
.br
.RI "\fIAn ellipse\&. \fP"
.ti -1c
.RI "module \fBellipse_c\fP (size, core, t, co, cr=0)"
.br
.RI "\fIAn ellipse with a removed elliptical core\&. \fP"
.ti -1c
.RI "module \fBellipse_s\fP (size, a1=0, a2=0)"
.br
.RI "\fIAn ellipse sector\&. \fP"
.ti -1c
.RI "module \fBellipse_cs\fP (size, core, t, a1=0, a2=0, co, cr=0)"
.br
.RI "\fIA sector of an ellipse with a removed elliptical core\&. \fP"
.ti -1c
.RI "module \fBstar2d\fP (size, n=5, vr)"
.br
.RI "\fIA two-dimensional star\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Two-dimensional basic shapes\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBshapes2d\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
