.TH "tools/tools_polytope.scad" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools/tools_polytope.scad \- Polygon and polyhedron tools\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <\&.\&./math/math_polytope\&.scad>\fP
.br
\fC#include <tools_align\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBpolytope_number\fP (c, f, e, vi=true, fi=true, ei=true, sp=false, ts, th, to, tr=0)"
.br
.RI "\fILabel the vertices, paths, and edges of a polytope\&. \fP"
.ti -1c
.RI "module \fBpolytope_frame\fP (c, f, e, vi=true, fi=true, ei=true, vc=1, fc=2, ec=0)"
.br
.RI "\fIAssemble a polytope skeletal frame using child objects\&. \fP"
.ti -1c
.RI "module \fBpolytope_bbox\fP (c, f, a)"
.br
.RI "\fIThe 3d or 2d bounding box shape for a polytope\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Polygon and polyhedron tools\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBtools_polytope\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
