.TH "constants.scad" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants.scad \- Mechanical design constants\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBeps\fP = 0\&.01"
.br
.RI "\fI<decimal> Epsilon, small distance to deal with overlaping shapes \fP"
.ti -1c
.RI "\fBpi\fP = 3\&.1415926535897932384626433832795"
.br
.RI "\fI<decimal> The ratio of a circle's circumference to its diameter \fP"
.ti -1c
.RI "\fBtau\fP = 2*\fBpi\fP"
.br
.RI "\fI<decimal> The ratio of a circle's circumference to its radius \fP"
.ti -1c
.RI "\fBnumber_max\fP = 1e308"
.br
.RI "\fIThe largest representable number in OpenSCAD scripts\&. \fP"
.ti -1c
.RI "\fBnumber_min\fP = -1e308"
.br
.RI "\fIThe smallest representable number in OpenSCAD scripts\&. \fP"
.ti -1c
.RI "\fBempty_str\fP = ''"
.br
.RI "\fIA string with no content (the empty string)\&. \fP"
.ti -1c
.RI "\fBempty_v\fP = []"
.br
.RI "\fIA vector with no content (the empty vector)\&. \fP"
.ti -1c
.RI "\fBx_axis_vi\fP = 0"
.br
.RI "\fIThe vector index for the x-coordinate of a vector\&. \fP"
.ti -1c
.RI "\fBy_axis_vi\fP = 1"
.br
.RI "\fIThe vector index for the y-coordinate of a vector\&. \fP"
.ti -1c
.RI "\fBz_axis_vi\fP = 2"
.br
.RI "\fIThe vector index for the z-coordinate of a vector\&. \fP"
.ti -1c
.RI "\fBorigin2d\fP = [0, 0]"
.br
.RI "\fIThe origin coordinates in 2-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis2d_uv\fP = [1, 0]"
.br
.RI "\fIThe unit vector of the positive x-axis in 2-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis2d_uv\fP = [0, 1]"
.br
.RI "\fIThe unit vector of the positive y-axis in 2-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBorigin3d\fP = [0, 0, 0]"
.br
.RI "\fIThe origin coordinates in 3-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis3d_uv\fP = [1, 0, 0]"
.br
.RI "\fIThe unit vector of the positive x-axis in 3-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis3d_uv\fP = [0, 1, 0]"
.br
.RI "\fIThe unit vector of the positive y-axis in 3-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBz_axis3d_uv\fP = [0, 0, 1]"
.br
.RI "\fIThe unit vector of the positive z-axis in 3-dimensional Euclidean space\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mechanical design constants\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&.
.PP
\fBNote:\fP
.RS 4
Include this library file using the \fBinclude\fP statement\&. 
.RE
.PP

.PP
Definition in file \fBconstants\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
