.TH "tools/tools_utility.scad" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools/tools_utility.scad \- Shape transformation utility tools\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <\&.\&./console\&.scad>\fP
.br
\fC#include <\&.\&./math/math-base\&.scad>\fP
.br
\fC#include <\&.\&./math/math_oshapes\&.scad>\fP
.br
\fC#include <\&.\&./math/math_bitwise\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBrotate_extrude_tr\fP (r, pa=0, ra=360, profile=false)"
.br
.RI "\fITranslate, rotate, and revolve the 2d shape about the z-axis\&. \fP"
.ti -1c
.RI "module \fBrotate_extrude_tre\fP (r, l, pa=0, ra=360, m=255, profile=false)"
.br
.RI "\fITranslate, rotate, and revolve the 2d shape about the z-axis with linear elongation\&. \fP"
.ti -1c
.RI "module \fBlinear_extrude_uls\fP (h, center=false)"
.br
.RI "\fILinearly extrude 2d shape with extrusion upper and lower scaling\&. \fP"
.ti -1c
.RI "module \fBradial_repeat\fP (n, r=1, angle=true, move=false)"
.br
.RI "\fIDistribute copies of a 2d or 3d shape equally about a z-axis radius\&. \fP"
.ti -1c
.RI "module \fBgrid_repeat\fP (g, i, c=1, center=false)"
.br
.RI "\fIDistribute copies of 2d or 3d shapes about Cartesian grid\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape transformation utility tools\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBtools_utility\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
