.TH "install" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
install \- Installing 

.SH "Prerequisites"
.PP
First install \fCopenscad-amu\fP\&. A build script exists for \fILinux\fP and \fICygwin\fP (pull requests for \fImacos\fP are welcome)\&. If \fCwget\fP is not available, here is a downloadable link to the \fCbootstrap\fP script\&.
.PP
If the last step below reports the tool version, then the install likely completed successfully and the temporary directory may be removed as desired\&. Dependent on your operating system, file system, and/or user credentials, the install may or may not require elevated privileges as indicated by \fCsudo:\fP 
.PP
.PP
.nf
  $ mkdir tmp && cd tmp

  $ wget https://raw.githubusercontent.com/royasutton/openscad-amu/master/snapshots/bootstrap.{bash,conf} .
  $ chmod +x bootstrap.bash

  $ sudo ./bootstrap.bash --yes --install

  $ openscad-seam -v -V.fi
.PP
.PP
More information can be found in the GitHib \fCamu repository\fP, where the source is maintained, and at \fCamu on Thingiverse\fP\&.
.SH "omdl"
.PP
Now \fComdl\fP can be compiled, verified, and installed\&. First download the source from the GitHub \fComdl repository\fP, select the branch version, and start the install as follows:
.PP
.PP
.nf
  $ git clone https://github.com/royasutton/omdl.git
  $ cd omdl
  $ git checkout v0.6.1

  $ make scopes_exclude="manifest" all
  $ make install.fi
.PP
.PP
By default, some things are not built, as controlled by the design flow variable \fCscopes_exclude\fP\&. To build everything, use the following:
.PP
.PP
.nf
  $ make list-scopes_exclude

  $ make scopes_exclude="" all.fi
.PP
.PP
Now the library should have been installed to the OpenSCAD \fIbuilt-in\fP library location along with the documentation that can be views with a web browser\&. Multiple versions can be installed simultaneously\&.
.PP
Have a look in: 
.PD 0

.IP "\(bu" 2
\fBLinux:\fP $HOME/\&.local/share/OpenSCAD/libraries 
.IP "\(bu" 2
\fBWindows:\fP My Documents\\OpenSCAD\\libraries
.PP
You may include the desired library component from your project as follows, replacing the version number as needed:
.PP
.PP
.nf
  include <omdl-v0.6/shapes/shapes2de.scad>;
  include <omdl-v0.6/shapes/shapes3d.scad>;
  ....fi
.PP
.SS "Snapshots"
Library source release \fCsnapshots\fP are periodically made available in the repository and at \fComdl on Thingiverse\fP\&. 
