.TH "constants_general" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants_general \- General
.PP
General design constants\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.scad\fP"
.br
.RI "\fIDesign constant definitions\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBaeps\fP = 0\&.001"
.br
.RI "\fI<decimal> Epsilon, small distance to deal with overlapping shapes\&. \fP"
.ti -1c
.RI "\fBpi\fP = 3\&.14159265358979323"
.br
.RI "\fI<decimal> The ratio of a circle's circumference to its diameter\&. \fP"
.ti -1c
.RI "\fBtau\fP = 2*\fBpi\fP"
.br
.RI "\fI<decimal> The ratio of a circle's circumference to its radius\&. \fP"
.ti -1c
.RI "\fBphi\fP = (1 + sqrt(5)) / 2"
.br
.RI "\fI<decimal> The golden ratio\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
General design constants\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
