.TH "shapes2de.scad" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shapes2de.scad \- Linearly extruded two-dimensional basic shapes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <shapes2d\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBerectangle\fP (size, h, vr, center=false)"
.br
.RI "\fIAn extruded rectangle\&. \fP"
.ti -1c
.RI "module \fBerectangle_c\fP (size, core, h, t, co, cr=0, vr, vr1, vr2, center=false)"
.br
.RI "\fIAn extruded rectangle with a removed rectangular core\&. \fP"
.ti -1c
.RI "module \fBerhombus\fP (size, h, vr, center=false)"
.br
.RI "\fIAn extruded rhombus\&. \fP"
.ti -1c
.RI "module \fBetriangle_ppp\fP (v1, v2, v3, h, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by three vertices\&. \fP"
.ti -1c
.RI "module \fBetriangle_vp\fP (v, h, vr, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by a vector of its three vertices\&. \fP"
.ti -1c
.RI "module \fBetriangle_lll\fP (s1, s2, s3, h, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by its three side lengths\&. \fP"
.ti -1c
.RI "module \fBetriangle_vl\fP (v, h, vr, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by a vector of its three side lengths\&. \fP"
.ti -1c
.RI "module \fBetriangle_vl_c\fP (vs, vc, h, co, cr=0, vr, vr1, vr2, centroid=false, incenter=false, center=false)"
.br
.RI "\fIA general triangle specified by its sides with a removed triangular core\&. \fP"
.ti -1c
.RI "module \fBetriangle_lal\fP (s1, a, s2, h, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by two sides and the included angle\&. \fP"
.ti -1c
.RI "module \fBetriangle_ala\fP (a1, s, a2, h, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by a side and two adjacent angles\&. \fP"
.ti -1c
.RI "module \fBetriangle_aal\fP (a1, a2, s, h, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by a side, one adjacent angle and the opposite angle\&. \fP"
.ti -1c
.RI "module \fBetriangle_ll\fP (x, y, h, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded right-angled triangle specified by its opposite and adjacent side lengths\&. \fP"
.ti -1c
.RI "module \fBetriangle_la\fP (x, y, aa, oa, h, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded right-angled triangle specified by a side length and an angle\&. \fP"
.ti -1c
.RI "module \fBengon\fP (n, r, h, vr, center=false)"
.br
.RI "\fIAn extruded n-sided equiangular/equilateral regular polygon\&. \fP"
.ti -1c
.RI "module \fBeellipse\fP (size, h, center=false)"
.br
.RI "\fIAn extruded ellipse\&. \fP"
.ti -1c
.RI "module \fBeellipse_c\fP (size, core, h, t, co, cr=0, center=false)"
.br
.RI "\fIAn extruded ellipse with a removed elliptical core\&. \fP"
.ti -1c
.RI "module \fBeellipse_s\fP (size, h, a1=0, a2=0, center=false)"
.br
.RI "\fIAn extruded ellipse sector\&. \fP"
.ti -1c
.RI "module \fBeellipse_cs\fP (size, core, h, t, a1=0, a2=0, co, cr=0, center=false)"
.br
.RI "\fIAn extruded sector of an ellipse with a removed elliptical core\&. \fP"
.ti -1c
.RI "module \fBestar2d\fP (size, h, n=5, vr, center=false)"
.br
.RI "\fIAn extruded two dimensional star\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Linearly extruded two-dimensional basic shapes\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBshapes2de\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
