.TH "datatypes_identify" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes_identify \- Identification
.PP
Compile-time data type identification and tests\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBIterables\fP"
.br
.RI "\fIIterable data type identification\&. \fP"
.ti -1c
.RI "\fBLists\fP"
.br
.RI "\fIList data type identification\&. \fP"
.ti -1c
.RI "\fBScalars\fP"
.br
.RI "\fIScalar data type identification\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatatypes\&.scad\fP"
.br
.RI "\fIData type identification and operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_scalar\&.scad\fP"
.br
.RI "\fIScalar data type identification\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_iterable\&.scad\fP"
.br
.RI "\fIIterable data type identification\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_list\&.scad\fP"
.br
.RI "\fIList data type identification\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Compile-time data type identification and tests\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
