.TH "tools_align" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools_align \- Alignment
.PP
Shape alignment tools\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtools_align\&.scad\fP"
.br
.RI "\fIShape alignment tools\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBorient_ll\fP (l=\fBz_axis3d_ul\fP, rl=\fBz_axis3d_ul\fP, r=0)"
.br
.RI "\fIOrient a line or vector to a reference line or vector\&. \fP"
.ti -1c
.RI "module \fBalign_ll\fP (l=\fBz_axis3d_ul\fP, rl=\fBz_axis3d_ul\fP, ap=0, rp=0, r=0, to=\fBorigin3d\fP, ro=\fBzero3d\fP)"
.br
.RI "\fIAlign a line or vector to a reference line or vector\&. \fP"
.ti -1c
.RI "module \fBalign_l\fP (rl=\fBz_axis3d_ul\fP, rp=0, r=0, to=\fBorigin3d\fP, ro=\fBzero3d\fP, d=\fBz_axis_ci\fP)"
.br
.RI "\fIAlign a shapes' x, y, or z Cartesian axis to reference line or vector\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape alignment tools\&. 


.SH "Function Documentation"
.PP 
.SS "module align_l (rl = \fC\fBz_axis3d_ul\fP\fP, rp = \fC0\fP, r = \fC0\fP, to = \fC\fBorigin3d\fP\fP, ro = \fC\fBzero3d\fP\fP, d = \fC\fBz_axis_ci\fP\fP)"

.PP
Align a shapes' x, y, or z Cartesian axis to reference line or vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrl\fP <line-3d|line-2d> The reference line or vector\&.
.br
\fIrp\fP <integer> The reference-line alignment point (see table)\&.
.br
\fIr\fP <decimal> Roll about axis \fCrl\fP (in degrees)\&.
.br
\fIto\fP <vector-3d|vector-2d> Translation offset about \fCrl\fP\&. 
.br
\fIro\fP <decimal-list-1:3|decimal> Rotation offset about \fCrl\fP (in degrees)\&.
.br
\fId\fP <integer> The Cartesian axis index to align (0, 1, or 2)\&.
.RE
.PP
The origin will be a translated to the specified alignment point for the reference line \fCrl\fP\&.
.PP
ap, rp alignment point  0 none (no translation) 1 initial 2 median 3 termination 4 initial + termination See \fBLines and vectors\fP for argument specification and conventions\&. 
.PP
Definition at line 170 of file tools_align\&.scad\&.
.SS "module align_ll (l = \fC\fBz_axis3d_ul\fP\fP, rl = \fC\fBz_axis3d_ul\fP\fP, ap = \fC0\fP, rp = \fC0\fP, r = \fC0\fP, to = \fC\fBorigin3d\fP\fP, ro = \fC\fBzero3d\fP\fP)"

.PP
Align a line or vector to a reference line or vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIl\fP <line-3d|line-2d> The line or vector to align\&. 
.br
\fIrl\fP <line-3d|line-2d> The reference line or vector\&.
.br
\fIap\fP <integer> The line alignment point (see table)\&. 
.br
\fIrp\fP <integer> The reference-line alignment point (see table)\&.
.br
\fIr\fP <decimal> Roll about axis \fCrl\fP (in degrees)\&.
.br
\fIto\fP <vector-3d|vector-2d> Translation offset about \fCrl\fP\&. 
.br
\fIro\fP <decimal-list-1:3|decimal> Rotation offset about \fCrl\fP (in degrees)\&.
.RE
.PP
The specified alignment point for the line \fCl\fP will be a translated to the specified alignment point for the reference line \fCrl\fP\&.
.PP
ap, rp alignment point  0 none (no translation) 1 initial 2 median 3 termination 4 initial + termination See \fBLines and vectors\fP for argument specification and conventions\&. 
.PP
Definition at line 102 of file tools_align\&.scad\&.
.SS "module orient_ll (l = \fC\fBz_axis3d_ul\fP\fP, rl = \fC\fBz_axis3d_ul\fP\fP, r = \fC0\fP)"

.PP
Orient a line or vector to a reference line or vector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIl\fP <line-3d|line-2d> The line or vector to align\&. 
.br
\fIrl\fP <line-3d|line-2d> The reference line or vector\&.
.br
\fIr\fP <decimal> Roll about axis \fCrl\fP (in degrees)\&.
.RE
.PP
See \fBLines and vectors\fP for argument specification and conventions\&. 
.PP
Definition at line 58 of file tools_align\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
