.TH "database_polyhedra" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database_polyhedra \- Polyhedra
.PP
Tables of polyhedra vertices, faces, and edges\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBanti_prisms\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCanti_prisms\fP\&. \fP"
.ti -1c
.RI "file \fBarchimedean_duals\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCarchimedean_duals\fP\&. \fP"
.ti -1c
.RI "file \fBarchimedean\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCarchimedean\fP\&. \fP"
.ti -1c
.RI "file \fBcupolas\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCcupolas\fP\&. \fP"
.ti -1c
.RI "file \fBdipyramids\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCdipyramids\fP\&. \fP"
.ti -1c
.RI "file \fBjohnson\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCjohnson\fP\&. \fP"
.ti -1c
.RI "file \fBplatonic\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCplatonic\fP\&. \fP"
.ti -1c
.RI "file \fBprisms\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCprisms\fP\&. \fP"
.ti -1c
.RI "file \fBpyramids\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCpyramids\fP\&. \fP"
.ti -1c
.RI "file \fBtrapezohedron\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCtrapezohedron\fP\&. \fP"
.ti -1c
.RI "file \fBpolyhedra_all\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCpolyhedra_all\fP\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdtc_polyhedra_anti_prisms\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_anti_prisms\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_archimedean_duals\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_archimedean_duals\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_archimedean\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_archimedean\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_cupolas\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_cupolas\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_dipyramids\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_dipyramids\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_johnson\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_johnson\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_platonic\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_platonic\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_prisms\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_prisms\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_pyramids\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_pyramids\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_trapezohedron\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_trapezohedron\fP"
.br
.ti -1c
.RI "\fBdtc_polyhedra_polyhedra_all\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_polyhedra_all\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tables of polyhedra vertices, faces, and edges\&. 

Database of polyhedra vertices, faces, and edges\&. Classes of polyhedra are grouped into separate files\&. The file \fBpolyhedra_all\&.scad\fP contains all polyhedra from all files\&. Each table uses the following column data structure\&.
.PP
feild description  id identifier n name o other name g group d data source c cartesian vertices s spherical vertices f faces e edges Use the functions \fBget_table_v()\fP to retrieve feild data as show in the following example\&. To see a list of table identifiers consider the function \fBget_table_ridl()\fP, \fBget_table_cidl()\fP, or module \fBtable_dump()\fP\&. See \fBdatatypes_table\&.scad\fP for other available table functions\&.
.PP
\fBExample\fP 
.PP
.nf
include <units/units_coordinate\&.scad>;
include <tools/tools_polytope\&.scad>;
include <datatypes/datatypes_table\&.scad>;
include <database/geometry/polyhedra/platonic\&.scad>;

tc = dtc_polyhedra_platonic;
tr = dtr_polyhedra_platonic;

id = "dodecahedron";

pv = get_table_v(tr, tc, id, "c");
pf = get_table_v(tr, tc, id, "f");

sv = coordinates_csc(pv, 100);

polytope_number(sv, pf, to=[0,0,5]);
polytope_frame(sv, pf) {circle(r=2); color("grey") sphere(r=4);}
polyhedron(sv, pf);

.fi
.PP
.PP
\fBAutotests\fP 
.PP
.nf
1 ECHO: "checking table: "
2 ECHO: "colums = dtc_polyhedra_polyhedra_all"
3 ECHO: "  rows = dtr_polyhedra_polyhedra_all"
4 ECHO: "[ INFO ] table_check(); begin table check"
5 ECHO: "[ INFO ] table_check(); row identifier found at column zero\&."
6 ECHO: "[ INFO ] table_check(); checking row column counts\&."
7 ECHO: "[ INFO ] table_check(); checking for repeat column identifiers\&."
8 ECHO: "[ INFO ] table_check(); checking for repeat row identifiers\&."
9 ECHO: "[ INFO ] table_check(); table size: 164 rows by 9 columns\&."
10 ECHO: "[ INFO ] table_check(); end table check"
11 ECHO: 
12 ECHO: "confirming calculations stored in table:"
13 ECHO: "  (1) spherical with converted cartesian coordinates:"
14 ECHO: "  (2) edge list from faces definition:"
15 ECHO: "[ INFO ] root(); edge-list not sorted: id=anti_prisms_triangular_antiprism"
16 ECHO: "[ INFO ] root(); edge-list not sorted: id=archimedean_duals_rhombic_dodecahedron"
17 ECHO: "[ INFO ] root(); edge-list not sorted: id=archimedean_cuboctahedron"
18 ECHO: "[ INFO ] root(); edge-list not sorted: id=cupolas_triangular_gyrobicupola"
19 ECHO: "[ INFO ] root(); edge-list not sorted: id=platonic_octahedron"
20 ECHO: 
21 ECHO: "164 polyhedra checked\&."

.fi
.PP
.PP
For more information see Wikipedia on \fCPolyhedron\fP\&.
.PP

.br
 
.SS "Group: anti_prisms"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1decagonal_antiprism-2022403\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
35\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
84\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
95\&.2\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.597\fI\*{x\*} \fP\fB\*{40\*} \fP36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP2hexagonal_antiprism-1214243\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{2\*} \fP34\&.8\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
59\&.2\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
81\&.1\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
98\&.9\fI\*{x\*} \fP\fB\*{24\*} \fP0\&.919\fI\*{x\*} \fP\fB\*{24\*} \fP60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{36\*} \fP3octagonal_antiprism-1618323\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{2\*} \fP26\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
44\&.7\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
83\&.4\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
96\&.6\fI\*{x\*} \fP\fB\*{32\*} \fP0\&.727\fI\*{x\*} \fP\fB\*{32\*} \fP45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{48\*} \fP4pentagonal_antiprism-1012203\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
100\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP1\&.05\fI\*{x\*} \fP\fB\*{20\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP5square_antiprism-810163\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{2\*} \fP52\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
76\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
86\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
103\&.8\fI\*{x\*} \fP\fB\*{16\*} \fP1\&.22\fI\*{x\*} \fP\fB\*{16\*} \fP90\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP6triangular_antiprismOctahedron68123\fI\*{x\*} \fP\fB\*{8\*} \fP70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.41\fI\*{x\*} \fP\fB\*{12\*} \fP120\fI\*{x\*} \fP\fB\*{24\*} \fP
.PP

.br
 
.SS "Group: archimedean_duals"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1disdyakis_dodecahedronHexakis-Octahedron2648723\fI\*{x\*} \fP\fB\*{48\*} \fP6\&.9\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
32\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
38\&.2\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
43\&.1\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
47\&.3\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
50\&.6\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
54\&.6\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
55\&.1\fI\*{x\*} \fP\fB\*{96\*} \fP0\&.606\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
0\&.765\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
0\&.919\fI\*{x\*} \fP\fB\*{24\*} \fP96\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
124\&.2\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
139\&.1\fI\*{x\*} \fP\fB\*{48\*} \fP2disdyakis_triacontahedronHexakis-Icosahedron621201803\fI\*{x\*} \fP\fB\*{120\*} \fP15\&.1\fI\*{x\*} \fP\fB\*{360\*} \fP, 
.br
21\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
26\&.3\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
29\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
30\&.5\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
40\&.3\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
47\&.7\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
50\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP0\&.37\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
0\&.581\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
0\&.683\fI\*{x\*} \fP\fB\*{60\*} \fP91\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
121\&.8\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
147\&.2\fI\*{x\*} \fP\fB\*{120\*} \fP3kite_hexecontahedron-62601204\fI\*{x\*} \fP\fB\*{60\*} \fP25\&.9\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
36\&.9\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
42\&.5\fI\*{x\*} \fP\fB\*{120\*} \fP0\&.37\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
0\&.569\fI\*{x\*} \fP\fB\*{60\*} \fP61\&.7\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
93\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
112\&.2\fI\*{x\*} \fP\fB\*{60\*} \fP4kite_icositetrahedron-2624484\fI\*{x\*} \fP\fB\*{24\*} \fP41\&.9\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
60\&.7\fI\*{x\*} \fP\fB\*{72\*} \fP0\&.592\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
0\&.765\fI\*{x\*} \fP\fB\*{24\*} \fP64\&.7\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
98\&.4\fI\*{x\*} \fP\fB\*{72\*} \fP5pentagonal_hexecontahedron-92601505\fI\*{x\*} \fP\fB\*{60\*} \fP26\&.8\fI\*{x\*} \fP\fB\*{300\*} \fP, 
.br
44\&.1\fI\*{x\*} \fP\fB\*{120\*} \fP0\&.278\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
0\&.486\fI\*{x\*} \fP\fB\*{60\*} \fP61\&.9\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
112\&.5\fI\*{x\*} \fP\fB\*{60\*} \fP6pentagonal_icositetrahedron-3824605\fI\*{x\*} \fP\fB\*{24\*} \fP43\&.7\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
63\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP0\&.436\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
0\&.619\fI\*{x\*} \fP\fB\*{24\*} \fP65\&.2\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
99\&.2\fI\*{x\*} \fP\fB\*{24\*} \fP7pentakis_dodecahedron-3260903\fI\*{x\*} \fP\fB\*{60\*} \fP23\&.3\fI\*{x\*} \fP\fB\*{180\*} \fP, 
.br
38\&.1\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
40\&.9\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
47\&.6\fI\*{x\*} \fP\fB\*{120\*} \fP0\&.678\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
0\&.764\fI\*{x\*} \fP\fB\*{30\*} \fP111\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
124\&.3\fI\*{x\*} \fP\fB\*{120\*} \fP8rhombic_dodecahedron-1412244\fI\*{x\*} \fP\fB\*{12\*} \fP60\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP0\&.866\fI\*{x\*} \fP\fB\*{24\*} \fP70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP9rhombic_triacontahedron-3230604\fI\*{x\*} \fP\fB\*{30\*} \fP36\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{120\*} \fP0\&.691\fI\*{x\*} \fP\fB\*{60\*} \fP63\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{60\*} \fP10tetrakis_hexahedron-1424363\fI\*{x\*} \fP\fB\*{24\*} \fP36\&.9\fI\*{x\*} \fP\fB\*{72\*} \fP, 
.br
53\&.1\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
66\&.4\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
78\&.5\fI\*{x\*} \fP\fB\*{48\*} \fP1\&.06\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
1\&.41\fI\*{x\*} \fP\fB\*{12\*} \fP96\&.4\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
131\&.8\fI\*{x\*} \fP\fB\*{48\*} \fP11triakis_icosahedron-3260903\fI\*{x\*} \fP\fB\*{60\*} \fP19\&.4\fI\*{x\*} \fP\fB\*{180\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
52\&.3\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
62\&.4\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
66\fI\*{x\*} \fP\fB\*{120\*} \fP0\&.717\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
1\&.24\fI\*{x\*} \fP\fB\*{30\*} \fP61\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
149\&.5\fI\*{x\*} \fP\fB\*{120\*} \fP12triakis_octahedron-1424363\fI\*{x\*} \fP\fB\*{24\*} \fP32\&.6\fI\*{x\*} \fP\fB\*{72\*} \fP, 
.br
62\&.6\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
85\&.5\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
94\&.5\fI\*{x\*} \fP\fB\*{48\*} \fP1\&.17\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
2\fI\*{x\*} \fP\fB\*{12\*} \fP62\&.8\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
148\&.6\fI\*{x\*} \fP\fB\*{48\*} \fP13triakis_tetrahedron-812183\fI\*{x\*} \fP\fB\*{12\*} \fP50\&.5\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
95\&.2\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
117\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.7\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
2\&.83\fI\*{x\*} \fP\fB\*{6\*} \fP67\&.1\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
146\&.4\fI\*{x\*} \fP\fB\*{24\*} \fP
.PP

.br
 
.SS "Group: archimedean"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1cuboctahedron-1214243\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{6\*} \fP54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.41\fI\*{x\*} \fP\fB\*{24\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP2icosidodecahedron-3032603\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP0\&.65\fI\*{x\*} \fP\fB\*{60\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP3rhombicosidodecahedron-60621203\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP0\&.46\fI\*{x\*} \fP\fB\*{120\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP4rhombicuboctahedron-2426483\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{18\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{48\*} \fP0\&.765\fI\*{x\*} \fP\fB\*{48\*} \fP90\fI\*{x\*} \fP\fB\*{72\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP5snub_cuboctahedron-2438603\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{6\*} \fP26\&.8\fI\*{x\*} \fP\fB\*{72\*} \fP, 
.br
37\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
45\&.9\fI\*{x\*} \fP\fB\*{96\*} \fP, 
.br
50\&.4\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{96\*} \fP0\&.802\fI\*{x\*} \fP\fB\*{60\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{96\*} \fP6snub_icosidodecahedronSnub Dodecahedron60921503\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP15\&.8\fI\*{x\*} \fP\fB\*{180\*} \fP, 
.br
27\&.1\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
27\&.3\fI\*{x\*} \fP\fB\*{240\*} \fP, 
.br
31\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{240\*} \fP0\&.477\fI\*{x\*} \fP\fB\*{150\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{240\*} \fP7truncated_cube-2414363\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{6\*} \fP54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP0\&.586\fI\*{x\*} \fP\fB\*{36\*} \fP45\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP8truncated_cuboctahedronGreat Rhombicuboctahedron4826724\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{6\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP0\&.442\fI\*{x\*} \fP\fB\*{72\*} \fP45\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{48\*} \fP9truncated_dodecahedron-6032903\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{12\*} \fP37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP0\&.342\fI\*{x\*} \fP\fB\*{90\*} \fP36\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP10truncated_icosahedronSoccer Ball6032905\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{20\*} \fP37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{60\*} \fP0\&.412\fI\*{x\*} \fP\fB\*{90\*} \fP60\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{60\*} \fP11truncated_icosidodecahedronGreat Rhombicosidodecahedron120621804\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{12\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP0\&.265\fI\*{x\*} \fP\fB\*{180\*} \fP36\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{120\*} \fP12truncated_octahedron-2414364\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{8\*} \fP54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.41\fI\*{x\*} \fP\fB\*{36\*} \fP60\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP13truncated_tetrahedron-128183\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{4\*} \fP70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP2\&.83\fI\*{x\*} \fP\fB\*{18\*} \fP60\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP
.PP

.br
 
.SS "Group: cupolas"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1pentagonal_cupolaJ51512253\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
142\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
148\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.614\fI\*{x\*} \fP\fB\*{25\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP2pentagonal_gyrobicupolaJ312022403\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
110\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.618\fI\*{x\*} \fP\fB\*{40\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP3pentagonal_orthobicupolaJ302022403\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
105\&.2\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
114\&.7\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.618\fI\*{x\*} \fP\fB\*{40\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP4square_cupolaJ41210203\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{1\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
125\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
135\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.753\fI\*{x\*} \fP\fB\*{20\*} \fP45\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP5square_gyrobicupolaJ291618323\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
80\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
82\&.1\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
98\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.765\fI\*{x\*} \fP\fB\*{32\*} \fP90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP6square_orthobicupolaJ281618323\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.765\fI\*{x\*} \fP\fB\*{32\*} \fP90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP7triangular_cupolaJ398153\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{1\*} \fP54\&.7\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
125\&.3\fI\*{x\*} \fP\fB\*{6\*} \fP0\&.965\fI\*{x\*} \fP\fB\*{15\*} \fP60\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP8triangular_gyrobicupolaCuboctahedron1214243\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{6\*} \fP54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP1\fI\*{x\*} \fP\fB\*{24\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP9triangular_orthobicupolaJ271214243\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{6\*} \fP38\&.9\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
78\&.9\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP1\fI\*{x\*} \fP\fB\*{24\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP
.PP

.br
 
.SS "Group: dipyramids"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1decagonal_bi_pyramid-1220303\fI\*{x\*} \fP\fB\*{20\*} \fP34\&.3\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
49\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
68\&.3\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
101\&.2\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
130\&.6\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
145\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.201\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
1\&.05\fI\*{x\*} \fP\fB\*{20\*} \fP95\&.5\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
169\fI\*{x\*} \fP\fB\*{20\*} \fP2hexagonal_bi_pyramid-812183\fI\*{x\*} \fP\fB\*{12\*} \fP53\&.1\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
78\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
101\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
126\&.9\fI\*{x\*} \fP\fB\*{12\*} \fP0\&.577\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
1\&.15\fI\*{x\*} \fP\fB\*{12\*} \fP104\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
151\fI\*{x\*} \fP\fB\*{12\*} \fP3octagonal_di_pyramid-1016243\fI\*{x\*} \fP\fB\*{16\*} \fP41\&.9\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
60\&.7\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
82\&.7\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
119\&.3\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
138\&.1\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.317\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
1\&.08\fI\*{x\*} \fP\fB\*{16\*} \fP98\&.4\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
163\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP4pentagonal_di_pyramid-710153\fI\*{x\*} \fP\fB\*{10\*} \fP60\&.9\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
91\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
110\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.854\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
1\&.24\fI\*{x\*} \fP\fB\*{10\*} \fP110\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
139\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP5square_di_pyramidOctahedron68123\fI\*{x\*} \fP\fB\*{8\*} \fP70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.41\fI\*{x\*} \fP\fB\*{12\*} \fP120\fI\*{x\*} \fP\fB\*{24\*} \fP6triangular_di_pyramid-5693\fI\*{x\*} \fP\fB\*{6\*} \fP81\&.8\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
135\&.6\fI\*{x\*} \fP\fB\*{12\*} \fP1\&.15\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
1\&.73\fI\*{x\*} \fP\fB\*{3\*} \fP82\&.8\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
138\&.6\fI\*{x\*} \fP\fB\*{12\*} \fP
.PP

.br
 
.SS "Group: johnson"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1augmented_dodecahedronJ582116353\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{11\*} \fP26\&.1\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
58\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.641\fI\*{x\*} \fP\fB\*{35\*} \fP72\fI\*{x\*} \fP\fB\*{55\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP2augmented_hexagonal_prismJ541311223\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{2\*} \fP5\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
73\&.2\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{28\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP0\&.689\fI\*{x\*} \fP\fB\*{22\*} \fP60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP3augmented_pentagonal_prismJ521110193\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP17\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
79\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP0\&.788\fI\*{x\*} \fP\fB\*{19\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP4augmented_sphenocoronaJ871117263\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{1\*} \fP8\&.2\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
15\&.7\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
20\&.1\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
27\&.8\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
31\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
36\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
44\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
48\&.6\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
61\&.1\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
61\&.7\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
62\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
68\&.2\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
69\&.7\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
70\&.7\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
72\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
74\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
74\&.8\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
78\&.9\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
81\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
82\&.5\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
82\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
85\&.7\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
87\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
104\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP0\&.858\fI\*{x\*} \fP\fB\*{26\*} \fP90\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{48\*} \fP5augmented_triangular_prismJ4978133\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{2\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
65\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
106\&.8\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{2\*} \fP1\&.14\fI\*{x\*} \fP\fB\*{13\*} \fP90\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{18\*} \fP6augmented_tridiminished_icosahedronJ641010183\fI\*{x\*} \fP\fB\*{7\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{3\*} \fP8\&.7\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
100\&.8\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
113\&.6\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{6\*} \fP0\&.976\fI\*{x\*} \fP\fB\*{18\*} \fP72\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{21\*} \fP7augmented_truncated_cubeJ662822483\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{5\*} \fP9\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
36\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.506\fI\*{x\*} \fP\fB\*{48\*} \fP45\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{36\*} \fP8augmented_truncated_dodecahedronJ6865421053\fI\*{x\*} \fP\fB\*{25\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{11\*} \fP5\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
21\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{50\*} \fP0\&.316\fI\*{x\*} \fP\fB\*{105\*} \fP36\fI\*{x\*} \fP\fB\*{110\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{75\*} \fP9augmented_truncated_tetrahedronJ651514273\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{3\*} \fP15\&.8\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
38\&.9\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
56\&.3\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
78\&.9\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP0\&.7\fI\*{x\*} \fP\fB\*{27\*} \fP60\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP10biaugmented_pentagonal_prismJ531213233\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP17\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
79\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{28\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.727\fI\*{x\*} \fP\fB\*{23\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP11biaugmented_triangular_prismJ50811173\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{1\*} \fP10\&.5\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
65\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
76\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
106\&.8\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP1\&.06\fI\*{x\*} \fP\fB\*{17\*} \fP90\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP12biaugmented_truncated_cubeJ673230603\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{4\*} \fP9\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
36\&.4\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.49\fI\*{x\*} \fP\fB\*{60\*} \fP45\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{48\*} \fP13bigyrate_diminished_rhombicosidodecahedronJ7955521053\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{25\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{11\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{70\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
33\&.3\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.423\fI\*{x\*} \fP\fB\*{105\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{55\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP14bilunabirotundaJ911414263\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{4\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
69\&.1\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{4\*} \fP0\&.714\fI\*{x\*} \fP\fB\*{26\*} \fP72\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP15diminished_rhombicosidodecahedronJ7655521053\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{25\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{11\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.423\fI\*{x\*} \fP\fB\*{105\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{55\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP16disphenocingulumJ901624383\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{4\*} \fP13\&.2\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
25\&.6\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
31\&.6\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
39\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
43\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
46\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
49\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
53\&.9\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
55\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
62\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
64\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
66\&.6\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
74\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
77\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
79\&.8\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
82\&.6\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.825\fI\*{x\*} \fP\fB\*{38\*} \fP90\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP17elongated_pentagonal_cupolaJ202522453\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
52\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
60\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
64\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.567\fI\*{x\*} \fP\fB\*{45\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP18elongated_pentagonal_dipyramidJ161215253\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
52\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.975\fI\*{x\*} \fP\fB\*{25\*} \fP90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP19elongated_pentagonal_gyrobicupolaJ393032603\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
52\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
60\&.6\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
64\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.59\fI\*{x\*} \fP\fB\*{60\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP20elongated_pentagonal_gyrobirotundaJ434042803\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP10\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{140\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
43\&.6\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.485\fI\*{x\*} \fP\fB\*{80\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP21elongated_pentagonal_gyrocupolarotundaJ413537703\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{7\*} \fP10\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
43\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
52\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
60\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
64\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.552\fI\*{x\*} \fP\fB\*{70\*} \fP72\fI\*{x\*} \fP\fB\*{35\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP22elongated_pentagonal_orthobicupolaJ383032603\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
52\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
60\&.6\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
64\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.59\fI\*{x\*} \fP\fB\*{60\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP23elongated_pentagonal_orthobirotundaJ424042803\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP10\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{140\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
43\&.6\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.485\fI\*{x\*} \fP\fB\*{80\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP24elongated_pentagonal_orthocupolarotundaJ403537703\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{7\*} \fP10\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
43\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
52\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
60\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
64\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.552\fI\*{x\*} \fP\fB\*{70\*} \fP72\fI\*{x\*} \fP\fB\*{35\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP25elongated_pentagonal_pyramidJ91111203\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
52\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.964\fI\*{x\*} \fP\fB\*{20\*} \fP72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP26elongated_pentagonal_rotundsJ213027553\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP10\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{70\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
43\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.52\fI\*{x\*} \fP\fB\*{55\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP27elongated_square_cupolaJ192018363\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{13\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{1\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.666\fI\*{x\*} \fP\fB\*{36\*} \fP45\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{52\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP28elongated_square_dipyramidJ151012203\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{4\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.828\fI\*{x\*} \fP\fB\*{20\*} \fP90\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP29elongated_square_gyrobicupolaJ372426483\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{18\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{48\*} \fP0\&.715\fI\*{x\*} \fP\fB\*{48\*} \fP90\fI\*{x\*} \fP\fB\*{72\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP30elongated_square_pyramidJ899163\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP0\&.932\fI\*{x\*} \fP\fB\*{16\*} \fP90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP31elongated_triangular_cupolaJ181514273\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{9\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{1\*} \fP19\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
61\&.9\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
65\&.9\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{18\*} \fP0\&.795\fI\*{x\*} \fP\fB\*{27\*} \fP60\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP32elongated_triangular_dipyramidJ1489153\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP19\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
118\&.1\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{6\*} \fP0\&.76\fI\*{x\*} \fP\fB\*{15\*} \fP90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{18\*} \fP33elongated_triangular_gyrobicupolaJ361820363\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{12\*} \fP19\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
61\&.9\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
65\&.9\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP0\&.696\fI\*{x\*} \fP\fB\*{36\*} \fP90\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP34elongated_triangular_orthobicupolaJ351820363\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{12\*} \fP19\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
61\&.9\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
65\&.9\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP0\&.696\fI\*{x\*} \fP\fB\*{36\*} \fP90\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP35elongated_triangular_pyramidJ777123\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP19\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
118\&.1\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{6\*} \fP0\&.886\fI\*{x\*} \fP\fB\*{12\*} \fP90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP36gyrate_bidiminished_rhombicosidodecahedronJ825042903\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{70\*} \fP, 
.br
33\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.41\fI\*{x\*} \fP\fB\*{90\*} \fP36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP37gyrate_rhombicosidodecahedronJ7260621203\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{110\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{110\*} \fP, 
.br
33\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.448\fI\*{x\*} \fP\fB\*{120\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP38gyrobifastigiumJ2688143\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{4\*} \fP30\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
104\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{4\*} \fP1\fI\*{x\*} \fP\fB\*{14\*} \fP90\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP39gyroelongated_pentagonal_bicupolaJ463042703\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
35\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
47\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
53\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
55\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
59\&.9\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
65\&.2\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.597\fI\*{x\*} \fP\fB\*{70\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{90\*} \fP40gyroelongated_pentagonal_birotundaJ484052903\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP5\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
20\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
21\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
24\&.1\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
35\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\&.1\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\&.3\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
40\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.501\fI\*{x\*} \fP\fB\*{90\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{120\*} \fP41gyroelongated_pentagonal_cupolaJ242532553\fI\*{x\*} \fP\fB\*{25\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
35\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
47\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
53\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
55\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
59\&.8\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
59\&.9\fI\*{x\*} \fP\fB\*{28\*} \fP, 
.br
65\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
84\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
95\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.577\fI\*{x\*} \fP\fB\*{55\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{75\*} \fP42gyroelongated_pentagonal_cupolarotundaJ473547803\fI\*{x\*} \fP\fB\*{35\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{7\*} \fP5\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
20\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
21\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
24\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
35\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
40\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
47\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
53\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
55\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
59\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
65\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.563\fI\*{x\*} \fP\fB\*{80\*} \fP72\fI\*{x\*} \fP\fB\*{35\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{105\*} \fP43gyroelongated_pentagonal_pyramidJ111116253\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{70\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
100\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP1\&.01\fI\*{x\*} \fP\fB\*{25\*} \fP72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP44gyroelongated_pentagonal_rotundaJ253037653\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP5\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
20\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
21\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
24\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
35\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
40\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
84\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
95\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.591\fI\*{x\*} \fP\fB\*{65\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{90\*} \fP45gyroelongated_square_bicupolaJ452434563\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP26\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
28\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
38\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
44\&.7\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
46\&.9\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
50\&.2\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
55\&.4\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.727\fI\*{x\*} \fP\fB\*{56\*} \fP90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{72\*} \fP46gyroelongated_square_cupolaJ232026443\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{1\*} \fP26\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
28\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
38\&.4\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
44\&.7\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
46\&.9\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
50\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
55\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
83\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
96\&.6\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.741\fI\*{x\*} \fP\fB\*{44\*} \fP45\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP47gyroelongated_square_dipyramidJ171016243\fI\*{x\*} \fP\fB\*{16\*} \fP21\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
52\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
65\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
82\&.1\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
86\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.887\fI\*{x\*} \fP\fB\*{24\*} \fP120\fI\*{x\*} \fP\fB\*{48\*} \fP48gyroelongated_square_pyramidJ10913203\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{1\*} \fP21\&.4\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
52\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
65\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
76\&.2\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
82\&.1\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
86\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
103\&.8\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP0\&.998\fI\*{x\*} \fP\fB\*{20\*} \fP90\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{36\*} \fP49gyroelongated_triangular_bicupolaJ441826423\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{6\*} \fP10\&.6\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
26\&.4\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
34\&.8\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
41\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
52\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
58\&.8\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
59\&.2\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
60\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP0\&.729\fI\*{x\*} \fP\fB\*{42\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP50gyroelongated_triangular_cupolaJ221520333\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{1\*} \fP10\&.6\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
26\&.4\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
34\&.8\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
41\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
52\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
58\&.8\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
59\&.2\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
60\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
81\&.1\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
98\&.9\fI\*{x\*} \fP\fB\*{12\*} \fP0\&.891\fI\*{x\*} \fP\fB\*{33\*} \fP60\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{48\*} \fP51hebesphenomegacoronaJ891421333\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP22\&.9\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
27\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
30\&.4\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
38\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
39\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
46\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
51\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
51\&.8\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
53\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
56\&.4\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
65\&.1\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
65\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
68\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
70\&.2\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
76\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
77\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
80\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
81\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
85\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.889\fI\*{x\*} \fP\fB\*{33\*} \fP90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{54\*} \fP52metabiaugmented_dodecahedronJ602220403\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{10\*} \fP26\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
58\&.5\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.625\fI\*{x\*} \fP\fB\*{40\*} \fP72\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP53metabiaugmented_hexagonal_prismJ561414263\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{2\*} \fP5\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
73\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.658\fI\*{x\*} \fP\fB\*{26\*} \fP60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP54metabiaugmented_truncated_dodecahedronJ7070521203\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{10\*} \fP5\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
21\&.6\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.313\fI\*{x\*} \fP\fB\*{120\*} \fP36\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{90\*} \fP55metabidiminished_icosahedronJ621012203\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{22\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
100\&.8\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{2\*} \fP0\&.964\fI\*{x\*} \fP\fB\*{20\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP56metabidiminished_rhombicosidodecahedronJ815042903\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.41\fI\*{x\*} \fP\fB\*{90\*} \fP36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP57metabigyrate_rhombicosidodecahedronJ7460621203\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
33\&.3\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.448\fI\*{x\*} \fP\fB\*{120\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP58metagyrate_diminished_rhombicosidodecahedronJ7855521053\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{25\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{11\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
33\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{70\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{70\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.423\fI\*{x\*} \fP\fB\*{105\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{55\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP59parabiaugmented_dodecahedronJ592220403\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{10\*} \fP26\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
58\&.5\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.61\fI\*{x\*} \fP\fB\*{40\*} \fP72\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP60parabiaugmented_hexagonal_prismJ551414263\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{2\*} \fP5\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
73\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.636\fI\*{x\*} \fP\fB\*{26\*} \fP60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP61parabiaugmented_truncated_dodecahedronJ6970521203\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{10\*} \fP5\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
21\&.6\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.319\fI\*{x\*} \fP\fB\*{120\*} \fP36\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{90\*} \fP62parabidiminished_rhombicosidodecahedronJ805042903\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.448\fI\*{x\*} \fP\fB\*{90\*} \fP36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP63parabigyrate_rhombicosidodecahedronJ7360621203\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
33\&.3\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.448\fI\*{x\*} \fP\fB\*{120\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP64paragyrate_diminished_rhombicosidodecahedronJ7755521053\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{25\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{11\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
33\&.3\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{70\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{70\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.423\fI\*{x\*} \fP\fB\*{105\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{55\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP65pentagonal_cupolaJ51512253\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
142\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
148\&.3\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.614\fI\*{x\*} \fP\fB\*{25\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP66pentagonal_dipyramidJ13710153\fI\*{x\*} \fP\fB\*{10\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
105\&.2\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
121\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP1\&.18\fI\*{x\*} \fP\fB\*{15\*} \fP120\fI\*{x\*} \fP\fB\*{30\*} \fP67pentagonal_gyrobicupolaJ312022403\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
110\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.618\fI\*{x\*} \fP\fB\*{40\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP68pentagonal_gyrocupolarotundaJ332527503\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{7\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
75\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
84\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
85\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.605\fI\*{x\*} \fP\fB\*{50\*} \fP72\fI\*{x\*} \fP\fB\*{35\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP69pentagonal_orthobicupolaJ302022403\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
105\&.2\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
114\&.7\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.618\fI\*{x\*} \fP\fB\*{40\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP70pentagonal_orthobirotundaJ343032603\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP21\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{100\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
51\&.2\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
53\&.1\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.618\fI\*{x\*} \fP\fB\*{60\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP71pentagonal_orthocupolarontundaJ322527503\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{7\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
69\&.1\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.605\fI\*{x\*} \fP\fB\*{50\*} \fP72\fI\*{x\*} \fP\fB\*{35\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP72pentagonal_pyramidJ266103\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
142\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP1\&.17\fI\*{x\*} \fP\fB\*{10\*} \fP72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP73pentagonal_rotundaJ62017353\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{1\*} \fP37\&.4\fI\*{x\*} \fP\fB\*{50\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
100\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP0\&.584\fI\*{x\*} \fP\fB\*{35\*} \fP36\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{30\*} \fP74snub_disphenoidJ84812183\fI\*{x\*} \fP\fB\*{12\*} \fP13\&.5\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
13\&.6\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
58\&.2\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
65\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
83\&.8\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\&.6\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
90\&.7\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
94\&.9\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
111\&.5\fI\*{x\*} \fP\fB\*{16\*} \fP1\&.08\fI\*{x\*} \fP\fB\*{18\*} \fP120\fI\*{x\*} \fP\fB\*{36\*} \fP75snub_square_antiprismJ851626403\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{2\*} \fP15\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
34\&.6\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
35\&.9\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
45\&.5\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
47\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
59\&.9\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
61\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
65\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
73\&.9\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
85\&.9\fI\*{x\*} \fP\fB\*{32\*} \fP0\&.815\fI\*{x\*} \fP\fB\*{40\*} \fP90\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{72\*} \fP76sphenocoronaJ861014223\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{2\*} \fP20\&.1\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
36\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
44\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
48\&.6\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
61\&.1\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
62\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
63\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
68\&.2\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
72\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
74\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
81\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
82\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
82\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
87\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
104\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP1\fI\*{x\*} \fP\fB\*{22\*} \fP90\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{36\*} \fP77sphenomegacoronaJ881218283\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{2\*} \fP8\&.3\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
8\&.4\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
18\&.6\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
25\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
36\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
41\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
42\&.8\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
48\&.4\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
50\&.6\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
55\&.1\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
61\&.6\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
62\&.6\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
62\&.7\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
65\&.8\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
67\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
67\&.1\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
72\&.8\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
72\&.9\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
83\&.8\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
93\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
97\&.4\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
100\&.6\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
105\&.4\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
107\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
114\&.9\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.761\fI\*{x\*} \fP\fB\*{26\*} \fP, 
.br
0\&.762\fI\*{x\*} \fP\fB\*{2\*} \fP90\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{48\*} \fP78square_cupolaJ41210203\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{1\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
125\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
135\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.753\fI\*{x\*} \fP\fB\*{20\*} \fP45\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP79square_gyrobicupolaJ291618323\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
80\&.3\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
82\&.1\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
98\&.4\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.765\fI\*{x\*} \fP\fB\*{32\*} \fP90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP80square_orthobicupolaJ281618323\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{10\*} \fP35\&.3\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.765\fI\*{x\*} \fP\fB\*{32\*} \fP90\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP81square_pyramidJ15583\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{1\*} \fP70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
125\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP1\&.41\fI\*{x\*} \fP\fB\*{8\*} \fP90\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP82triangular_cupolaJ398153\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{1\*} \fP54\&.7\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
125\&.3\fI\*{x\*} \fP\fB\*{6\*} \fP0\&.965\fI\*{x\*} \fP\fB\*{15\*} \fP60\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP83triangular_dipyramidJ125693\fI\*{x\*} \fP\fB\*{6\*} \fP38\&.9\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
123\&.7\fI\*{x\*} \fP\fB\*{12\*} \fP1\&.22\fI\*{x\*} \fP\fB\*{9\*} \fP120\fI\*{x\*} \fP\fB\*{18\*} \fP84triangular_hebesphenorotundaJ921820363\fI\*{x\*} \fP\fB\*{13\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{1\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
69\&.1\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
100\&.8\fI\*{x\*} \fP\fB\*{6\*} \fP0\&.661\fI\*{x\*} \fP\fB\*{36\*} \fP60\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{39\*} \fP85triangular_orthobicupolaJ271214243\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{6\*} \fP38\&.9\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
54\&.7\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
78\&.9\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP1\fI\*{x\*} \fP\fB\*{24\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{24\*} \fP86triaugmented_dodecahedronJ612324453\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{9\*} \fP26\&.1\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
41\&.8\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
58\&.5\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{30\*} \fP0\&.613\fI\*{x\*} \fP\fB\*{45\*} \fP72\fI\*{x\*} \fP\fB\*{45\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{45\*} \fP87triaugmented_hexagonal_prismJ571517303\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{2\*} \fP5\&.3\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
73\&.2\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP0\&.636\fI\*{x\*} \fP\fB\*{30\*} \fP60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{36\*} \fP88triaugmented_triangular_prismJ51914213\fI\*{x\*} \fP\fB\*{14\*} \fP10\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
35\&.3\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
76\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP1\fI\*{x\*} \fP\fB\*{21\*} \fP120\fI\*{x\*} \fP\fB\*{42\*} \fP89triaugmented_truncated_dodecahedronJ7175621353\fI\*{x\*} \fP\fB\*{35\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{3\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{9\*} \fP5\&.7\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
9\&.8\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
11\&.3\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
18\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
20\&.9\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
21\&.6\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{26\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{52\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{32\*} \fP0\&.307\fI\*{x\*} \fP\fB\*{135\*} \fP36\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{105\*} \fP90tridiminished_icosahedronJ6398153\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{3\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
79\&.2\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
100\&.8\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{6\*} \fP1\fI\*{x\*} \fP\fB\*{15\*} \fP72\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP91tridiminished_rhombicosidodecahedronJ834532753\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{15\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{9\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{3\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
58\&.3\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
63\&.4\fI\*{x\*} \fP\fB\*{30\*} \fP0\&.424\fI\*{x\*} \fP\fB\*{75\*} \fP36\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
72\fI\*{x\*} \fP\fB\*{45\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP92trigyrate_rhombicosidodecahedronJ7560621203\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{12\*} \fP20\&.9\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
26\&.1\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
26\&.6\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
31\&.7\fI\*{x\*} \fP\fB\*{90\*} \fP, 
.br
33\&.3\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
36\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
37\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
40\&.5\fI\*{x\*} \fP\fB\*{60\*} \fP0\&.448\fI\*{x\*} \fP\fB\*{120\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{120\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{60\*} \fP
.PP

.br
 
.SS "Group: platonic"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1cubeHexahedron86124\fI\*{x\*} \fP\fB\*{6\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP2\fI\*{x\*} \fP\fB\*{12\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP2dodecahedron-2012305\fI\*{x\*} \fP\fB\*{12\*} \fP63\&.4\fI\*{x\*} \fP\fB\*{60\*} \fP0\&.714\fI\*{x\*} \fP\fB\*{30\*} \fP72\fI\*{x\*} \fP\fB\*{60\*} \fP3icosahedron-1220303\fI\*{x\*} \fP\fB\*{20\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{120\*} \fP1\&.24\fI\*{x\*} \fP\fB\*{30\*} \fP120\fI\*{x\*} \fP\fB\*{60\*} \fP4octahedron-68123\fI\*{x\*} \fP\fB\*{8\*} \fP70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.41\fI\*{x\*} \fP\fB\*{12\*} \fP120\fI\*{x\*} \fP\fB\*{24\*} \fP5tetrahedron-4463\fI\*{x\*} \fP\fB\*{4\*} \fP109\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP2\&.83\fI\*{x\*} \fP\fB\*{6\*} \fP120\fI\*{x\*} \fP\fB\*{12\*} \fP
.PP

.br
 
.SS "Group: prisms"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1decagonal_prism-2012304\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
10\fI\*{x\*} \fP\fB\*{2\*} \fP36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP0\&.59\fI\*{x\*} \fP\fB\*{30\*} \fP36\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{40\*} \fP2hexagonal_prism-128184\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
6\fI\*{x\*} \fP\fB\*{2\*} \fP60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP0\&.894\fI\*{x\*} \fP\fB\*{18\*} \fP60\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{24\*} \fP3octagonal_prism-1610244\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
8\fI\*{x\*} \fP\fB\*{2\*} \fP45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{32\*} \fP0\&.715\fI\*{x\*} \fP\fB\*{24\*} \fP45\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{32\*} \fP4pentagonal_prism-107154\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{2\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP1\&.01\fI\*{x\*} \fP\fB\*{15\*} \fP72\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
90\fI\*{x\*} \fP\fB\*{20\*} \fP5square_prismCube86124\fI\*{x\*} \fP\fB\*{6\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.15\fI\*{x\*} \fP\fB\*{12\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP6triangular_prism-6593\fI\*{x\*} \fP\fB\*{2\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{3\*} \fP90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{6\*} \fP1\&.31\fI\*{x\*} \fP\fB\*{9\*} \fP90\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{6\*} \fP
.PP

.br
 
.SS "Group: pyramids"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1pentagonal_dipyramidJ13710153\fI\*{x\*} \fP\fB\*{10\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
105\&.2\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
121\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP1\&.18\fI\*{x\*} \fP\fB\*{15\*} \fP120\fI\*{x\*} \fP\fB\*{30\*} \fP2pentagonal_pyramidJ266103\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
5\fI\*{x\*} \fP\fB\*{1\*} \fP41\&.8\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
70\&.5\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
142\&.6\fI\*{x\*} \fP\fB\*{10\*} \fP1\&.17\fI\*{x\*} \fP\fB\*{10\*} \fP72\fI\*{x\*} \fP\fB\*{5\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{15\*} \fP3square_dipryamidOctahedron68123\fI\*{x\*} \fP\fB\*{8\*} \fP70\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.41\fI\*{x\*} \fP\fB\*{12\*} \fP120\fI\*{x\*} \fP\fB\*{24\*} \fP4square_pyramidJ15583\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
4\fI\*{x\*} \fP\fB\*{1\*} \fP70\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
125\&.3\fI\*{x\*} \fP\fB\*{8\*} \fP1\&.41\fI\*{x\*} \fP\fB\*{8\*} \fP90\fI\*{x\*} \fP\fB\*{4\*} \fP, 
.br
120\fI\*{x\*} \fP\fB\*{12\*} \fP5triangular_dipyramidJ125693\fI\*{x\*} \fP\fB\*{6\*} \fP38\&.9\fI\*{x\*} \fP\fB\*{6\*} \fP, 
.br
109\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
123\&.7\fI\*{x\*} \fP\fB\*{12\*} \fP1\&.22\fI\*{x\*} \fP\fB\*{9\*} \fP120\fI\*{x\*} \fP\fB\*{18\*} \fP6triangular_pyramidTetrahedron4463\fI\*{x\*} \fP\fB\*{4\*} \fP109\&.5\fI\*{x\*} \fP\fB\*{12\*} \fP1\&.63\fI\*{x\*} \fP\fB\*{6\*} \fP120\fI\*{x\*} \fP\fB\*{12\*} \fP
.PP

.br
 
.SS "Group: trapezohedron"
.PP
.PP
.PP
no\&.table idother nameverticesfacesedgesface-verticiesface-anglesedge-lengthsedge-angles1decagonal_trapezohedron-2220404\fI\*{x\*} \fP\fB\*{20\*} \fP34\&.7\fI\*{x\*} \fP\fB\*{80\*} \fP, 
.br
69\&.2\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
102\&.8\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
133\&.6\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
150\&.2\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.0991\fI\*{x\*} \fP\fB\*{20\*} \fP, 
.br
1\&.01\fI\*{x\*} \fP\fB\*{20\*} \fP63\&.2\fI\*{x\*} \fP\fB\*{60\*} \fP, 
.br
170\&.4\fI\*{x\*} \fP\fB\*{20\*} \fP2enneagonal_trapezohedron-2018364\fI\*{x\*} \fP\fB\*{18\*} \fP38\&.3\fI\*{x\*} \fP\fB\*{72\*} \fP, 
.br
76\&.1\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
112\&.3\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
141\&.7\fI\*{x\*} \fP\fB\*{36\*} \fP0\&.122\fI\*{x\*} \fP\fB\*{18\*} \fP, 
.br
1\&.02\fI\*{x\*} \fP\fB\*{18\*} \fP63\&.9\fI\*{x\*} \fP\fB\*{54\*} \fP, 
.br
168\&.3\fI\*{x\*} \fP\fB\*{18\*} \fP3heptagonal_trapezohedron-1614284\fI\*{x\*} \fP\fB\*{14\*} \fP48\fI\*{x\*} \fP\fB\*{56\*} \fP, 
.br
94\&.2\fI\*{x\*} \fP\fB\*{28\*} \fP, 
.br
132\fI\*{x\*} \fP\fB\*{28\*} \fP0\&.203\fI\*{x\*} \fP\fB\*{14\*} \fP, 
.br
1\&.03\fI\*{x\*} \fP\fB\*{14\*} \fP66\&.4\fI\*{x\*} \fP\fB\*{42\*} \fP, 
.br
160\&.9\fI\*{x\*} \fP\fB\*{14\*} \fP4hexagonal_trapezohedron-1412244\fI\*{x\*} \fP\fB\*{12\*} \fP54\&.7\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
105\&.5\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
133\&.7\fI\*{x\*} \fP\fB\*{12\*} \fP0\&.277\fI\*{x\*} \fP\fB\*{12\*} \fP, 
.br
1\&.04\fI\*{x\*} \fP\fB\*{12\*} \fP68\&.5\fI\*{x\*} \fP\fB\*{36\*} \fP, 
.br
154\&.4\fI\*{x\*} \fP\fB\*{12\*} \fP5octagonal_trapezohedron-1816324\fI\*{x\*} \fP\fB\*{16\*} \fP42\&.6\fI\*{x\*} \fP\fB\*{64\*} \fP, 
.br
84\&.4\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
122\&.7\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
143\&.6\fI\*{x\*} \fP\fB\*{16\*} \fP0\&.155\fI\*{x\*} \fP\fB\*{16\*} \fP, 
.br
1\&.02\fI\*{x\*} \fP\fB\*{16\*} \fP64\&.9\fI\*{x\*} \fP\fB\*{48\*} \fP, 
.br
165\&.2\fI\*{x\*} \fP\fB\*{16\*} \fP6pentagonal_trapezohedron-1210204\fI\*{x\*} \fP\fB\*{10\*} \fP63\&.4\fI\*{x\*} \fP\fB\*{40\*} \fP, 
.br
116\&.6\fI\*{x\*} \fP\fB\*{20\*} \fP0\&.402\fI\*{x\*} \fP\fB\*{10\*} \fP, 
.br
1\&.05\fI\*{x\*} \fP\fB\*{10\*} \fP72\fI\*{x\*} \fP\fB\*{30\*} \fP, 
.br
144\fI\*{x\*} \fP\fB\*{10\*} \fP7square_trapezohedron-108164\fI\*{x\*} \fP\fB\*{8\*} \fP74\&.9\fI\*{x\*} \fP\fB\*{32\*} \fP, 
.br
118\&.5\fI\*{x\*} \fP\fB\*{8\*} \fP0\&.634\fI\*{x\*} \fP\fB\*{8\*} \fP, 
.br
1\&.08\fI\*{x\*} \fP\fB\*{8\*} \fP78\fI\*{x\*} \fP\fB\*{24\*} \fP, 
.br
125\&.9\fI\*{x\*} \fP\fB\*{8\*} \fP8triangular_trapezohedronCube86124\fI\*{x\*} \fP\fB\*{6\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP1\&.15\fI\*{x\*} \fP\fB\*{12\*} \fP90\fI\*{x\*} \fP\fB\*{24\*} \fP
.SH "Variable Documentation"
.PP 
.SS "dtc_polyhedra_anti_prisms"
<matrix-2x9> \fCanti_prisms\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file anti_prisms\&.scad\&.
.SS "dtc_polyhedra_archimedean"
<matrix-2x9> \fCarchimedean\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file archimedean\&.scad\&.
.SS "dtc_polyhedra_archimedean_duals"
<matrix-2x9> \fCarchimedean_duals\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file archimedean_duals\&.scad\&.
.SS "dtc_polyhedra_cupolas"
<matrix-2x9> \fCcupolas\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file cupolas\&.scad\&.
.SS "dtc_polyhedra_dipyramids"
<matrix-2x9> \fCdipyramids\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file dipyramids\&.scad\&.
.SS "dtc_polyhedra_johnson"
<matrix-2x9> \fCjohnson\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file johnson\&.scad\&.
.SS "dtc_polyhedra_platonic"
<matrix-2x9> \fCplatonic\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file platonic\&.scad\&.
.SS "dtc_polyhedra_polyhedra_all"
<matrix-2x9> \fCpolyhedra_all\fP polyhedra data table columns definition\&. 
.PP
Definition at line 125 of file polyhedra_all\&.scad\&.
.SS "dtc_polyhedra_prisms"
<matrix-2x9> \fCprisms\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file prisms\&.scad\&.
.SS "dtc_polyhedra_pyramids"
<matrix-2x9> \fCpyramids\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file pyramids\&.scad\&.
.SS "dtc_polyhedra_trapezohedron"
<matrix-2x9> \fCtrapezohedron\fP polyhedra data table columns definition\&. 
.PP
Definition at line 114 of file trapezohedron\&.scad\&.
.SS "dtr_polyhedra_anti_prisms"
<matrix-9xR> \fCanti_prisms\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file anti_prisms\&.scad\&.
.SS "dtr_polyhedra_archimedean"
<matrix-9xR> \fCarchimedean\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file archimedean\&.scad\&.
.SS "dtr_polyhedra_archimedean_duals"
<matrix-9xR> \fCarchimedean_duals\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file archimedean_duals\&.scad\&.
.SS "dtr_polyhedra_cupolas"
<matrix-9xR> \fCcupolas\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file cupolas\&.scad\&.
.SS "dtr_polyhedra_dipyramids"
<matrix-9xR> \fCdipyramids\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file dipyramids\&.scad\&.
.SS "dtr_polyhedra_johnson"
<matrix-9xR> \fCjohnson\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file johnson\&.scad\&.
.SS "dtr_polyhedra_platonic"
<matrix-9xR> \fCplatonic\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file platonic\&.scad\&.
.SS "dtr_polyhedra_polyhedra_all"
<matrix-9xR> \fCpolyhedra_all\fP polyhedra data table rows\&. 
.PP
Definition at line 140 of file polyhedra_all\&.scad\&.
.SS "dtr_polyhedra_prisms"
<matrix-9xR> \fCprisms\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file prisms\&.scad\&.
.SS "dtr_polyhedra_pyramids"
<matrix-9xR> \fCpyramids\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file pyramids\&.scad\&.
.SS "dtr_polyhedra_trapezohedron"
<matrix-9xR> \fCtrapezohedron\fP polyhedra data table rows\&. 
.PP
Definition at line 129 of file trapezohedron\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
