.TH "units_angle.scad" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units_angle.scad \- Angle units and conversions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <constants\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBunit_angle_name\fP (units=\fBbase_unit_angle\fP)"
.br
.RI "\fIReturn the name of the given angle \fCunit\fP identifier\&. \fP"
.ti -1c
.RI "function \fBconvert_angle\fP (angle, from=\fBbase_unit_angle\fP, to=\fBbase_unit_angle\fP)"
.br
.RI "\fIConvert the \fCangle\fP from \fCfrom\fP units to \fCto\fP units\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbase_unit_angle\fP = 'd'"
.br
.RI "\fI<string> Base unit for angle measurements\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Angle units and conversions\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&.
.PP
\fBNote:\fP
.RS 4
Include this library file using the \fBinclude\fP statement\&. 
.RE
.PP

.PP
Definition in file \fBunits_angle\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
