.TH "database/geometry/polyhedra/archimedean.scad" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database/geometry/polyhedra/archimedean.scad \- Table of polyhedra data group: \fCarchimedean\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdtc_polyhedra_archimedean\fP"
.br
.ti -1c
.RI "\fBdtr_polyhedra_archimedean\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Table of polyhedra data group: \fCarchimedean\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&.
.PP
This \fComdl\fP formatted data table has been assembled using a script that converts the polyhedra data obtained from \fCAnthony Thyssen\fP's \fCStudies into Polyhedra\fP\&. The vertices are tabulated in both their original Cartesian as well as their converted spherical coordinate form, which is convenient when scaling\&. The data originates from one of three sources:
.PP
.PD 0
.IP "\(bu" 2
\fCExact Mathematics\fP as presented by \fCAnthony Thyssen\fP, 
.IP "\(bu" 2
the \fCPolyhedron Database\fP maintained by \fCNetlib\fP, and 
.IP "\(bu" 2
an \fCEncyclopedia of Polyhedra\fP by \fCGeorge W\&. Hart\fP\&.
.PP
\fBNote:\fP
.RS 4
Include this library file using the \fBinclude\fP statement\&.
.RE
.PP

.PP
Definition in file \fBarchimedean\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
