.TH "utilities" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utilities \- Utilities
.PP
General utilities\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBConsole\fP"
.br
.RI "\fIConsole message logging\&. \fP"
.ti -1c
.RI "\fBValidation\fP"
.br
.RI "\fIFunction validation methods\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconsole\&.scad\fP"
.br
.RI "\fIMessage logging functions\&. \fP"
.ti -1c
.RI "file \fBvalidation\&.scad\fP"
.br
.RI "\fIFunction validation methods\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
General utilities\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
