.TH "datatypes" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes \- Datatypes
.PP
Data type definitions and operators\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBIdentification\fP"
.br
.RI "\fICompile-time data type identification and tests\&. \fP"
.ti -1c
.RI "\fBMaps\fP"
.br
.RI "\fIMap data type operations\&. \fP"
.ti -1c
.RI "\fBOperations\fP"
.br
.RI "\fIData type operation\&. \fP"
.ti -1c
.RI "\fBTables\fP"
.br
.RI "\fITable data type operations\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatatypes\&.scad\fP"
.br
.RI "\fIData type identification and operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_scalar\&.scad\fP"
.br
.RI "\fIScalar data type identification\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_iterable\&.scad\fP"
.br
.RI "\fIIterable data type identification\&. \fP"
.ti -1c
.RI "file \fBdatatypes_identify_list\&.scad\fP"
.br
.RI "\fIList data type identification\&. \fP"
.ti -1c
.RI "file \fBdatatypes_operate_scalar\&.scad\fP"
.br
.RI "\fIScalar data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_operate_iterable\&.scad\fP"
.br
.RI "\fIIterable data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_operate_list\&.scad\fP"
.br
.RI "\fIList data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_map\&.scad\fP"
.br
.RI "\fIMap data type operations\&. \fP"
.ti -1c
.RI "file \fBdatatypes_table\&.scad\fP"
.br
.RI "\fITable data type operations\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data type definitions and operators\&. 

See \fBData types\fP for nomenclature, assumptions, and conventions used to specify values and data types throughout the library\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
