.TH "constants" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants \- Constants
.PP
Design constant definitions\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBEuclidean\fP"
.br
.RI "\fIEuclidean space axis mapping\&. \fP"
.ti -1c
.RI "\fBGeneral\fP"
.br
.RI "\fIGeneral design constants\&. \fP"
.ti -1c
.RI "\fBSystem\fP"
.br
.RI "\fISystem and program limits\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.scad\fP"
.br
.RI "\fIDesign constant definitions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Design constant definitions\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
