.TH "transforms" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transforms \- Transformations
.PP
Shape transformations\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBExtrusions\fP"
.br
.RI "\fIShape Extrusions\&. \fP"
.ti -1c
.RI "\fBReplications\fP"
.br
.RI "\fIShape Replications and distribution\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtransform\&.scad\fP"
.br
.RI "\fIShape transformation functions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape transformations\&. 

  
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
