.TH "datatypes_identify" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes_identify \- Identification
.PP
Compile-time data type identification and tests\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBIterables\fP"
.br
.RI "\fIIterable data type identification\&. \fP"
.ti -1c
.RI "\fBLists\fP"
.br
.RI "\fIList data type identification\&. \fP"
.ti -1c
.RI "\fBScalars\fP"
.br
.RI "\fIScalar data type identification\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatatypes-base\&.scad\fP"
.br
.RI "\fIInclude file wrapper of data types base primitives\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Compile-time data type identification and tests\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
