.TH "constants_general" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants_general \- General
.PP
General design constants\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.scad\fP"
.br
.RI "\fIMechanical design constants\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBeps\fP = 0\&.01"
.br
.RI "\fI<decimal> Epsilon, small distance to deal with overlaping shapes \fP"
.ti -1c
.RI "\fBpi\fP = 3\&.1415926535897932384626433832795"
.br
.RI "\fI<decimal> The ratio of a circle's circumference to its diameter \fP"
.ti -1c
.RI "\fBtau\fP = 2*\fBpi\fP"
.br
.RI "\fI<decimal> The ratio of a circle's circumference to its radius \fP"
.in -1c
.SH "Detailed Description"
.PP 
General design constants\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
