.TH "datatypes_operate_scalar" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes_operate_scalar \- Scalars
.PP
Scalar data type operations\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdatatypes-base\&.scad\fP"
.br
.RI "\fIInclude file wrapper of data types base primitives\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBdefined_or\fP (v, d)"
.br
.RI "\fIReturn a value when it is defined or a default value when it is not\&. \fP"
.ti -1c
.RI "function \fBcircular_index\fP (i, l, f=0)"
.br
.RI "\fIMap an index position into a circularly indexed list\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Scalar data type operations\&. 

See validation \fBresults\fP\&. 
.SH "Function Documentation"
.PP 
.SS "function circular_index (i, l, f = \fC0\fP)"

.PP
Map an index position into a circularly indexed list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi\fP <integer> Any index, in or out of bounds\&. 
.br
\fIl\fP <integer> The circular list length\&. 
.br
\fIf\fP <integer> The starting index number\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<integer> A index position in the circular list within the range \fC[f : l+f-1]\fP\&. 
.RE
.PP

.SS "function defined_or (v, d)"

.PP
Return a value when it is defined or a default value when it is not\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <value> A value\&. 
.br
\fId\fP <value> A default value\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<value> \fCv\fP when it is defined and \fCd\fP otherwise\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
