.TH "constants" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants \- Constants
.PP
General design constants\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBEuclidean\fP"
.br
.RI "\fIEuclidean 2D/3D space mapping\&. \fP"
.ti -1c
.RI "\fBGeneral\fP"
.br
.RI "\fIGeneral design constants\&. \fP"
.ti -1c
.RI "\fBSystem\fP"
.br
.RI "\fISystem/Program limits\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.scad\fP"
.br
.RI "\fIMechanical design constants\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
General design constants\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
