.TH "math_ngon" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math_ngon \- n-gon Solutions
.PP
Regular n-sided polygon computations\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmath\&.scad\fP"
.br
.RI "\fIMathematical functions\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBngon_vp\fP (n, r, vr)"
.br
.RI "\fICompute the vertices for an n-sided equiangular/equilateral regular polygon\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Regular n-sided polygon computations\&. 


.SH "Function Documentation"
.PP 
.SS "function ngon_vp (n, r, vr)"

.PP
Compute the vertices for an n-sided equiangular/equilateral regular polygon\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP <decimal> The number of sides\&. 
.br
\fIr\fP <decimal> The ngon vertex radius\&. 
.br
\fIvr\fP <decimal> The vertex rounding radius\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<vector> A vector [v1, v2, \&.\&.\&., vn] of vectors [x, y] of coordinates\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
vr=5;

hull()
{
  for ( p = ngon_vp( r=20, n=5, vr=vr ) )
    translate( p )
    circle( r=vr );
}

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
