.TH "install" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
install \- Installing 
First install \fCopenscad-amu\fP\&. More information can be found at \fCamu on Thingiverse\fP and in the GitHib \fCamu repository\fP where the source is maintained\&.
.PP
A build script exists for \fILinux\fP and \fICygwin\fP (pull requests for \fImacos\fP are welcome)\&. If \fCwget\fP is not available, here is a downloadable link to the \fCbootstrap\fP script\&.
.PP
.PP
.nf
  $ mkdir tmp && cd tmp

  $ wget https://raw.githubusercontent.com/royasutton/openscad-amu/master/snapshots/bootstrap.{bash,conf} .
  $ chmod +x bootstrap.bash

  $ ./bootstrap.bash --yes --install

  $ openscad-seam -v -V.fi
.PP
.PP
If the last step reports the tool version, then the install most likely completed successfully and the temporary directory may be removed as desired\&.
.PP
Now \fComdl\fP can be compiled, verified, and installed\&. First download the source from \fComdl on Thingiverse\fP or clone the GitHub \fComdl repository\fP and install as follows:
.PP
.PP
.nf
  $ git clone https://github.com/royasutton/omdl.git
  $ cd omdl

  $ make install.fi
.PP
.PP
The library and documentation should now have been installed to the OpenSCAD \fIbuilt-in\fP library location along with the \fComdl\fP reference documentation that can be views with a web browser\&.
.PP
Have a look in: 
.PD 0

.IP "\(bu" 2
\fBLinux:\fP $HOME/\&.local/share/OpenSCAD/libraries 
.IP "\(bu" 2
\fBWindows:\fP My Documents\\OpenSCAD\\libraries
.PP
You may include the desired library component from your project as follows, replacing the version number as needed:
.PP
.PP
.nf
  include <omdl-v0.4/shapes2de.scad>;
  include <omdl-v0.4/shapes3d.scad>;
  ....fi
.PP
 
