.TH "database/geometry/polyhedra Directory Reference" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database/geometry/polyhedra Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBanti_prisms\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCanti_prisms\fP\&. \fP"
.ti -1c
.RI "file \fBarchimedean\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCarchimedean\fP\&. \fP"
.ti -1c
.RI "file \fBarchimedean_duals\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCarchimedean_duals\fP\&. \fP"
.ti -1c
.RI "file \fBcupolas\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCcupolas\fP\&. \fP"
.ti -1c
.RI "file \fBdipyramids\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCdipyramids\fP\&. \fP"
.ti -1c
.RI "file \fBjohnson\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCjohnson\fP\&. \fP"
.ti -1c
.RI "file \fBplatonic\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCplatonic\fP\&. \fP"
.ti -1c
.RI "file \fBpolyhedra_all\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCpolyhedra_all\fP\&. \fP"
.ti -1c
.RI "file \fBprisms\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCprisms\fP\&. \fP"
.ti -1c
.RI "file \fBpyramids\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCpyramids\fP\&. \fP"
.ti -1c
.RI "file \fBtrapezohedron\&.scad\fP"
.br
.RI "\fITable of polyhedra data group: \fCtrapezohedron\fP\&. \fP"
.in -1c
