.TH "math.scad" 3 "Sat Feb 4 2017" "Version v0.5" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math.scad \- Mathematical functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <primitives\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBdistance_pp\fP (p1, p2)"
.br
.RI "\fICompute the distance between two points in a Euclidean 1, 2, or 3D-space\&. \fP"
.ti -1c
.RI "function \fBdot_vv\fP (v1t, v2t, v1i, v2i)"
.br
.RI "\fICompute the dot product of two vectors\&. \fP"
.ti -1c
.RI "function \fBcross_vv\fP (v1t, v2t, v1i, v2i)"
.br
.RI "\fICompute the cross product of two vectors in a Euclidean 3D-space (2D)\&. \fP"
.ti -1c
.RI "function \fBstriple_vvv\fP (v1t, v2t, v3t, v1i, v2i, v3i)"
.br
.RI "\fICompute scalar triple product of two vectors in a Euclidean 3D-space\&. \fP"
.ti -1c
.RI "function \fBangle_vv\fP (v1t, v2t, v1i, v2i)"
.br
.RI "\fICompute the angle between two vectors in a Euclidean 2 or 3D-space\&. \fP"
.ti -1c
.RI "function \fBangle_vvn\fP (v1t, v2t, nvt, v1i, v2i, nvi)"
.br
.RI "\fICompute the angle between two vectors in a Euclidean 3D-space\&. \fP"
.ti -1c
.RI "function \fBunit_v\fP (vt, vi)"
.br
.RI "\fICompute the normalized unit vector for a 1, 2, or 3 term vector\&. \fP"
.ti -1c
.RI "function \fBare_coplanar_vvv\fP (v1t, v2t, v3t, v1i, v2i, v3i)"
.br
.RI "\fITest if three vectors are coplanar in Euclidean 3D-space\&. \fP"
.ti -1c
.RI "function \fBngon_vp\fP (n, r, vr)"
.br
.RI "\fICompute the vertices for an n-sided equiangular/equilateral regular polygon\&. \fP"
.ti -1c
.RI "function \fBtriangle_lll2vp\fP (s1, s2, s3)"
.br
.RI "\fICompute the vertices of a plane triangle given its side lengths\&. \fP"
.ti -1c
.RI "function \fBtriangle_vl2vp\fP (v)"
.br
.RI "\fICompute the vertices of a plane triangle given its side lengths\&. \fP"
.ti -1c
.RI "function \fBtriangle_ppp2vl\fP (v1, v2, v3)"
.br
.RI "\fICompute the side lengths of a triangle given its vertices\&. \fP"
.ti -1c
.RI "function \fBtriangle_vp2vl\fP (v)"
.br
.RI "\fICompute the side lengths of a triangle given its vertices\&. \fP"
.ti -1c
.RI "function \fBtriangle_centroid_ppp\fP (v1, v2, v3)"
.br
.RI "\fICompute the centroid (geometric center) of a triangle\&. \fP"
.ti -1c
.RI "function \fBtriangle_centroid_vp\fP (v)"
.br
.RI "\fICompute the centroid (geometric center) of a triangle\&. \fP"
.ti -1c
.RI "function \fBtriangle_incenter_ppp\fP (v1, v2, v3)"
.br
.RI "\fICompute the coordinate for the triangle's incircle\&. \fP"
.ti -1c
.RI "function \fBtriangle_incenter_vp\fP (v)"
.br
.RI "\fICompute the coordinate for the triangle's incircle\&. \fP"
.ti -1c
.RI "function \fBtriangle_inradius_ppp\fP (v1, v2, v3)"
.br
.RI "\fICompute the inradius of a triangle's incircle\&. \fP"
.ti -1c
.RI "function \fBtriangle_inradius_vp\fP (v)"
.br
.RI "\fICompute the inradius of a triangle's incircle\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mathematical functions\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&.
.PP
\fBNote:\fP
.RS 4
Include this library file using the \fBinclude\fP statement\&. 
.RE
.PP

.PP
Definition in file \fBmath\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
