.TH "units/units_coordinate.scad" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
units/units_coordinate.scad \- Coordinate systems and conversions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <\&.\&./constants\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBcoordinates_name\fP (s=\fBbase_coordinates\fP)"
.br
.RI "\fIReturn the name of the given coordinate system identifier\&. \fP"
.ti -1c
.RI "function \fBconvert_coordinate\fP (c, from=\fBbase_coordinates\fP, to=\fBbase_coordinates\fP)"
.br
.RI "\fIConvert point from one coordinate system to another\&. \fP"
.ti -1c
.RI "function \fBcoordinates_cpc\fP (c, r, t=false)"
.br
.RI "\fIRadially scale a list of 2d cartesian coordinates\&. \fP"
.ti -1c
.RI "function \fBcoordinates_pc\fP (p, r, t=false)"
.br
.RI "\fIRadially scale and convert a list of 2d polar coordinates to cartesian\&. \fP"
.ti -1c
.RI "function \fBcoordinates_csc\fP (c, r, t=false)"
.br
.RI "\fIRadially scale a list of 3d cartesian coordinates\&. \fP"
.ti -1c
.RI "function \fBcoordinates_sc\fP (s, r, t=false)"
.br
.RI "\fIRadially scale and convert a list of 3d spherical coordinates to cartesian\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbase_coordinates\fP = 'c'"
.br
.RI "\fI<string> The base coordinate system\&. \fP"
.ti -1c
.RI "\fBcoordinates_positive_angles\fP = true"
.br
.RI "\fI<boolean> When converting to angular measures add 360 to negative angles\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Coordinate systems and conversions\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBunits_coordinate\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
