.TH "tv_datatypes_operate_scalar_r" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tv_datatypes_operate_scalar_r \- Results 

.PP
.nf
1 ECHO: "OpenSCAD Version [2017, 2, 19]"
2 ECHO: "[ INFO ] run_test(); t01 passed: 'defined_or_D(undef)=default'"
3 ECHO: "[ INFO ] run_test(); t02 passed: 'defined_or_D([])=[]'"
4 ECHO: "[ INFO ] run_test(); t03 passed: 'defined_or_D([0 : 0\&.5 : 9])=[0 : 0\&.5 : 9]'"
5 ECHO: "[ INFO ] run_test(); t04 passed: 'defined_or_D(A string)=A string'"
6 ECHO: "[ INFO ] run_test(); t05 passed: 'defined_or_D(["orange", "apple", "grape", "banana"])=["orange", "apple", "grape", "banana"]'"
7 ECHO: "[ INFO ] run_test(); t06 passed: 'defined_or_D(["b", "a", "n", "a", "n", "a", "s"])=["b", "a", "n", "a", "n", "a", "s"]'"
8 ECHO: "[ INFO ] run_test(); t07 passed: 'defined_or_D([undef])=[undef]'"
9 ECHO: "[ INFO ] run_test(); t08 passed: 'defined_or_D([[1, 2], [2, 3]])=[[1, 2], [2, 3]]'"
10 ECHO: "[ INFO ] run_test(); t09 passed: 'defined_or_D(["ab", [1, 2], [2, 3], [4, 5]])=["ab", [1, 2], [2, 3], [4, 5]]'"
11 ECHO: "[ INFO ] run_test(); t10 passed: 'defined_or_D([[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]])=[[1, 2, 3], [4, 5, 6], [7, 8, 9], ["a", "b", "c"]]'"
12 ECHO: "[ INFO ] run_test(); t11 passed: 'defined_or_D([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]'"

.fi
.PP
 
