.TH "tools_polytope" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools_polytope \- Polytope
.PP
Polygon and polyhedron tools\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtools_polytope\&.scad\fP"
.br
.RI "\fIPolygon and polyhedron tools\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBpolytope_number\fP (c, f, e, vi=true, fi=true, ei=true, sp=false, ts, th, to, tr=0)"
.br
.RI "\fILabel the vertices, paths, and edges of a polytope\&. \fP"
.ti -1c
.RI "module \fBpolytope_frame\fP (c, f, e, vi=true, fi=true, ei=true, vc=1, fc=2, ec=0)"
.br
.RI "\fIAssemble a polytope skeletal frame using child objects\&. \fP"
.ti -1c
.RI "module \fBpolytope_bbox\fP (c, f, a)"
.br
.RI "\fIThe 3d or 2d bounding box shape for a polytope\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Polygon and polyhedron tools\&. 


.SH "Function Documentation"
.PP 
.SS "module polytope_bbox (c, f, a)"

.PP
The 3d or 2d bounding box shape for a polytope\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP <coords-3d|coords-2d> A list of 3d or 2d cartesian coordinates [[x, y (, z)], \&.\&.\&.]\&. 
.br
\fIf\fP <integer-list-list> A list of faces (or paths) that enclose the shape where each face is a list of coordinate indexes\&. 
.br
\fIa\fP <decimal-list-1:3|decimal> The box padding\&. A list of lengths to equally pad the box dimensions\&.
.RE
.PP
Generates: (1) the 3d box shape that completely encloses the defined 3d polyhedron with the box sides oriented parallel to the coordinate axes\&. Or: (2) the 2d box shape that exactly encloses the defined 2d polygon with the box sides oriented parallel to the coordinate axes\&.
.PP
\fBNote:\fP
.RS 4
When \fCf\fP is not given, the listed order of the coordinates \fCc\fP establishes the path\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBpolytope_limits\fP for warning about secondary \fBShapes\fP\&. 
.RE
.PP

.PP
Definition at line 298 of file tools_polytope\&.scad\&.
.SS "module polytope_frame (c, f, e, vi = \fCtrue\fP, fi = \fCtrue\fP, ei = \fCtrue\fP, vc = \fC1\fP, fc = \fC2\fP, ec = \fC0\fP)"

.PP
Assemble a polytope skeletal frame using child objects\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP <coords-3d|coords-2d> A list of 3d or 2d coordinate points\&. 
.br
\fIf\fP <integer-list-list> A list of faces (or paths) that enclose the shape where each face is a list of coordinate indexes\&. 
.br
\fIe\fP <integer-list-2-list> A list of edges where each edge is a list of two coordinate indexes\&.
.br
\fIvi\fP <index> Vertex index\&. An index sequence \fBspecification\fP\&. 
.br
\fIfi\fP <index> Face index\&. An index sequence \fBspecification\fP\&. 
.br
\fIei\fP <index> Edge index\&. An index sequence \fBspecification\fP\&.
.br
\fIvc\fP <integer> Vertex child index\&. 
.br
\fIfc\fP <integer> Face child index\&. 
.br
\fIec\fP <integer> Edge child index\&.
.RE
.PP
This function constructs a skeletal frame for a given polytope\&. A 2d child object is linearly extruded along specified edges of the polytope to form the frame\&. Additional 3d child objects can be centered on specified vertices and/or the mean coordinates of specified faces\&.
.PP
\fBExample\fP 
.PP
.PP
.nf
include <tools/tools_polytope\&.scad>;

s = second(xy_plane_os) * 25;
p = linear_extrude_pp2pf(s, h=50);

polytope_frame(first(p), second(p))
{
  circle(r=2);
  color("grey") sphere(r=4);
  color("blue") cube(4);
}
.fi
.PP
.PP
\fBNote:\fP
.RS 4
To disable a child assignment to the vertices, faces, or edges, use an index that is less than zero or greater than the number of children\&. 
.PP
Parameter \fCf\fP is optional for polygons\&. When it is not given, the listed order of the coordinates \fCc\fP establishes the polygon path\&. 
.PP
When \fCe\fP is not specified, it is computed from \fCf\fP using \fBpolytope_faces2edges()\fP\&. 
.RE
.PP

.PP
Definition at line 216 of file tools_polytope\&.scad\&.
.SS "module polytope_number (c, f, e, vi = \fCtrue\fP, fi = \fCtrue\fP, ei = \fCtrue\fP, sp = \fCfalse\fP, ts, th, to, tr = \fC0\fP)"

.PP
Label the vertices, paths, and edges of a polytope\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP <coords-3d|coords-2d> A list of 3d or 2d coordinate points\&. 
.br
\fIf\fP <integer-list-list> A list of faces (or paths) that enclose the shape where each face is a list of coordinate indexes\&. 
.br
\fIe\fP <integer-list-2-list> A list of edges where each edge is a list of two coordinate indexes\&.
.br
\fIvi\fP <index> Vertex index\&. An index sequence \fBspecification\fP\&. 
.br
\fIfi\fP <index> Face index\&. An index sequence \fBspecification\fP\&. 
.br
\fIei\fP <index> Edge index\&. An index sequence \fBspecification\fP\&.
.br
\fIsp\fP <boolean> Show polyhedron shape\&.
.br
\fIts\fP <decimal> The text size override\&. 
.br
\fIth\fP <decimal> The text extrusion height override\&.
.br
\fIto\fP <vector-3d|vector-2d> The text offset override\&. 
.br
\fItr\fP <decimal-list-1:3|decimal> The text rotation (in degrees)\&.
.RE
.PP
\fBNote:\fP
.RS 4
Parameter \fCf\fP is optional for polygons\&. When it is not given, the listed order of the coordinates \fCc\fP establishes the polygon path\&. 
.PP
When \fCe\fP is not specified, it is computed from \fCf\fP using \fBpolytope_faces2edges()\fP\&. 
.RE
.PP

.PP
Definition at line 78 of file tools_polytope\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
