.TH "constants_euclidean" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants_euclidean \- Euclidean
.PP
Euclidean space axis mapping\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconstants\&.scad\fP"
.br
.RI "\fIDesign constant definitions\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBx_axis_ci\fP = 0"
.br
.RI "\fI<integer> The coordinate axis index for the Euclidean space x-axis\&. \fP"
.ti -1c
.RI "\fBy_axis_ci\fP = 1"
.br
.RI "\fI<integer> The coordinate axis index for the Euclidean space y-axis\&. \fP"
.ti -1c
.RI "\fBz_axis_ci\fP = 2"
.br
.RI "\fI<integer> The coordinate axis index for the Euclidean space z-axis\&. \fP"
.ti -1c
.RI "\fBzero2d\fP = [0, 0]"
.br
.RI "\fI<decimal-list-2> A 2d zero vector (a list with two zeros)\&. \fP"
.ti -1c
.RI "\fBorigin2d\fP = [0, 0]"
.br
.RI "\fI<point-2d> The origin point coordinate in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis2d_uv\fP = [1, 0]"
.br
.RI "\fI<vector-2d> The unit vector of the positive x-axis in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis2d_uv\fP = [0, 1]"
.br
.RI "\fI<vector-2d> The unit vector of the positive y-axis in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis2d_ul\fP = [-\fBx_axis2d_uv\fP, +\fBx_axis2d_uv\fP]"
.br
.RI "\fI<line-2d> A positively-directed unit line centered on the x-axis in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis2d_ul\fP = [-\fBy_axis2d_uv\fP, +\fBy_axis2d_uv\fP]"
.br
.RI "\fI<line-2d> A positively-directed unit line centered on the y-axis in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBzero3d\fP = [0, 0, 0]"
.br
.RI "\fI<decimal-list-2> A 3d zero vector (a list with three zeros)\&. \fP"
.ti -1c
.RI "\fBorigin3d\fP = [0, 0, 0]"
.br
.RI "\fI<point-3d> The origin point coordinate in 3-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis3d_uv\fP = [1, 0, 0]"
.br
.RI "\fI<vector-3d> The unit vector of the positive x-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis3d_uv\fP = [0, 1, 0]"
.br
.RI "\fI<vector-3d> The unit vector of the positive y-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBz_axis3d_uv\fP = [0, 0, 1]"
.br
.RI "\fI<vector-3d> The unit vector of the positive z-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis3d_ul\fP = [-\fBx_axis3d_uv\fP, +\fBx_axis3d_uv\fP]"
.br
.RI "\fI<line-3d> A positively-directed unit line centered on the x-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis3d_ul\fP = [-\fBy_axis3d_uv\fP, +\fBy_axis3d_uv\fP]"
.br
.RI "\fI<line-3d> A positively-directed unit line centered on the y-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBz_axis3d_ul\fP = [-\fBz_axis3d_uv\fP, +\fBz_axis3d_uv\fP]"
.br
.RI "\fI<line-3d> A positively-directed unit line centered on the z-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBxy_plane_on\fP = [\fBorigin3d\fP, \fBz_axis3d_uv\fP]"
.br
.RI "\fI<plane> The right-handed xy plane centered at the origin with normal vector\&. \fP"
.ti -1c
.RI "\fByz_plane_on\fP = [\fBorigin3d\fP, \fBx_axis3d_uv\fP]"
.br
.RI "\fI<plane> The right-handed yz plane centered at the origin with normal vector\&. \fP"
.ti -1c
.RI "\fBzx_plane_on\fP = [\fBorigin3d\fP, \fBy_axis3d_uv\fP]"
.br
.RI "\fI<plane> The right-handed zx plane centered at the origin with normal vector\&. \fP"
.ti -1c
.RI "\fBxy_plane_os\fP = [\fBorigin3d\fP, [for (r=[[1,1],[1,-1],[-1,-1],[-1,1]]) [r[0],r[1],0]]]"
.br
.RI "\fI<plane> The right-handed xy plane centered at the origin with coplanar unit square points\&. \fP"
.ti -1c
.RI "\fByz_plane_os\fP = [\fBorigin3d\fP, [for (r=[[1,1],[1,-1],[-1,-1],[-1,1]]) [0,r[0],r[1]]]]"
.br
.RI "\fI<plane> The right-handed yz plane centered at the origin with coplanar unit square points\&. \fP"
.ti -1c
.RI "\fBzx_plane_os\fP = [\fBorigin3d\fP, [for (r=[[1,1],[1,-1],[-1,-1],[-1,1]]) [r[1],0,r[0]]]]"
.br
.RI "\fI<plane> The right-handed zx plane centered at the origin with coplanar unit square points\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Euclidean space axis mapping\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
