.TH "math_utility" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math_utility \- Utilities
.PP
Miscellaneous mathematical utilities\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmath_utility\&.scad\fP"
.br
.RI "\fIMiscellaneous mathematical utilities\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBhist\fP (v, m=0, cs, cb, cp, ca, cf, d=false)"
.br
.RI "\fIGenerate a histogram for the elements of a list of values\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Miscellaneous mathematical utilities\&. 


.SH "Function Documentation"
.PP 
.SS "function hist (v, m = \fC0\fP, cs, cb, cp, ca, cf, d = \fCfalse\fP)"

.PP
Generate a histogram for the elements of a list of values\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <data> A list of values\&. 
.br
\fIm\fP <integer> The output mode (a 5-bit encoded integer)\&.
.br
\fIcs\fP <string-list-4> A list of strings [s1, s2, s3, fs] (for custom field formatting)\&.
.RE
.PP
\fBReturns:\fP
.RS 4
<list|string> with the occurrence frequency of the elements of \fCv\fP\&.
.RE
.PP
The custom formatting strings are inserted in the output stream as follows:
.PP
.PP
.nf
  s1, value, s2, value-frequency, s3, fs.fi
.PP
.PP
See \fBlstr_html()\fP for description of the html formatting parameters \fCcb\fP, \fCcp\fP, \fCca\fP, \fCcf\fP, and \fCd\fP\&.
.PP
Output mode selection:
.PP
bit Description 0 1  0 output mode numerical string 1-3 string mode format see table see table 4 field separator mode not at end all String output modes:
.PP
B3 B2 B1 B0 Description  1 0 0 0 1 list of strings 3 0 0 1 1 text format 1 9 1 0 0 1 html format 1 15 1 1 1 1 custom formating 
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
