.TH "constants.scad" 3 "Fri Apr 7 2017" "Version v0.6.1" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
constants.scad \- Design constant definitions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBaeps\fP = 0\&.001"
.br
.RI "\fI<decimal> Epsilon, small distance to deal with overlapping shapes\&. \fP"
.ti -1c
.RI "\fBpi\fP = 3\&.14159265358979323"
.br
.RI "\fI<decimal> The ratio of a circle's circumference to its diameter\&. \fP"
.ti -1c
.RI "\fBtau\fP = 2*\fBpi\fP"
.br
.RI "\fI<decimal> The ratio of a circle's circumference to its radius\&. \fP"
.ti -1c
.RI "\fBphi\fP = (1 + sqrt(5)) / 2"
.br
.RI "\fI<decimal> The golden ratio\&. \fP"
.ti -1c
.RI "\fBnumber_max\fP = 1e308"
.br
.RI "\fI<decimal> The largest representable number in OpenSCAD scripts\&. \fP"
.ti -1c
.RI "\fBnumber_min\fP = -1e308"
.br
.RI "\fI<decimal> The smallest representable number in OpenSCAD scripts\&. \fP"
.ti -1c
.RI "\fBempty_str\fP = ''"
.br
.RI "\fI<string> A string with no characters (the empty string)\&. \fP"
.ti -1c
.RI "\fBempty_lst\fP = []"
.br
.RI "\fI<list> A list with no values (the empty list)\&. \fP"
.ti -1c
.RI "\fBx_axis_ci\fP = 0"
.br
.RI "\fI<integer> The coordinate axis index for the Euclidean space x-axis\&. \fP"
.ti -1c
.RI "\fBy_axis_ci\fP = 1"
.br
.RI "\fI<integer> The coordinate axis index for the Euclidean space y-axis\&. \fP"
.ti -1c
.RI "\fBz_axis_ci\fP = 2"
.br
.RI "\fI<integer> The coordinate axis index for the Euclidean space z-axis\&. \fP"
.ti -1c
.RI "\fBzero2d\fP = [0, 0]"
.br
.RI "\fI<decimal-list-2> A 2d zero vector (a list with two zeros)\&. \fP"
.ti -1c
.RI "\fBorigin2d\fP = [0, 0]"
.br
.RI "\fI<point-2d> The origin point coordinate in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis2d_uv\fP = [1, 0]"
.br
.RI "\fI<vector-2d> The unit vector of the positive x-axis in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis2d_uv\fP = [0, 1]"
.br
.RI "\fI<vector-2d> The unit vector of the positive y-axis in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis2d_ul\fP = [-\fBx_axis2d_uv\fP, +\fBx_axis2d_uv\fP]"
.br
.RI "\fI<line-2d> A positively-directed unit line centered on the x-axis in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis2d_ul\fP = [-\fBy_axis2d_uv\fP, +\fBy_axis2d_uv\fP]"
.br
.RI "\fI<line-2d> A positively-directed unit line centered on the y-axis in 2d Euclidean space\&. \fP"
.ti -1c
.RI "\fBzero3d\fP = [0, 0, 0]"
.br
.RI "\fI<decimal-list-2> A 3d zero vector (a list with three zeros)\&. \fP"
.ti -1c
.RI "\fBorigin3d\fP = [0, 0, 0]"
.br
.RI "\fI<point-3d> The origin point coordinate in 3-dimensional Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis3d_uv\fP = [1, 0, 0]"
.br
.RI "\fI<vector-3d> The unit vector of the positive x-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis3d_uv\fP = [0, 1, 0]"
.br
.RI "\fI<vector-3d> The unit vector of the positive y-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBz_axis3d_uv\fP = [0, 0, 1]"
.br
.RI "\fI<vector-3d> The unit vector of the positive z-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBx_axis3d_ul\fP = [-\fBx_axis3d_uv\fP, +\fBx_axis3d_uv\fP]"
.br
.RI "\fI<line-3d> A positively-directed unit line centered on the x-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBy_axis3d_ul\fP = [-\fBy_axis3d_uv\fP, +\fBy_axis3d_uv\fP]"
.br
.RI "\fI<line-3d> A positively-directed unit line centered on the y-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBz_axis3d_ul\fP = [-\fBz_axis3d_uv\fP, +\fBz_axis3d_uv\fP]"
.br
.RI "\fI<line-3d> A positively-directed unit line centered on the z-axis in 3d Euclidean space\&. \fP"
.ti -1c
.RI "\fBxy_plane_on\fP = [\fBorigin3d\fP, \fBz_axis3d_uv\fP]"
.br
.RI "\fI<plane> The right-handed xy plane centered at the origin with normal vector\&. \fP"
.ti -1c
.RI "\fByz_plane_on\fP = [\fBorigin3d\fP, \fBx_axis3d_uv\fP]"
.br
.RI "\fI<plane> The right-handed yz plane centered at the origin with normal vector\&. \fP"
.ti -1c
.RI "\fBzx_plane_on\fP = [\fBorigin3d\fP, \fBy_axis3d_uv\fP]"
.br
.RI "\fI<plane> The right-handed zx plane centered at the origin with normal vector\&. \fP"
.ti -1c
.RI "\fBxy_plane_os\fP = [\fBorigin3d\fP, [for (r=[[1,1],[1,-1],[-1,-1],[-1,1]]) [r[0],r[1],0]]]"
.br
.RI "\fI<plane> The right-handed xy plane centered at the origin with coplanar unit square points\&. \fP"
.ti -1c
.RI "\fByz_plane_os\fP = [\fBorigin3d\fP, [for (r=[[1,1],[1,-1],[-1,-1],[-1,1]]) [0,r[0],r[1]]]]"
.br
.RI "\fI<plane> The right-handed yz plane centered at the origin with coplanar unit square points\&. \fP"
.ti -1c
.RI "\fBzx_plane_os\fP = [\fBorigin3d\fP, [for (r=[[1,1],[1,-1],[-1,-1],[-1,1]]) [r[1],0,r[0]]]]"
.br
.RI "\fI<plane> The right-handed zx plane centered at the origin with coplanar unit square points\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Design constant definitions\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBconstants\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
