.TH "tools_edge" 3 "Tue Apr 4 2017" "Version v0.6" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tools_edge \- Edge
.PP
Shape edge finishing tools\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtools_edge\&.scad\fP"
.br
.RI "\fIShape edge finishing tools\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBedge_profile_r\fP (r, p=0, f=1, a=90,)"
.br
.RI "\fIA 2d edge-finish profile specified by intersection radius\&. \fP"
.ti -1c
.RI "module \fBedge_add_r\fP (r, l=1, p=0, f=1, m=3, ba=45, a1=0, a2=90, center=false)"
.br
.RI "\fIA 3d edge-finish additive shape specified by intersection radius\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Shape edge finishing tools\&. 


.SH "Function Documentation"
.PP 
.SS "module edge_add_r (r, l = \fC1\fP, p = \fC0\fP, f = \fC1\fP, m = \fC3\fP, ba = \fC45\fP, a1 = \fC0\fP, a2 = \fC90\fP, center = \fCfalse\fP)"

.PP
A 3d edge-finish additive shape specified by intersection radius\&. 
.PP
\fBParameters:\fP
.RS 4
\fIr\fP <decimal> The radius length\&. 
.br
\fIl\fP <decimal> The edge length\&.
.br
\fIp\fP <integer> The profile identifier\&. 
.br
\fIf\fP <decimal> The mid-point offset factor\&.
.br
\fIm\fP <integer> The end finish mode: (B0: bottom, B1: top)\&. 
.br
\fIba\fP <decimal> The end bevel angle\&.
.br
\fIa1\fP <decimal> The edge plane start angle\&. 
.br
\fIa2\fP <decimal> The edge plane end angle\&.
.br
\fIcenter\fP <boolean> Center length about origin\&.
.RE
.PP
\fBExample\fP edge_add_r edge_add_r 
.PP
.nf
1       rotate([90,-90,90]) edge_add_r( r=5, l=20, f=5/8, center=true );

.fi
.PP
.PP
m B1 B0 Description  0 0 0 cut bottom (-z) and top (+z) 1 0 1 bevel bottom and cut top 2 1 0 cut bottom and bevel top 3 1 1 bevel bottom and top See \fBedge_profile_r()\fP for description of available profiles\&. 
.PP
Definition at line 208 of file tools_edge\&.scad\&.
.SS "module edge_profile_r (r, p = \fC0\fP, f = \fC1\fP, a = \fC90\fP)"

.PP
A 2d edge-finish profile specified by intersection radius\&. 
.PP
\fBParameters:\fP
.RS 4
\fIr\fP <decimal> The radius length\&. 
.br
\fIp\fP <integer> The profile identifier\&. 
.br
\fIf\fP <decimal> The mid-point offset factor\&. 
.br
\fIa\fP <decimal> The sweep angle\&.
.RE
.PP
\fBExample\fP edge_profile_r edge_profile_r 
.PP
.nf
1       edge_profile_r( r=5, p=1, f=1+10/100, a=75 );

.fi
.PP
.PP
\fBProfiles:\fP 
.PP
p Description  0 Two segment bevel with mid inflection 1 A cove with cut-out offset 2 A quarter round with offset 
.PP
\fBNote:\fP
.RS 4
An offset factor greater than 1 moves the mid-point away from the profile edge-vertex\&. A factor less than 1 move it inwards towards the edge-vertex\&. 
.RE
.PP

.PP
Definition at line 114 of file tools_edge\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
