.TH "shapes_2de" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
shapes_2de \- 2D Extrusions
.PP
Extruded two dimensional geometric shapes\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBshapes2de\&.scad\fP"
.br
.RI "\fILinearly extruded two-dimensional basic shapes\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "module \fBerectangle\fP (size, h, vr, center=false)"
.br
.RI "\fIAn extruded rectangle\&. \fP"
.ti -1c
.RI "module \fBerectangle_c\fP (size, core, h, t, co, cr=0, vr, vr1, vr2, center=false)"
.br
.RI "\fIAn extruded rectangle with a removed rectangular core\&. \fP"
.ti -1c
.RI "module \fBerhombus\fP (size, h, vr, center=false)"
.br
.RI "\fIAn extruded rhombus\&. \fP"
.ti -1c
.RI "module \fBetriangle_ppp\fP (v1, v2, v3, h, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by three vertices\&. \fP"
.ti -1c
.RI "module \fBetriangle_vp\fP (v, h, vr, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by a vector of its three vertices\&. \fP"
.ti -1c
.RI "module \fBetriangle_lll\fP (s1, s2, s3, h, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by its three side lengths\&. \fP"
.ti -1c
.RI "module \fBetriangle_vl\fP (v, h, vr, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by a vector of its three side lengths\&. \fP"
.ti -1c
.RI "module \fBetriangle_vl_c\fP (vs, vc, h, co, cr=0, vr, vr1, vr2, centroid=false, incenter=false, center=false)"
.br
.RI "\fIA general triangle specified by its sides with a removed triangular core\&. \fP"
.ti -1c
.RI "module \fBetriangle_lal\fP (s1, a, s2, h, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by two sides and the included angle\&. \fP"
.ti -1c
.RI "module \fBetriangle_ala\fP (a1, s, a2, h, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by a side and two adjacent angles\&. \fP"
.ti -1c
.RI "module \fBetriangle_aal\fP (a1, a2, s, h, x=1, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded general triangle specified by a side, one adjacent angle and the opposite angle\&. \fP"
.ti -1c
.RI "module \fBetriangle_ll\fP (x, y, h, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded right-angled triangle specified by its opposite and adjacent side lengths\&. \fP"
.ti -1c
.RI "module \fBetriangle_la\fP (x, y, aa, oa, h, vr, v1r, v2r, v3r, centroid=false, incenter=false, center=false)"
.br
.RI "\fIAn extruded right-angled triangle specified by a side length and an angle\&. \fP"
.ti -1c
.RI "module \fBengon\fP (n, r, h, vr, center=false)"
.br
.RI "\fIAn extruded n-sided equiangular/equilateral regular polygon\&. \fP"
.ti -1c
.RI "module \fBeellipse\fP (size, h, center=false)"
.br
.RI "\fIAn extruded ellipse\&. \fP"
.ti -1c
.RI "module \fBeellipse_c\fP (size, core, h, t, co, cr=0, center=false)"
.br
.RI "\fIAn extruded ellipse with a removed elliptical core\&. \fP"
.ti -1c
.RI "module \fBeellipse_s\fP (size, h, a1=0, a2=0, center=false)"
.br
.RI "\fIAn extruded ellipse sector\&. \fP"
.ti -1c
.RI "module \fBeellipse_cs\fP (size, core, h, t, a1=0, a2=0, co, cr=0, center=false)"
.br
.RI "\fIAn extruded sector of an ellipse with a removed elliptical core\&. \fP"
.ti -1c
.RI "module \fBestar2d\fP (size, h, n=5, vr, center=false)"
.br
.RI "\fIAn extruded two dimensional star\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Extruded two dimensional geometric shapes\&. 


.SH "Function Documentation"
.PP 
.SS "module eellipse (size, h, center = \fCfalse\fP)"

.PP
An extruded ellipse\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <vector|decimal> A vector [rx, ry] of decimals or a single decimal for (rx=ry)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP eellipse eellipse 
.PP
.nf
1       eellipse( size=[25, 40], h=20, center=true );

.fi
.PP
 
.PP
Definition at line 758 of file shapes2de\&.scad\&.
.SS "module eellipse_c (size, core, h, t, co, cr = \fC0\fP, center = \fCfalse\fP)"

.PP
An extruded ellipse with a removed elliptical core\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <vector|decimal> A vector [rx, ry] of decimals or a single decimal for (rx=ry)\&. 
.br
\fIcore\fP <vector|decimal> A vector [rx, ry] of decimals or a single decimal for (rx=ry)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIt\fP <vector|decimal> A vector [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIco\fP <vector> Core offset\&. A vector [x, y] of decimals\&. 
.br
\fIcr\fP <decimal> Core z-rotation\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
Thickness \fCt\fP 
.PD 0

.IP "\(bu" 2
\fCcore = size - t\fP; when \fCt\fP and \fCsize\fP are given\&. 
.IP "\(bu" 2
\fCsize = core + t\fP; when \fCt\fP and \fCcore\fP are given\&.
.PP
\fBExample\fP eellipse_c eellipse_c 
.PP
.nf
1       eellipse_c( size=[25,40], core=[16,10], co=[0,10], cr=45, h=20, center=true );

.fi
.PP
 
.PP
Definition at line 798 of file shapes2de\&.scad\&.
.SS "module eellipse_cs (size, core, h, t, a1 = \fC0\fP, a2 = \fC0\fP, co, cr = \fC0\fP, center = \fCfalse\fP)"

.PP
An extruded sector of an ellipse with a removed elliptical core\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <vector|decimal> A vector [rx, ry] of decimals or a single decimal for (rx=ry)\&. 
.br
\fIcore\fP <vector|decimal> A vector [rx, ry] of decimals or a single decimal for (rx=ry)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIt\fP <vector|decimal> A vector [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIa1\fP <decimal> The start angle in degrees\&. 
.br
\fIa2\fP <decimal> The stop angle in degrees\&.
.br
\fIco\fP <vector> Core offset\&. A vector [x, y] of decimals\&. 
.br
\fIcr\fP <decimal> Core z-rotation\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
Thickness \fCt\fP 
.PD 0

.IP "\(bu" 2
\fCcore = size - t\fP; when \fCt\fP and \fCsize\fP are given\&. 
.IP "\(bu" 2
\fCsize = core + t\fP; when \fCt\fP and \fCcore\fP are given\&.
.PP
\fBExample\fP eellipse_cs eellipse_cs 
.PP
.nf
1       eellipse_cs( size=[25,40], t=[10,5], a1=90, a2=180, co=[10,0], cr=45, h=20, center=true );

.fi
.PP
 
.PP
Definition at line 878 of file shapes2de\&.scad\&.
.SS "module eellipse_s (size, h, a1 = \fC0\fP, a2 = \fC0\fP, center = \fCfalse\fP)"

.PP
An extruded ellipse sector\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <vector|decimal> A vector [rx, ry] of decimals or a single decimal for (rx=ry)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIa1\fP <decimal> The start angle in degrees\&. 
.br
\fIa2\fP <decimal> The stop angle in degrees\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP eellipse_s eellipse_s 
.PP
.nf
1       eellipse_s( size=[25,40], h=20, a1=90, a2=180, center=true );

.fi
.PP
 
.PP
Definition at line 833 of file shapes2de\&.scad\&.
.SS "module engon (n, r, h, vr, center = \fCfalse\fP)"

.PP
An extruded n-sided equiangular/equilateral regular polygon\&. 
.PP
\fBParameters:\fP
.RS 4
\fIn\fP <decimal> The number of sides\&. 
.br
\fIr\fP <decimal> The ngon vertex radius\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <decimal> The vertex rounding radius\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP engon engon 
.PP
.nf
1       engon( n=6, r=25, h=20, vr=6, center=true );

.fi
.PP
.PP
See \fCWikipedia\fP for more information\&. 
.PP
Definition at line 728 of file shapes2de\&.scad\&.
.SS "module erectangle (size, h, vr, center = \fCfalse\fP)"

.PP
An extruded rectangle\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <vector|decimal> A vector [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <vector|decimal> The corner rounding radius\&. A vector [v1r, v2r, v3r, v4r] of decimals or a single decimal for (v1r=v2r=v3r=v4r)\&. Unspecified corners are not rounded\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP erectangle erectangle 
.PP
.nf
1       erectangle( size=[25,40], vr=5, h=20, center=true );

.fi
.PP
 
.PP
Definition at line 106 of file shapes2de\&.scad\&.
.SS "module erectangle_c (size, core, h, t, co, cr = \fC0\fP, vr, vr1, vr2, center = \fCfalse\fP)"

.PP
An extruded rectangle with a removed rectangular core\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <vector|decimal> A vector [x, y] of decimals or a single decimal for (x=y)\&. 
.br
\fIcore\fP <vector|decimal> A vector [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIt\fP <vector|decimal> A vector [x, y] of decimals or a single decimal for (x=y)\&.
.br
\fIco\fP <vector> Core offset\&. A vector [x, y] of decimals\&. 
.br
\fIcr\fP <decimal> Core z-rotation\&.
.br
\fIvr\fP <vector|decimal> The default corner rounding radius\&. A vector [v1r, v2r, v3r, v4r] of decimals or a single decimal for (v1r=v2r=v3r=v4r)\&. Unspecified corners are not rounded\&. 
.br
\fIvr1\fP <vector|decimal> The outer corner rounding radius\&. A vector [v1r, v2r, v3r, v4r] of decimals or a single decimal for (v1r=v2r=v3r=v4r)\&. Unspecified corners are not rounded\&. 
.br
\fIvr2\fP <vector|decimal> The core corner rounding radius\&. A vector [v1r, v2r, v3r, v4r] of decimals or a single decimal for (v1r=v2r=v3r=v4r)\&. Unspecified corners are not rounded\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
Thickness \fCt\fP 
.PD 0

.IP "\(bu" 2
\fCcore = size - t\fP; when \fCt\fP and \fCsize\fP are given\&. 
.IP "\(bu" 2
\fCsize = core + t\fP; when \fCt\fP and \fCcore\fP are given\&.
.PP
\fBExample\fP erectangle_c erectangle_c 
.PP
.nf
1       erectangle_c(size=[40,20], t=[10,1], co=[0,-6], cr=10, vr=5, h=30, center=true);

.fi
.PP
 
.PP
Definition at line 157 of file shapes2de\&.scad\&.
.SS "module erhombus (size, h, vr, center = \fCfalse\fP)"

.PP
An extruded rhombus\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <vector|decimal> A vector [w, h] of decimals or a single decimal for (w=h)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <vector|decimal> The corner rounding radius\&. A vector [v1r, v2r, v3r, v4r] of decimals or a single decimal for (v1r=v2r=v3r=v4r)\&. Unspecified corners are not rounded\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP erhombus erhombus 
.PP
.nf
1       erhombus( size=[40,25], h=10, vr=[3,0,3,9], center=true );

.fi
.PP
 
.PP
Definition at line 202 of file shapes2de\&.scad\&.
.SS "module estar2d (size, h, n = \fC5\fP, vr, center = \fCfalse\fP)"

.PP
An extruded two dimensional star\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP <vector|decimal> A vector [l, w] of decimals or a single decimal for (size=l=2*w)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIn\fP <decimal> The number of points\&.
.br
\fIvr\fP <vector|decimal> The vertex rounding radius\&. A vector [v1r, v2r, v3r] of decimals or a single decimal for (v1r=v2r=v3r)\&.
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP estar2d estar2d 
.PP
.nf
1       estar2d( size=[40, 15], h=15, n=5, vr=2, center=true );

.fi
.PP
 
.PP
Definition at line 917 of file shapes2de\&.scad\&.
.SS "module etriangle_aal (a1, a2, s, h, x = \fC1\fP, vr, v1r, v2r, v3r, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded general triangle specified by a side, one adjacent angle and the opposite angle\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa1\fP <decimal> The opposite angle 1 in degrees\&. 
.br
\fIa2\fP <decimal> The adjacent angle 2 in degrees\&. 
.br
\fIs\fP <decimal> The side length\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIx\fP <decimal> The side to draw on the positive x-axis (\fCx=1\fP for \fCs\fP)\&.
.br
\fIvr\fP <decimal> The default vertex rounding radius\&. 
.br
\fIv1r\fP <decimal> Vertex 1 rounding radius\&. 
.br
\fIv2r\fP <decimal> Vertex 2 rounding radius\&. 
.br
\fIv3r\fP <decimal> Vertex 3 rounding radius\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP etriangle_aal etriangle_aal 
.PP
.nf
1       etriangle_aal( a1=60, a2=30, s=40, h=20, vr=2, centroid=true, center=true );

.fi
.PP
 
.PP
Definition at line 580 of file shapes2de\&.scad\&.
.SS "module etriangle_ala (a1, s, a2, h, x = \fC1\fP, vr, v1r, v2r, v3r, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded general triangle specified by a side and two adjacent angles\&. 
.PP
\fBParameters:\fP
.RS 4
\fIa1\fP <decimal> The adjacent angle 1 in degrees\&. 
.br
\fIs\fP <decimal> The side length adjacent to the angles\&. 
.br
\fIa2\fP <decimal> The adjacent angle 2 in degrees\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIx\fP <decimal> The side to draw on the positive x-axis (\fCx=1\fP for \fCs\fP)\&.
.br
\fIvr\fP <decimal> The default vertex rounding radius\&. 
.br
\fIv1r\fP <decimal> Vertex 1 rounding radius\&. 
.br
\fIv2r\fP <decimal> Vertex 2 rounding radius\&. 
.br
\fIv3r\fP <decimal> Vertex 3 rounding radius\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP etriangle_ala etriangle_ala 
.PP
.nf
1       etriangle_ala( a1=30, s=50, a2=60, h=20, vr=2, centroid=true, center=true );

.fi
.PP
 
.PP
Definition at line 528 of file shapes2de\&.scad\&.
.SS "module etriangle_la (x, y, aa, oa, h, vr, v1r, v2r, v3r, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded right-angled triangle specified by a side length and an angle\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP <decimal> The length of the side along the x-axis\&. 
.br
\fIy\fP <decimal> The length of the side along the y-axis\&. 
.br
\fIaa\fP <decimal> The adjacent angle in degrees\&. 
.br
\fIoa\fP <decimal> The opposite angle in degrees\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <decimal> The default vertex rounding radius\&. 
.br
\fIv1r\fP <decimal> Vertex 1 rounding radius\&. 
.br
\fIv2r\fP <decimal> Vertex 2 rounding radius\&. 
.br
\fIv3r\fP <decimal> Vertex 3 rounding radius\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP etriangle_la etriangle_la 
.PP
.nf
1       etriangle_la( x=40, aa=30, h=20, vr=2, centroid=true, center=true );

.fi
.PP
.PP
\fBNote:\fP
.RS 4
When both \fCx\fP and \fCy\fP are given, both triangles are rendered\&. 
.PP
When both \fCaa\fP and \fCoa\fP are given, \fCaa\fP is used\&. 
.RE
.PP

.PP
Definition at line 681 of file shapes2de\&.scad\&.
.SS "module etriangle_lal (s1, a, s2, h, x = \fC1\fP, vr, v1r, v2r, v3r, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded general triangle specified by two sides and the included angle\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs1\fP <decimal> The length of the side 1\&. 
.br
\fIa\fP <decimal> The included angle in degrees\&. 
.br
\fIs2\fP <decimal> The length of the side 2\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIx\fP <decimal> The side to draw on the positive x-axis (\fCx=1\fP for \fCs1\fP)\&.
.br
\fIvr\fP <decimal> The default vertex rounding radius\&. 
.br
\fIv1r\fP <decimal> Vertex 1 rounding radius\&. 
.br
\fIv2r\fP <decimal> Vertex 2 rounding radius\&. 
.br
\fIv3r\fP <decimal> Vertex 3 rounding radius\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP etriangle_lal etriangle_lal 
.PP
.nf
1       etriangle_lal( s1=50, a=60, s2=30, h=20, vr=2, centroid=true, center=true );

.fi
.PP
 
.PP
Definition at line 476 of file shapes2de\&.scad\&.
.SS "module etriangle_ll (x, y, h, vr, v1r, v2r, v3r, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded right-angled triangle specified by its opposite and adjacent side lengths\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP <decimal> The length of the side along the x-axis\&. 
.br
\fIy\fP <decimal> The length of the side along the y-axis\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <decimal> The default vertex rounding radius\&. 
.br
\fIv1r\fP <decimal> Vertex 1 rounding radius\&. 
.br
\fIv2r\fP <decimal> Vertex 2 rounding radius\&. 
.br
\fIv3r\fP <decimal> Vertex 3 rounding radius\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP etriangle_ll etriangle_ll 
.PP
.nf
1       etriangle_ll( x=30, y=40, h=20, vr=2, centroid=true, center=true );

.fi
.PP
 
.PP
Definition at line 629 of file shapes2de\&.scad\&.
.SS "module etriangle_lll (s1, s2, s3, h, vr, v1r, v2r, v3r, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded general triangle specified by its three side lengths\&. 
.PP
\fBParameters:\fP
.RS 4
\fIs1\fP <decimal> The length of the side 1 (along the x-axis)\&. 
.br
\fIs2\fP <decimal> The length of the side 2\&. 
.br
\fIs3\fP <decimal> The length of the side 3\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <decimal> The default vertex rounding radius\&. 
.br
\fIv1r\fP <decimal> Vertex 1 rounding radius\&. 
.br
\fIv2r\fP <decimal> Vertex 2 rounding radius\&. 
.br
\fIv3r\fP <decimal> Vertex 3 rounding radius\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP etriangle_lll etriangle_lll 
.PP
.nf
1       etriangle_lll( s1=30, s2=40, s3=50, h=20, vr=2, centroid=true, center=true );

.fi
.PP
 
.PP
Definition at line 327 of file shapes2de\&.scad\&.
.SS "module etriangle_ppp (v1, v2, v3, h, vr, v1r, v2r, v3r, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded general triangle specified by three vertices\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv1\fP <vector> A vector [x, y] for vertex 1\&. 
.br
\fIv2\fP <vector> A vector [x, y] for vertex 2\&. 
.br
\fIv3\fP <vector> A vector [x, y] for vertex 3\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <decimal> The default vertex rounding radius\&. 
.br
\fIv1r\fP <decimal> Vertex 1 rounding radius\&. 
.br
\fIv2r\fP <decimal> Vertex 2 rounding radius\&. 
.br
\fIv3r\fP <decimal> Vertex 3 rounding radius\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP etriangle_ppp etriangle_ppp 
.PP
.nf
1       etriangle_ppp( v1=[0,0], v2=[5,25], v3=[40,5], h=20, vr=2, centroid=true, center=true );

.fi
.PP
 
.PP
Definition at line 239 of file shapes2de\&.scad\&.
.SS "module etriangle_vl (v, h, vr, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded general triangle specified by a vector of its three side lengths\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector [s1, s2, s3] of decimals\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <vector|decimal> The vertex rounding radius\&. A vector [v1r, v2r, v3r] of decimals or a single decimal for (v1r=v2r=v3r)\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
t = triangle_lll2vp( 3, 4, 5 );
s = triangle_vp2vl( t );
etriangle_vl( v=s, h=5, vr=2 );

.fi
.PP
 
.PP
Definition at line 376 of file shapes2de\&.scad\&.
.SS "module etriangle_vl_c (vs, vc, h, co, cr = \fC0\fP, vr, vr1, vr2, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
A general triangle specified by its sides with a removed triangular core\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvs\fP <vector|decimal> The size\&. A vector [s1, s2, s3] of decimals or a single decimal for (s1=s2=s3)\&. 
.br
\fIvc\fP <vector|decimal> The core\&. A vector [s1, s2, s3] of decimals or a single decimal for (s1=s2=s3)\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIco\fP <vector> Core offset\&. A vector [x, y] of decimals\&. 
.br
\fIcr\fP <decimal> Core z-rotation\&.
.br
\fIvr\fP <vector|decimal> The default vertex rounding radius\&. A vector [v1r, v2r, v3r] of decimals or a single decimal for (v1r=v2r=v3r)\&. 
.br
\fIvr1\fP <vector|decimal> The outer vertex rounding radius\&. A vector [v1r, v2r, v3r] of decimals or a single decimal for (v1r=v2r=v3r)\&. 
.br
\fIvr2\fP <vector|decimal> The core vertex rounding radius\&. A vector [v1r, v2r, v3r] of decimals or a single decimal for (v1r=v2r=v3r)\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP etriangle_vl_c etriangle_vl_c 
.PP
.nf
1       etriangle_vl_c(vs=50, vc=30, h=15, co=[0,-10], cr=180, vr=[2,2,8], centroid=true, center=true);

.fi
.PP
.PP
\fBNote:\fP
.RS 4
The outer and inner triangles centroids are aligned prior to the core removal\&. 
.RE
.PP

.PP
Definition at line 424 of file shapes2de\&.scad\&.
.SS "module etriangle_vp (v, h, vr, centroid = \fCfalse\fP, incenter = \fCfalse\fP, center = \fCfalse\fP)"

.PP
An extruded general triangle specified by a vector of its three vertices\&. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP <vector> A vector [v1, v2, v3] of vectors [x, y]\&.
.br
\fIh\fP <vector|decimal> A vector of decimals or a single decimal to specify simple extrusion height\&.
.br
\fIvr\fP <vector|decimal> The vertex rounding radius\&. A vector [v1r, v2r, v3r] of decimals or a single decimal for (v1r=v2r=v3r)\&.
.br
\fIcentroid\fP <boolean> Center centroid at origin\&. 
.br
\fIincenter\fP <boolean> Center incenter at origin\&. 
.br
\fIcenter\fP <boolean> Center about origin\&.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBst_linear_extrude_scale\fP for a description on specifying \fCh\fP\&.
.RE
.PP
\fBExample\fP 
.PP
.nf
t = triangle_lll2vp( 30, 40, 50 );
r = [2, 4, 6];
etriangle_vp( v=t, h=5, vr=r );

.fi
.PP
 
.PP
Definition at line 288 of file shapes2de\&.scad\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
