.TH "table.scad" 3 "Thu Feb 2 2017" "Version v0.4" "omdl" \" -*- nroff -*-
.ad l
.nh
.SH NAME
table.scad \- Data table encoding and lookup\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <console\&.scad>\fP
.br
\fC#include <primitives\&.scad>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBtable_get_row_idx\fP (rows, row_id)"
.br
.RI "\fIGet the index for a table row identifier\&. \fP"
.ti -1c
.RI "function \fBtable_get_row\fP (rows, row_id)"
.br
.RI "\fIGet the row for a table row identifier\&. \fP"
.ti -1c
.RI "function \fBtable_get_col_idx\fP (cols, col_id)"
.br
.RI "\fIGet the index for a table column identifier\&. \fP"
.ti -1c
.RI "function \fBtable_get_col\fP (cols, col_id)"
.br
.RI "\fIGet the column for a table column identifier\&. \fP"
.ti -1c
.RI "function \fBtable_get\fP (rows, cols, row_id, col_id)"
.br
.RI "\fIGet the value for a table row and column identifier\&. \fP"
.ti -1c
.RI "function \fBtable_get_row_cols\fP (rows, cols, col_id)"
.br
.RI "\fIForm a vector from the specified column of each table row\&. \fP"
.ti -1c
.RI "function \fBtable_get_row_ids\fP (rows)"
.br
.RI "\fIForm a vector of each table row identifier\&. \fP"
.ti -1c
.RI "function \fBtable_exists\fP (rows, cols, row_id, col_id)"
.br
.RI "\fITest the existence of a table row and column identifier\&. \fP"
.ti -1c
.RI "function \fBtable_size\fP (rows, cols)"
.br
.RI "\fIGet the size of a table\&. \fP"
.ti -1c
.RI "module \fBtable_check\fP (rows, cols, verbose=false)"
.br
.RI "\fIPerform some basic validation/checks on a table\&. \fP"
.ti -1c
.RI "module \fBtable_dump\fP (rows, cols, rows_sel, cols_sel, number=true)"
.br
.RI "\fIDump a table to the console\&. \fP"
.ti -1c
.RI "function \fBtable_copy\fP (rows, cols, rows_sel, cols_sel)"
.br
.RI "\fICreate a copy of select rows and columns of a table\&. \fP"
.ti -1c
.RI "function \fBtable_sum\fP (rows, cols, rows_sel, cols_sel)"
.br
.RI "\fISum select rows and columns of a table\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data table encoding and lookup\&. 


.PP
\fBAuthor:\fP
.RS 4
Roy Allen Sutton 
.RE
.PP
\fBDate:\fP
.RS 4
2015-2017
.RE
.PP
\fBCopyright:\fP
.RS 4
.RE
.PP
This file is part of \fComdl\fP, an OpenSCAD mechanical design library\&.
.PP
The \fIomdl\fP is free software; you can redistribute it and/or modify it under the terms of the \fCGNU Lesser General Public License\fP as published by the Free Software Foundation; either version 2\&.1 of the License, or (at your option) any later version\&.
.PP
The \fIomdl\fP is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the GNU Lesser General Public License for more details\&.
.PP
You should have received a copy of the GNU Lesser General Public License along with the \fIomdl\fP; if not, write to the Free Software Foundation, Inc\&., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA; or see http://www.gnu.org/licenses/\&. 
.PP
Definition in file \fBtable\&.scad\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for omdl from the source code\&.
