#
# Jekyll configuration
#
# https://help.github.com/categories/customizing-github-pages
# https://help.github.com/articles/configuring-jekyll
# https://jekyllrb.com/docs/configuration
#

# GitHub Pages theme
theme: jekyll-theme-cayman

# versions
vopenscad:    2021.01

#
# eof
#
